---
title: "SOCIOL 208A Reading Schedule"
---

**THIS IS A LIVE DOCUMENT. CHECK REGULARLY FOR CHANGES**

All lecture notes linked below are hosted on the companion course website: [olizardo.github.io/SOCIOL208](https://olizardo.github.io/SOCIOL208/).

## Week 1: Basic SNA Concepts
### Readings
- Prell, C. & Schaefer, D. R. (2023). Introducing Social Network Analysis. In J. McLevey, J. Scott, P. J. Carrington (Eds.) *The SAGE Handbook of Social Network Analysis*. Sage Publications. [link](https://methods.sagepub.com/book/the-sage-handbook-of-social-network-analysis-2e-srm/i388.xml)
- Light, R. & Moody, J. (2021). Network Basics: Points, Lines, and Positions. In R. Light and J. Moody (Eds.) *The Oxford Handbook of Social Networks* Oxford University Press. [link](https://doi.org/10.1093/oxfordhb/9780190251765.013.2)
- Harary, F. & Norman, R. Z. (1953). Graph Theory as a Mathematical Model in Social Science. Research Center for Group Dynamics, University of Michigan. [link](https://www.idiosophy.com/wp-content/uploads/2017/07/harary-norman.pdf)

### Other Material
- Basic Network Concepts and Definitions [Cheat Sheet](https://cazabetremy.fr/Teaching/CN/Definitions.pdf).
- [Basic Introduction to R](https://inarwhal.github.io/NetworkAnalysisR-book/ch2-intro-R.html)
- [The Basics of the R Programming Language](https://ona-book.org/the-basics-of-the-r-programming-language.html)
- [Short Intergraph Tutorial](https://cran.r-project.org/web/packages/intergraph/vignettes/howto.html)
- [Package networkdata](https://schochastics.github.io/networkdata/)

### Lecture Notes
- [Basic Network Statistics](https://olizardo.github.io/SOCIOL208/basic.html)
- [Directed Graph Statistics](https://olizardo.github.io/SOCIOL208/basic-dir.html)
- [Loading Network Data](https://olizardo.github.io/SOCIOL208/data-loading.html)
- [Working with Lists of Networks](https://olizardo.github.io/SOCIOL208/data-network-lists.html)
- [Selecting Subgraphs](https://olizardo.github.io/SOCIOL208/data-subgraph-select.html)

## Week 2: Centrality
### Readings
- Borgatti, S. P., & Everett, M. G. (2006). A graph-theoretic perspective on centrality. *Social Networks*, 28(4), 466-484. [link](https://doi.org/10.1016/j.socnet.2005.11.005)
- Martin G. Everett & Steve P. Borgatti (2023). "Centrality." In J. McLevey, J. Scott, P. J. Carrington (Eds.) *The SAGE Handbook of Social Network Analysis*. Sage Publications. [link](https://methods.sagepub.com/book/the-sage-handbook-of-social-network-analysis-2e-srm/i4087.xml)
- Freeman, L. C. (1978). Centrality in Social Networks Conceptual Clarification. *Social Networks*, 1(3), 215-239. [pdf](https://www.albany.edu/~ravi/pdfs/freeman_1978.pdf)
- Agneessens, F., Borgatti, S. P., & Everett, M. G. (2017). Geodesic-based centrality: Unifying the local and the global. *Social Networks*, 49, 12-26. [link](https://doi.org/10.1016/j.socnet.2016.09.005)

### Other Material & Further Reading
- Brandes, U., Borgatti, S. P., & Freeman, L. C. (2016). Maintaining the duality of closeness and betweenness centrality. Social networks, 44, 153-159. [link](https://doi.org/10.1016/j.socnet.2015.08.003)
- Koschützki, D., Lehmann, K.A., Peeters, L., Richter, S., Tenfelde-Podehl, D., Zlotowski, O. (2005). Centrality Indices. In: Brandes, U., Erlebach, T. (eds) *Network Analysis. Lecture Notes in Computer Science*, vol 3418. Springer, Berlin, Heidelberg (secs. 3.2, 3.3, and 3.4). [link](https://doi.org/10.1007/978-3-540-31955-9_3)
- Koschützki, D., Lehmann, K.A., Tenfelde-Podehl, D., Zlotowski, O. (2005). Advanced Centrality Concepts. In: Brandes, U., Erlebach, T. (eds) *Network Analysis. Lecture Notes in Computer Science*, vol 3418. Springer, Berlin, Heidelberg. [link](https://doi.org/10.1007/978-3-540-31955-9_5)
- [Comprehensive list of centrality measures with formulas and software](https://www.centiserver.ir/)

### Lecture Notes
- [Degree Centrality](https://olizardo.github.io/SOCIOL208/cent-deg.html)
- [Closeness Centrality](https://olizardo.github.io/SOCIOL208/cent-clos.html)
- [Betweenness Centrality](https://olizardo.github.io/SOCIOL208/cent-bet.html)
- [The Centrality Cube](https://olizardo.github.io/SOCIOL208/cent-cube.html)
- [Random Walk Centrality](https://olizardo.github.io/SOCIOL208/cent-random.html)
- [Edge Centrality](https://olizardo.github.io/SOCIOL208/cent-edge.html)
- [Centrality in Two-Mode Networks](https://olizardo.github.io/SOCIOL208/cent-tm.html)

## Week 3: Ego Networks
### Readings
- Smith, J. A. (2021). The Continued Relevance of Ego Network Data. In R. Light and J. Moody (Eds.) *The Oxford Handbook of Social Networks* Oxford University Press. [link](https://doi.org/10.1093/oxfordhb/9780190251765.013.15)

### Lecture Notes
- [Ego Network Metrics](https://olizardo.github.io/SOCIOL208/basic-ego.html)

## Week 4: Status and Prestige
### Readings
- Franceschet, M. (2011). PageRank: standing on the shoulders of giants. *Communications of the ACM*, 54(6), 92-101. [link](https://doi.org/10.1145/1953122.1953146)
- Gleich, D. F. (2015). PageRank beyond the web. *SIAM Review*, 57(3), 321-363. [link](https://doi.org/10.1137/140976649)
- Martin, J. L. & Murphy, J. P. (2021). Networks, Status, and Inequality. In R. Light and J. Moody (Eds.) *The Oxford Handbook of Social Networks* Oxford University Press. [link](https://doi.org/10.1093/oxfordhb/9780190251765.013.4)
- Rossman, G., Esparza, N., & Bonacich, P. (2010). I'd Like To Thank The Academy, Team Spillovers, and Network Centrality. *American Sociological Review*, 75(1), 31-51. [link](https://doi.org/10.1177/0003122409359164)

### Further (Mathy) Reading
- Vigna, S. (2016). Spectral ranking. Network Science, 4(4), 433-445. [pdf](https://doi.org/10.1017/nws.2016.21)
- Baltz, A., Kliemann, L. (2005). Spectral Analysis. In: Brandes, U., Erlebach, T. (eds) *Network Analysis. Lecture Notes in Computer Science*, vol 3418. Springer, Berlin, Heidelberg. [link](https://doi.org/10.1007/978-3-540-31955-9_14)
- Bonacich, P. (1972). Factoring and Weighting Approaches to Status Scores and Clique Identification. *Journal of Mathematical Sociology*, 2(1), 113-120. [pdf](https://www.tandfonline.com/doi/pdf/10.1080/0022250X.1972.9989806)
- Katz, L. (1953). A New Status Index Derived from Sociometric Analysis. *Psychometrika*, 18(1), 39-43. [pdf](https://link.springer.com/content/pdf/10.1007/BF02289026.pdf)

### Lecture Notes
- [Eigenvector Centrality/Status](https://olizardo.github.io/SOCIOL208/prest-eigen.html)
- [PageRank](https://olizardo.github.io/SOCIOL208/prest-pagerank.html)
- [HITS (Hubs and Authorities)](https://olizardo.github.io/SOCIOL208/prest-hits.html)
- [Status via Maximum Likelihood](https://olizardo.github.io/SOCIOL208/prest-ml.html)
- [Status in Two-Mode Networks](https://olizardo.github.io/SOCIOL208/prest-tm.html)
- [Generalized Two-Mode Status Models](https://olizardo.github.io/SOCIOL208/prest-tm-gen.html)

## Week 5: Similarity, Roles, and Structural Equivalence
### Readings
- Burt, R. S. (1976). Positions in networks. *Social Forces*, 55(1), 93-122. [link](https://doi.org/10.1093/sf/55.1.93)
- Breiger, R. L., Boorman, S. A., & Arabie, P. (1975). An algorithm for clustering relational data with applications to social network analysis and comparison with multidimensional scaling. *Journal of Mathematical Psychology*, 12(3), 328-383. [link](https://doi.org/10.1016/0022-2496(75)90028-0)
- Lü, L., Jin, C. H., & Zhou, T. (2009). Similarity index based on local paths for link prediction of complex networks. *Physical Review E—Statistical, Nonlinear, and Soft Matter Physics*, 80(4), 046122. [link](https://link.aps.org/doi/10.1103/PhysRevE.80.046122)
- Jeh, G., & Widom, J. (2002). Simrank: a measure of structural-context similarity. In *Proceedings of the eighth ACM SIGKDD international conference on Knowledge discovery and data mining* (pp. 538-543). [link](https://doi.org/10.1145/775047.775126)
- Leicht, E. A., Holme, P., & Newman, M. E. (2006). Vertex similarity in networks. *Physical Review E—Statistical, Nonlinear, and Soft Matter Physics*, 73(2), 026120. [link](https://doi.org/10.1103/PhysRevE.73.026120)

### Further Reading
- Fouss, F., Pirotte, A., Renders, J. M., & Saerens, M. (2007). Random-walk computation of similarities between nodes of a graph with application to collaborative recommendation. IEEE Transactions on knowledge and data engineering, 19(3), 355-369. [link](https://ieeexplore.ieee.org/document/4072747)
- Kovács, B. (2010). A generalized model of relational similarity. *Social Networks*, 32(3), 197-211. [link](https://doi.org/10.1016/j.socnet.2010.02.001)
- Liben-Nowell, D., & Kleinberg, J. (2003). The link prediction problem for social networks. In *Proceedings of the Twelfth Annual ACM International Conference on Information and Knowledge Management (CIKM'03)* (pp. 556-559). [link to longer paper](https://www.khoury.northeastern.edu/home/cbw/static/class/5750/papers/link-pred.pdf)
- Lü, L., & Zhou, T. (2011). Link prediction in complex networks: A survey. Physica A: statistical mechanics and its applications, 390(6), 1150-1170. [link](https://doi.org/10.1016/j.physa.2010.11.027)

### Cheat Sheets
- Centrality, Status, and Node Similarity [Cheat Sheet](https://cazabetremy.fr/Teaching/CN/Centralities.pdf).
- Chroł, B & Bojanowski, M. (2018). Proximity-based Methods for Link Prediction. [link](https://cran.r-project.org/web/packages/linkprediction/vignettes/proxfun.html)

### Lecture Notes
- [Structural Equivalence](https://olizardo.github.io/SOCIOL208/sim-structequiv.html)
- [Local Similarity](https://olizardo.github.io/SOCIOL208/sim-loc.html)
- [Similarity in Two-Mode Networks](https://olizardo.github.io/SOCIOL208/sim-tm.html)
- [Global Similarity](https://olizardo.github.io/SOCIOL208/sim-glob.html)
- [Generalized Similarity](https://olizardo.github.io/SOCIOL208/sim-gen.html)
- [Blondel et al. Similarity](https://olizardo.github.io/SOCIOL208/sim-blondel.html)

## Week 6: Community Detection — Foundations
### Readings
- Shai, S., Stanley, N., Granell, C., Taylor, D. & Mucha, P. J. (2021). Case Studies in Network Community Detection. In R. Light and J. Moody (Eds.) *The Oxford Handbook of Social Networks* Oxford University Press. [link](https://doi.org/10.1093/oxfordhb/9780190251765.013.16)
- Newman, M. E. (2018). Community Structure. In *Networks, 2nd Edition*. Oxford, Online Edition, Oxford Academic. [link](https://doi.org/10.1093/oso/9780198805090.003.0014)
- Girvan, M., & Newman, M. E. (2002). Community Structure in Social and Biological Networks. *Proceedings of the National Academy of Sciences*, 99(12), 7821-7826. [link](https://doi.org/10.1073/pnas.122653799)
- Clauset, A., Newman, M. E., & Moore, C. (2004). Finding community structure in very large networks. *Physical Review E—Statistical, Nonlinear, and Soft Matter Physics*, 70(6), 066111. [link](https://doi.org/10.1103/PhysRevE.70.066111)
- Newman, M. E. (2006). Modularity and Community Structure in Networks. *Proceedings of the National Academy of Sciences*, 103(23), 8577-8582. [link](https://www.pnas.org/doi/full/10.1073/pnas.0601602103)
- Melamed, D. (2015). Communities of classes: A network approach to social mobility. *Research in Social Stratification and Mobility*, 41, 56-65. [link](https://doi.org/10.1016/j.rssm.2015.05.001)

### Further (Substantive) Readings
- Moody, J., & Mucha, P. J. (2023). Structural Cohesion and Cohesive Groups. In J. McLevey, J. Scott, P. J. Carrington (Eds.) *The SAGE Handbook of Social Network Analysis*. Sage Publications. [link](https://methods.sagepub.com/book/the-sage-handbook-of-social-network-analysis-2e-srm/i4183.xml)
- Shwed, U., & Bearman, P. S. (2010). The temporal structure of scientific consensus formation. *American Sociological Review*, 75(6), 817-840. [link](https://doi.org/10.1177/0003122410388488)

### Further (Mathy) Reading
- Fortunato, S. (2010). Community Detection in Graphs. *Physics Reports*, 486(3-5), 75-174. [link](https://doi.org/10.1016/j.physrep.2009.11.002)
- Leicht, E. A., and Newman, M. E. (2008). Community Structure in Directed Networks. Physical Review Letters 100, 118703. [link](https://doi.org/10.1103/PhysRevLett.100.118703)
- Newman, M. E., & Girvan, M. (2003). Mixing patterns and community structure in networks. In *Statistical mechanics of complex networks* (pp. 66-87). Berlin, Heidelberg: Springer Berlin Heidelberg.
- Newman, M. E. (2003). Mixing Patterns in Networks. *Physical review E* 67(2), 026126. [link](https://doi.org/10.1103/PhysRevE.67.026126)
- Newman, M. E., & Girvan, M. (2004). Finding and evaluating community structure in networks. Physical Review E, 69(2), 026113. [link](https://doi.org/10.1103/PhysRevE.69.026113)

### Lecture Notes
- [Modularity-Based Detection](https://olizardo.github.io/SOCIOL208/comm-mod.html)
- [Edge-Betweenness (Girvan–Newman)](https://olizardo.github.io/SOCIOL208/comm-edge.html)
- [Spectral Clustering](https://olizardo.github.io/SOCIOL208/comm-spectral.html)

## Week 7: Advanced Community Detection Methods
### Readings
- Palla, G., Derényi, I., Farkas, I., & Vicsek, T. (2005). Uncovering the overlapping community structure of complex networks in nature and society. *Nature*, 435(7043), 814-818. [link](https://doi.org/10.1038/nature03607)
- Ahn, Y.-Y., Bagrow, J. P., & Lehmann, S. (2010). Link communities reveal multiscale complexity in networks. *Nature*, 466(7307), 761-764. [link](https://doi.org/10.1038/nature09182)
- Radicchi, F., Castellano, C., Cecconi, F., Loreto, V., & Parisi, D. (2004). Defining and identifying communities in networks. *Proceedings of the National Academy of Sciences*, 101(9), 2658-2663. [link](https://doi.org/10.1073/pnas.0400054101)
- Lancichinetti, A., Fortunato, S., & Kertész, J. (2009). Detecting the overlapping and hierarchical community structure in complex networks. *New Journal of Physics*, 11(3), 033015. [link](https://doi.org/10.1088/1367-2630/11/3/033015)
- Barber, M. J. (2007). Modularity and community detection in bipartite networks. *Physical Review E*, 76(6), 066102. [link](https://doi.org/10.1103/PhysRevE.76.066102)

### Further (Bipartite/Two-Mode Extensions)
- Wu, G., Gu, C., & Yang, H. (2022). A spectral method of modularity for community detection in bipartite networks. *Europhysics Letters*, 137(3), 31001. [link](https://doi.org/10.1209/0295-5075/ac54c0)
- Murata, T. (2009). Community division of heterogeneous networks. In *Complex Sciences: First International Conference, Complex 2009* (pp. 1011-1022). Springer.
- Suzuki, K., & Wakita, K. (2009). Extracting multi-facet community structure from bipartite networks. In *2009 International Conference on Computational Science and Engineering* (Vol. 4, pp. 312-319). IEEE. [link](https://doi.org/10.1109/CSE.2009.263)

### Lecture Notes
- [Overlapping Communities via Clique Percolation](https://olizardo.github.io/SOCIOL208/comm-overlap-clique.html)
- [Overlapping Communities via Edge Partitions](https://olizardo.github.io/SOCIOL208/comm-overlap-edge.html)
- [Overlapping Communities via Fitness Functions](https://olizardo.github.io/SOCIOL208/comm-overlap-fitness.html)
- [Correspondence Analysis for Community Detection](https://olizardo.github.io/SOCIOL208/comm-ca.html)
- [Spectral Clustering of Two-Mode Networks](https://olizardo.github.io/SOCIOL208/comm-tm-spectral.html)

## Week 8: Analyzing Two-Mode Networks
### Readings
- Breiger, R. L. (1974). The Duality of Persons and Groups. *Social Forces*, 53(2), 181-190. [link](https://www.jstor.org/stable/2576011)
- Borgatti, S. P., & Everett, M. G. (1997). Network Analysis of 2-Mode Data. *Social Networks*, 19(3), 243-269. [pdf](http://www.casos.cs.cmu.edu/events/summer_institute/2006/reading_list/borgatti/Borgatti_Network_Analysis.pdf)
- Everett, M. G., & Borgatti, S. P. (2013). The Dual-Projection Approach for Two-Mode Networks. *Social Networks*, 35(2), 204-210. [link](https://doi.org/10.1016/j.socnet.2012.05.004)
- Neal, Z. (2014). The backbone of bipartite projections: Inferring relationships from co-authorship, co-sponsorship, co-attendance, and other co-behaviors. *Social Networks*, 39, 84-97. [link](https://doi.org/10.1016/j.socnet.2014.06.001)

### Further Reading
- Borgatti, S., & Halgin, D. (2014). Analyzing affiliation networks. In *The SAGE Handbook of Social Network Analysis, First Edition* (pp. 417-433), SAGE Publications Ltd. [link](https://methods.sagepub.com/book/the-sage-handbook-of-social-network-analysis/n28.xml)
- Faust, K. (1997). Centrality in affiliation networks. *Social Networks*, 19(2), 157-191. [link](https://doi.org/10.1016/S0378-8733(96)00300-0)

### Other Material
- Murphy, Phil, and Brendan Knapp. (2018). Bipartite/two-mode networks in igraph. *RPubs* [link](https://rpubs.com/pjmurphy/317838)
- Domagalski, R., Neal, Z. P., & Sagan, B. (2021). Backbone: An R package for extracting the backbone of bipartite projections. Plos one, 16(1), e0244363. [link](https://doi.org/10.1371/journal.pone.0244363)
- Neal, Z. P. (2022). backbone: An R package to extract network backbones. *PloS one*, 17(5), e0269137. [link](https://doi.org/10.1371/journal.pone.0269137)

### Lecture Notes
- [Basic Two-Mode Network Statistics](https://olizardo.github.io/SOCIOL208/tm-basic.html)
- [The Duality of Persons and Groups](https://olizardo.github.io/SOCIOL208/tm-duality.html)
- [Weighted Bipartite Projections](https://olizardo.github.io/SOCIOL208/tm-weighted-proj.html)
- [Two-Mode Correspondence Analysis](https://olizardo.github.io/SOCIOL208/tm-ca.html)
- [Reflections on Two-Mode Analysis](https://olizardo.github.io/SOCIOL208/tm-reflections.html)
- [Two-Mode Fitness Models](https://olizardo.github.io/SOCIOL208/tm-fitness.html)

## Week 9: Statistical Network Models I — Random Graphs, QAP, and Permutation Methods
### Readings
- Krackhardt, D. (1988). Predicting with networks: Nonparametric multiple regression analysis of dyadic data. *Social Networks*, 10(4), 359-381. [link](https://doi.org/10.1016/0378-8733(88)90004-4)
- Maslov, S., & Sneppen, K. (2002). Specificity and stability in topology of protein networks. *Science*, 296(5569), 910-913. [link](https://doi.org/10.1126/science.1065103)
- Orsini, C., Dankulov, M. M., Colomer-de-Simón, P., Jamakovic, A., Mahadevan, P., Vahdat, A., ... & Krioukov, D. (2015). Quantifying randomness in real networks. *Nature communications*, 6(1), 8627. [link](https://doi.org/10.1038/ncomms9627)
- Borgatti, S. P., Agneessens, F., Johnson, J. C., & Everett, M. G. (2024). *Analyzing Social Networks Using R*. SAGE Publications Ltd.

### Further (Two-Mode Null Models)
- Neal, Z. P., Cadieux, A., Garlaschelli, D., Gotelli, N. J., Saracco, F., Squartini, T., Shutters, S. T., Ulrich, W., Wang, G., & Strona, G. (2024). Pattern detection in bipartite networks: A review of terminology, applications, and methods. *PLOS Complex Systems*, 1(2), e0000010. [link](https://doi.org/10.1371/journal.pcsy.0000010)

### Lecture Notes
- [Graph Ensembles and Random Networks](https://olizardo.github.io/SOCIOL208/stat-swap.html)
- [QAP Regression](https://olizardo.github.io/SOCIOL208/stat-qap.html)
- [Statistical Models for Two-Mode Networks](https://olizardo.github.io/SOCIOL208/stat-tm.html)
- [Backbone Extraction via Two-Mode Graph Ensembles](https://olizardo.github.io/SOCIOL208/stat-tm-bb.html)

## Week 10: Statistical Network Models II — Exponential Random Graph Models (ERGMs)
### Readings
- Robins, G., Pattison, P., Kalish, Y., & Lusher, D. (2007). An introduction to exponential random graph (p\*) models for social networks. *Social Networks*, 29(2), 173-191. [link](https://doi.org/10.1016/j.socnet.2006.08.002)
- Morris, M., Handcock, M. S., & Hunter, D. R. (2008). Specification of exponential-family random graph models: terms and computational aspects. *Journal of Statistical Software*, 24(4), 1548. [link](https://www.inf.uni-konstanz.de/exalgo/lehre/ws14/nm/local/papers/specifying_ergms.pdf)
- Pattison, P., & Robins, G. (2002). Neighborhood-based models for social networks. *Sociological Methodology*, 32(1), 301-337. [link](https://doi.org/10.1111/1467-9531.00119)
- Lusher, D., Koskinen, J., & Robins, G. (2013). *Exponential Random Graph Models for Social Networks: Theory, Methods, and Applications*. Cambridge University Press.

### Further Reading
- Lusher D., Wang, P., Brennecke, J., Brailly J., Faye, M., Gallagher, C. (2021). Advances in Exponential Random Graph Models. In R. Light and J. Moody (Eds.), *The Oxford Handbook of Social Networks*, Oxford University Press. [link](https://doi.org/10.1093/oxfordhb/9780190251765.013.18)

### Lecture Notes
- [Introduction to ERGMs](https://olizardo.github.io/SOCIOL208/stat-ergm1.html)
- [ERGM Specification, Estimation, and Goodness of Fit](https://olizardo.github.io/SOCIOL208/stat-ergm2.html)
