---
title: "SOCIOL 208A Reading Schedule (Fall 2024)"
format: 
  html:
    page-layout: full
---

## Week 1, October 2: Basic SNA Concepts

### Readings

- Prell, C. & Schaefer, D. R. (2023). Introducing Social Network Analysis. In J. McLevey, J. Scott, P. J. Carrington (Eds.) *The SAGE Handbook of Social Network Analysis*. Sage Publications. [link](https://methods.sagepub.com/book/the-sage-handbook-of-social-network-analysis-2e-srm/i388.xml)

- Light, R. & Moody, J. (2021). Network Basics: Points, Lines, and Positions. In R. Light, and J. Moody (Eds.) *The Oxford Handbook of Social Networks* Oxford University Press. [link](https://doi.org/10.1093/oxfordhb/9780190251765.013.2)

- Harary, F. & Norman., R. Z. (1953). Graph Theory as a Mathematical Model in Social Science. Research Center for Group Dynamics, University of Michigan. [link](https://www.idiosophy.com/wp-content/uploads/2017/07/harary-norman.pdf)

### Other Material

- [Basic Introduction to R](https://inarwhal.github.io/NetworkAnalysisR-book/ch2-intro-R.html)
- [The Basics of the R Programming Language](https://ona-book.org/the-basics-of-the-r-programming-language.html)
[Short Intergraph Tutorial](https://cran.r-project.org/web/packages/intergraph/vignettes/howto.html)

[Package networkdata](https://schochastics.github.io/networkdata/)

## Week 2, October 9: Centrality

### Readings

- Martin G. Everett & Steve P. Borgatti (2023). "Centrality." In J. McLevey, J. Scott, P. J. Carrington (Eds.) *The SAGE Handbook of Social Network Analysis*. Sage Publications. [link](https://methods.sagepub.com/book/the-sage-handbook-of-social-network-analysis-2e-srm/i4087.xml)

- Freeman, L. C. (1978). Centrality in Social Networks Conceptual Clarification. *Social Networks*, 1(3), 215-239. [pdf](https://www.albany.edu/~ravi/pdfs/freeman_1978.pdf)

- Koschützki, D., Lehmann, K.A., Peeters, L., Richter, S., Tenfelde-Podehl, D., Zlotowski, O. (2005). Centrality Indices. In: Brandes, U., Erlebach, T. (eds) *Network Analysis. Lecture Notes in Computer Science*, vol 3418. Springer, Berlin, Heidelberg (secs. 3.2, 3.3, and 3.4). [link](https://doi.org/10.1007/978-3-540-31955-9_3)

- Neal, Z. P. (2014). A network perspective on the processes of empowered organizations. *American Journal of Community Psychology*, 53, 407-418. [https://doi.org/10.1007/s10464-013-9623-1](link)

- Agneessens, F., Borgatti, S. P., & Everett, M. G. (2017). Geodesic based centrality: Unifying the local and the global. *Social Networks*, 49, 12-26. [link](https://doi.org/10.1016/j.socnet.2016.09.005)

### Explainers

- Lizardo, O. (n.d). Centralities based on Degree. [link](https://olizardo.github.io/networks-textbook/lesson-sna-degree-centrality.html)

- Lizardo, O. (n.d). Centralities based on the Geodesic Distance. [link](https://olizardo.github.io/networks-textbook/lesson-sna-closeness.html)

- Lizardo, O. (n.d). Centralities based on Shortest Paths. [link](https://olizardo.github.io/networks-textbook/lesson-sna-betweenness.html)

### Other Material & Further Reading

- Borgatti, S. P., & Everett, M. G. (2006). A graph-theoretic perspective on centrality. *Social Networks*, 28(4), 466-484. [link](https://doi.org/10.1016/j.socnet.2005.11.005)

- Brandes, U., Borgatti, S. P., & Freeman, L. C. (2016). Maintaining the duality of closeness and betweenness centrality. Social networks, 44, 153-159. [link](https://doi.org/10.1016/j.socnet.2015.08.003)

- Rossman, G., Esparza, N., & Bonacich, P. (2010). I’d Like To Thank The Academy, Team Spillovers, and Network Centrality. *American Sociological Review*, 75(1), 31-51. [link](https://doi.org/10.1177/0003122409359164)

- Koschützki, D., Lehmann, K.A., Tenfelde-Podehl, D., Zlotowski, O. (2005). Advanced Centrality Concepts. In: Brandes, U., Erlebach, T. (eds) *Network Analysis. Lecture Notes in Computer Science*, vol 3418. Springer, Berlin, Heidelberg. [link](https://doi.org/10.1007/978-3-540-31955-9_5)

- [Comprehensive list of centrality measures with formulas and software](https://www.centiserver.ir/)

## Week 3, October 16: Status and Prestige
- Lizardo, O. (n.d.) Status [link](https://olizardo.github.io/networks-textbook/lesson-sna-status.html)

- Franceschet, M. (2011). PageRank: standing on the shoulders of giants. *Communications of the ACM*, 54(6), 92-101. [link](https://doi.org/10.1145/1953122.1953146)

- Martin, J. L. & Murphy, J. P. (2021). Networks, Status, and Inequality. In R. Light, and J. Moody (Eds.) *The Oxford Handbook of Social Networks* Oxford University Press. [link](https://doi.org/10.1093/oxfordhb/9780190251765.013.4)

- Koschützki, D., Lehmann, K.A., Peeters, L., Richter, S., Tenfelde-Podehl, D., Zlotowski, O. (2005). Centrality Indices. In: Brandes, U., Erlebach, T. (eds) *Network Analysis. Lecture Notes in Computer Science*, vol 3418. Springer, Berlin, Heidelberg (sec. 3.9). [link](https://doi.org/10.1007/978-3-540-31955-9_3)

### Further (Mathy) Reading

- Vigna, S. (2016). Spectral ranking. Network Science, 4(4), 433-445. [pdf](https://doi.org/10.1017/nws.2016.21)

- Baltz, A., Kliemann, L. (2005). Spectral Analysis. In: Brandes, U., Erlebach, T. (eds) *Network Analysis. Lecture Notes in Computer Science*, vol 3418. Springer, Berlin, Heidelberg. [link](https://doi.org/10.1007/978-3-540-31955-9_14)

- Bonacich, P. (1972). Factoring and Weighting Approaches to Status Scores and Clique Identification. *Journal of Mathematical Sociology*, 2(1), 113-120. [pdf](https://www.tandfonline.com/doi/pdf/10.1080/0022250X.1972.9989806)

- Katz, L. (1953). A New Status Index Derived from Sociometric Analysis. *Psychometrika*, 18(1), 39-43. [pdf](https://link.springer.com/content/pdf/10.1007/BF02289026.pdf)

## Week 4, October 23:

### No Class (Traveling)

## Week 5, October 30: Similarity, Roles, and Positions

### Readings
- Burt, R. S. (1976). Positions in networks. *Social Forces*, 55(1), 93-122. [link](https://doi.org/10.1093/sf/55.1.93)

- Breiger, R. L., Boorman, S. A., & Arabie, P. (1975). An algorithm for clustering relational data with applications to social network analysis and comparison with multidimensional scaling. *Journal of Mathematical Psychology*, 12(3), 328-383. [link](https://doi.org/10.1016/0022-2496(75)90028-0)

- Lü, L., Jin, C. H., & Zhou, T. (2009). Similarity index based on local paths for link prediction of complex networks. *Physical Review E—Statistical, Nonlinear, and Soft Matter Physics*, 80(4), 046122. [link](https://link.aps.org/doi/10.1103/PhysRevE.80.046122)

- Jeh, G., & Widom, J. (2002). Simrank: a measure of structural-context similarity. In *Proceedings of the eighth ACM SIGKDD international conference on Knowledge discovery and data mining* (pp. 538-543). [link](https://doi.org/10.1145/775047.775126)

- Leicht, E. A., Holme, P., & Newman, M. E. (2006). Vertex similarity in networks. *Physical Review E—Statistical, Nonlinear, and Soft Matter Physics*, 73(2), 026120. [link](https://doi.org/10.1103/PhysRevE.73.026120)

### Further Reading

- Fouss, F., Pirotte, A., Renders, J. M., & Saerens, M. (2007). Random-walk computation of similarities between nodes of a graph with application to collaborative recommendation. IEEE Transactions on knowledge and data engineering, 19(3), 355-369. [link](https://ieeexplore.ieee.org/document/4072747)

- Kovács, B. (2010). A generalized model of relational similarity. *Social Networks*, 32(3), 197-211. [link](https://doi.org/10.1016/j.socnet.2010.02.001)

- Liben-Nowell, D., & Kleinberg, J. (2003). The link prediction problem for social networks. In *Proceedings of the Twelfth Annual ACM International Conference on Information and Knowledge Management (CIKM’03)* (pp. 556-559). [link to longer paper](https://www.khoury.northeastern.edu/home/cbw/static/class/5750/papers/link-pred.pdf)

- Lü, L., & Zhou, T. (2011). Link prediction in complex networks: A survey. Physica A: statistical mechanics and its applications, 390(6), 1150-1170. [link](https://doi.org/10.1016/j.physa.2010.11.027)

### Cheat Sheet:

- Chroł, B & Bojanowski, M. (2018). Proximity-based Methods for Link Prediction. [https://cran.r-project.org/web/packages/linkprediction/vignettes/proxfun.html](https://cran.r-project.org/web/packages/linkprediction/vignettes/proxfun.html)

## Week 6, November 6: Subgroups and Communities 
### Readings
- Moody, J., & Mucha, P. J. (2023). Structural Cohesion and Cohesive Groups. In J. McLevey, J. Scott, P. J. Carrington (Eds.) *The SAGE Handbook of Social Network Analysis*. Sage Publications. [link](https://methods.sagepub.com/book/the-sage-handbook-of-social-network-analysis-2e-srm/i4183.xml)

- Shai, S., Stanley, N., Granell, C., Taylor, D. & Mucha, P. J.  (2021). Case Studies in Network Community Detection. In R. Light, and J. Moody (Eds.) *The Oxford Handbook of Social Networks* Oxford University Press. [link](https://doi.org/10.1093/oxfordhb/9780190251765.013.16)

- Newman, M. E. (2018). Community Structure. In *Networks, 2nd Edition*. Oxford, Online Edition, Oxford Academic. [link](https://doi.org/10.1093/oso/9780198805090.003.0014)

- Fortunato, S. (2010). Community Detection in Graphs. *Physics Reports*, 486(3-5), 75-174. [link](https://doi.org/10.1016/j.physrep.2009.11.002)

### Further Reading

- Newman, M. E. (2006). Modularity and Community Structure in Networks. *Proceedings of the National Academy of Sciences*, 103(23), 8577-8582. [link](https://www.pnas.org/doi/full/10.1073/pnas.0601602103)

- Clauset, A., Newman, M. E., & Moore, C. (2004). Finding community structure in very large networks. *Physical Review E—Statistical, Nonlinear, and Soft Matter Physics*, 70(6), 066111. [link](https://doi.org/10.1103/PhysRevE.70.066111)

- Newman, M. E., & Girvan, M. (2003). Mixing patterns and community structure in networks. In *Statistical mechanics of complex networks* (pp. 66-87). Berlin, Heidelberg: Springer Berlin Heidelberg.

- Newman, M. E. "Mixing patterns in networks." *Physical review E* 67, no. 2 (2003): 026126. [link](https://doi.org/10.1103/PhysRevE.67.026126)

- Girvan, M., & Newman, M. E. (2002). Community Structure in Social and Biological Networks. *Proceedings of the National academy of Sciences*, 99(12), 7821-7826. [link](https://doi.org/10.1073/pnas.122653799)

- Newman, M. E., & Girvan, M. (2004). Finding and evaluating community structure in networks. Physical review E, 69(2), 026113. [link](https://doi.org/10.1103/PhysRevE.69.026113)

- Leicht, E. A., and Newman, M. E. J. (2008). Community Structure in Directed Networks. Physical Review Letters 100, 118703. [link](https://doi.org/10.1103/PhysRevLett.100.118703)

## Week 7, November 13: Analyzing Two-Mode Networks
### Readings
- Breiger, R. L. (1974). The Duality of Persons and Groups. *Social Forces*, 53(2), 181–190. [link](https://www.jstor.org/stable/2576011)

- Borgatti, S. P., & Everett, M. G. (1997). Network Analysis of 2-Mode Data. *Social Networks*, 19(3), 243-269. [pdf](http://www.casos.cs.cmu.edu/events/summer_institute/2006/reading_list/borgatti/Borgatti_Network_Analysis.pdf)

- Everett, M. G., & Borgatti, S. P. (2013). The Dual-Projection Approach for Two-Mode Networks. *Social Networks*, 35(2), 204-210. [link](https://doi.org/10.1016/j.socnet.2012.05.004)

- Neal, Z. (2014). The backbone of bipartite projections: Inferring relationships from co-authorship, co-sponsorship, co-attendance and other co-behaviors. *Social Networks*, 39, 84-97. [link](https://doi.org/10.1016/j.socnet.2014.06.001)

### Other Material

- Domagalski, R., Neal, Z. P., & Sagan, B. (2021). Backbone: An R package for extracting the backbone of bipartite projections. Plos one, 16(1), e0244363. [link](https://doi.org/10.1371/journal.pone.0244363)

- Neal, Z. P. (2022). backbone: An R package to extract network backbones. *PloS one*, 17(5), e0269137. [link](https://doi.org/10.1371/journal.pone.0269137)

## Week 8, November 20: Ego Networks
### Readings
- Smith, J. A. (2021). The Continued Relevance of Ego Network Data. In R. Light, and J. Moody (Eds.) *The Oxford Handbook of Social Networks* Oxford University Press. [link](https://doi.org/10.1093/oxfordhb/9780190251765.013.15)

## Week 9, November 27: Statistical Models of Network Structure 
### Readings
- Lusher D., Wang, P., Brennecke, J., Brailly J., Faye, M., Gallagher, C. (2021). Advances in Exponential Random Graph Models. In R. Light, and J. Moody (Eds.) *The Oxford Handbook of Social Networks* Oxford University Press. [link](https://doi.org/10.1093/oxfordhb/9780190251765.013.15)

## Week 10, December 4:  Dynamic Networks and Relational Events

- TBA
