---
title: "SOCIOL 208A Reading Schedule (Fall 2024)"
format: 
  html:
    page-layout: full
---

## Week 1, October 2: Basic SNA Concepts

### Readings

- Prell, C. & Schaefer, D. R. (2023). Introducing Social Network Analysis. In J. McLevey, J. Scott, P. J. Carrington (Eds.) *The SAGE Handbook of Social Network Analysis*. Sage Publications. [link](https://methods.sagepub.com/book/the-sage-handbook-of-social-network-analysis-2e-srm/i388.xml)

- Light, R. & Moody, J. (2021). Network Basics: Points, Lines, and Positions. In R. Light, and J. Moody (Eds.) *The Oxford Handbook of Social Networks* Oxford University Press. [link](https://doi.org/10.1093/oxfordhb/9780190251765.013.2)

- Harary, F. & Norman., R. Z. (1953). Graph Theory as a Mathematical Model in Social Science. Research Center for Group Dynamics, University of Michigan. [link](https://www.idiosophy.com/wp-content/uploads/2017/07/harary-norman.pdf)

### Other Material

- [Basic Introduction to R](https://inarwhal.github.io/NetworkAnalysisR-book/ch2-intro-R.html)
- [The Basics of the R Programming Language](https://ona-book.org/the-basics-of-the-r-programming-language.html)

## Week 2, October 9: Centrality

### Readings

- Martin G. Everett & Steve P. Borgatti (2023). "Centrality." In J. McLevey, J. Scott, P. J. Carrington (Eds.) *The SAGE Handbook of Social Network Analysis*. Sage Publications. [link](https://methods.sagepub.com/book/the-sage-handbook-of-social-network-analysis-2e-srm/i4087.xml)

- Freeman, L. C. (1978). Centrality in Social Networks Conceptual Clarification. *Social Networks*, 1(3), 215-239. [pdf](https://www.albany.edu/~ravi/pdfs/freeman_1978.pdf)

### Other Material
- [Comprehensive list of centrality measures with formulas and software](https://www.centiserver.ir/)

## Week 3, October 16: Status and Prestige
- Rossman, G., Esparza, N., & Bonacich, P. (2010). I’d Like To Thank The Academy, Team Spillovers, and Network Centrality. *American Sociological Review*, 75(1), 31-51. 

- Martin, J. L. & Murphy, J. P. (2021). Networks, Status, and Inequality. In R. Light, and J. Moody (Eds.) *The Oxford Handbook of Social Networks* Oxford University Press. [link](https://doi.org/10.1093/oxfordhb/9780190251765.013.4)
 
- Bonacich, P. (1972). Factoring and Weighting Approaches to Status Scores and Clique Identification. *Journal of Mathematical Sociology*, 2(1), 113-120.

- Katz, L. (1953). A New Status Index Derived from Sociometric Analysis. *Psychometrika*, 18(1), 39-43.

## Week 4, October 23:

### No Class (Traveling)

## Week 5, October 30: Similarity, Roles, and Positions

### Readings
- White, H. C., Boorman, S. A., & Breiger, R. L. (1976). Social Structure From Multiple Networks. I. Blockmodels of Roles and Positions. *American Journal of Sociology*, 81(4), 730–780. 

## Week 6, November 6: Subgroups and Communities 
### Readings
- Moody, J., & Mucha, P. J. (2023). Structural Cohesion and Cohesive Groups. In J. McLevey, J. Scott, P. J. Carrington (Eds.) *The SAGE Handbook of Social Network Analysis*. Sage Publications. [link](https://methods.sagepub.com/book/the-sage-handbook-of-social-network-analysis-2e-srm/i4183.xml)

- Shai, S., Stanley, N., Granell, C., Taylor, D. & Mucha, P. J.  (2021). Case Studies in Network Community Detection. In R. Light, and J. Moody (Eds.) *The Oxford Handbook of Social Networks* Oxford University Press. [link](https://doi.org/10.1093/oxfordhb/9780190251765.013.16)

- Newman, M. E. (2006). Modularity and Community Structure in Networks. *Proceedings of the National Academy of Sciences*, 103(23), 8577-8582.

- Girvan, M., & Newman, M. E. (2002). Community Structure in Social and Biological Networks. *Proceedings of the National academy of Sciences*, 99(12), 7821-7826.

- Fortunato, S., & Castellano, C. (2007). Community structure in graphs. arXiv preprint arXiv:0712.2716. [link](https://arxiv.org/abs/0712.2716)

## Week 7, November 13: Analyzing Two-Mode Networks
### Readings
- Breiger, R. L. (1974). The Duality of Persons and Groups. *Social Forces*, 53(2), 181–190.
- Borgatti, S. P., & Everett, M. G. (1997). Network Analysis of 2-Mode Data. *Social Networks*, 19(3), 243-269.
- Everett, M. G., & Borgatti, S. P. (2013). The Dual-Projection Approach for Two-Mode Networks. *Social Networks*, 35(2), 204-210.

## Week 8, November 20: Ego Networks
### Readings
- Smith, J. A. (2021). The Continued Relevance of Ego Network Data. In R. Light, and J. Moody (Eds.) *The Oxford Handbook of Social Networks* Oxford University Press. [link](https://doi.org/10.1093/oxfordhb/9780190251765.013.15)

## Week 9, November 27: Statistical Models of Network Structure 
### Readings
- Lusher D., Wang, P., Brennecke, J., Brailly J., Faye, M., Gallagher, C. (2021). Advances in Exponential Random Graph Models. In R. Light, and J. Moody (Eds.) *The Oxford Handbook of Social Networks* Oxford University Press. [link](https://doi.org/10.1093/oxfordhb/9780190251765.013.15)

## Week 10, December 4:  Dynamic Networks and Relational Events
