{
  "hash": "a6df22ef0e044b6d6a9769d8484e80fb",
  "result": {
    "markdown": "---\ntitle: \"Finding Communities via Edge-Deletion\"\nexecute: \n  eval: true\n  echo: true\n  output: true\n  warning: false\n  message: false\nformat: \n   html:\n      code-line-numbers: true\n---\n\n\n## Community Detection Using the Edge-Betweenness\n\nAnother approach to community detection with good sociological bona fides relies on **edge betweenness**, a concept we covered on the [lecture notes on edge centralities](edgecent.qmd). An edge has high betweenness if many other pairs of nodes need to use it to reach one another via shortest paths. \n\nIt follows that if we iteratively identify high betweenness edges, removing the top one, recalculate the edge betweenness on the resulting edge-deleted subgraph, and remove *that* top one (or flip a coin if two are tied), we have an algorithm for identifying communities as those subgraphs that end up being disconnected after removing the bridges [@girvan_newman02]. Note that, like the leading eigenvector method, this approach is **divisive** with all nodes starting in a single cluster, then that cluster splits into two, and so forth.\n\nFor instance, the function below implements a simple version of the Girvan-Newman edge-betweenness community partition algorithm.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n   eb.comms <- function(h, c, s = 123) {\n      d <- 1\n      while(d < c) {\n         eb <- edge_betweenness(h, directed = FALSE)\n         e <- which(eb == max(eb))\n         set.seed(s)\n         if(length(e) > 1) {e <- sample(e, 1)}      \n         h <- delete_edges(h, e)\n         comp <- components(h)\n         d <- comp$no\n         }\n      return(comp$membership)\n      }\n```\n:::\n\n\nThe function takes two inputs: some graph `h` and the number of community partitions desired `c`. Line two initializes the counter `d` which keeps track of the number of **components** in the graph (the number of disconnected clumps). Then we enter a `while` loop on lines 3-11. In line 4 we compute the **edge betweenness** of each edge in the graph (using the `igraph` function `edge_betwenness`), line 5 checks to see which one is the biggest, and lines 6-7 are designed to keep a random one in case of a tie (hence we need to set the seed for reproducibility). Line 8 deletes the selected edge, line 9 computes the number of components in the graph (using the `igraph` function `components` which returns a `list` of results), and line 10 sets the value of `d` to the number of components in the new **edge-deleted subgraph** (stored in the object `comp$no`). The `while` loop stops when the number of components `comm$no` is equal to the function argument `c`. Line 12 returns a vector of community membership assignments. \n\nAnd here's the function in action in the law firm friendship nomination network, requesting a partition into eight groups:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n    library(networkdata)\n    library(igraph)\n    g <- law_friends\n    g <- subgraph(g, degree(g) >= 2)\n    ug <- as_undirected(g, mode = \"collapse\")\n    c8 <- eb.comms(ug, c = 8)\n    c8\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n [1] 1 1 2 1 1 3 2 1 1 1 1 1 1 1 4 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1\n[39] 1 1 1 1 1 1 1 1 1 1 1 5 1 6 1 1 1 1 1 1 1 7 1 1 8 8 8 8 8 8\n```\n:::\n:::\n\n\nWe can check the modularity of this partition using the `igraph` function `modularity.`\n\n\n::: {.cell}\n\n```{.r .cell-code}\n   modularity(ug, c8)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.07147862\n```\n:::\n:::\n\n\nThe resulting partition is shown in @fig-eb-1\n\nNote that edge betweenness provides a different picture of the network's community structure than the eigenvector-based partitioning method. This is not surprising, as it is based on graph-theoretic principles rather than null-model principles such as modularity. The picture here is of two broad communities (in the middle) surrounded by many smaller islands, including some singletons. \n\nIn this respect, we can see that the edge-betweenness algorithm begins by selecting the edges, separating pendant nodes and other peripheral nodes into their own communities, which makes sense, since these are the easiest to disconnect (and the edges connecting them to the graph have the highest betweenness). To reach the \"middle\" or core of the graph, we need to request a partition into more communities. @fig-eb-2 shows the result of using the `eb.comms` function above to partition the network into sixteen communities. Which looks a bit better, uncovering some actual groups of nodes in the periphery of the network that nominate one another as friends.\n\n## Combining Modularity Maximization and Edge-Betweenness\n\nOf course, it is possible to combine the modularity maximization idea with the edge-betweenness partition idea. This is helpful because we usually do not know the actual number of communities in the network; we want the algorithm to tell us. So the trick is to modify the function `eb.comms` above to compute the modularity of a given partition at each step and record it in a vector. That way, we can pick the biggest number after going through all of the edges. \n\nA function that does that looks like this:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n   eb.comms2 <- function(h, s = 123) {\n      k <- 1 #initializing counter\n      qv <- 0 #initializing modularity vector\n      C <- list() #initializing membership vector list\n      og <- h\n      while(ecount(h) > 0) { #do until there are no more edges to delete\n         eb <- edge_betweenness(h, directed = FALSE) #computing edge betweenness\n         e <- which(eb == max(eb)) #grabbing top betweenness edges\n         set.seed(s) #setting seed\n         if(length(e) > 1) {e <- sample(e, 1)} #grabbing an edge at random in case of tie\n         h <- delete_edges(h, e) #deleting top betweenness edge\n         comp <- components(h) #computing number of components of edge-deleted graph\n         C[[k]] <- comp$membership #creating new community membership vector based on component membership\n         qv[k] <- modularity(og, comp$membership, directed = FALSE) #recomputing modularity of original graph\n         k <- k + 1 #increasing counter\n         }\n      maxqpos <- min(which(qv == max(qv))) #picking partition with maximum modularity\n      q <- qv[maxqpos] #picking partition with maximum modularity\n      membership <- C[[maxqpos]] #picking membership vector with maximum modularity\n      nc <- max(membership)\n      return(list(q = q, nc = nc, membership = membership))\n      }\n```\n:::\n\n\nThe main additions here are lines 13 and 14. Line 13 puts the membership vector for the components of the graph in a list object called `C` at each step (the list is initialized to an empty list in line 4). Line 14 computes the modularity (using the `igraph` function `modularity`) *on the original graph* (not the vertex-deleted one), called `og` (get it?) initialized in line 5, but using the membership vector from the components of the vertex-deleted subgraph at a given step as community assignments. After the `while` loop ends (going through all the edges), lines 17-20 grab the community assignments corresponding to the maximum number stored in the modularity vector `qv`, and line 21 returns a list containing membership vector stored in the object `membership`, a scalar recording the number of communities (the maximum number in the membership vector) stored in the object `nc`, and a scalar recording the maximum modularity value stored in the object `q`. \n\nLet's see the new and improved algorithm in action:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n   c.mod <- eb.comms2(ug)\n   c.mod\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n$q\n[1] 0.2078357\n\n$nc\n[1] 23\n\n$membership\n [1]  1  1  2  1  3  4  2  1  1  1  1  1  1  5  6  1  1  3  7  1  1  1  1  1  1\n[26]  1  1  3  1  8  1  3  3  1  3  1  1  1  1  1  1  1  9  7 10 11  3  3 12 13\n[51] 14 15 16 17  3 18  7 19 20 21 22  1 23 23 23 23 23 23\n```\n:::\n:::\n\nWhich tells us that the optimal partition according to the edge betweenness is one that splits the graph into 23 communities, with a maximum modularity of Q = 0.208. \n\nOf course, all of these steps are packaged in the `igraph` function called `cluster_edge_betweenness`. Let's see how that works.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n   eb.res <- cluster_edge_betweenness(ug, directed = FALSE)\n```\n:::\n\n\nNote that the `cluster_edge_betweenness` function takes a graph as input. We have to tell it that is an undirected graph by setting the argument `directed` to `FALSE`. \n\nAnd as we can see, the results are exactly the same we obtained earlier, dividing the nodes in the network into 23 communities. \n:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n   eb.res$membership\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n [1]  1  1  2  1  3  4  2  1  1  1  1  1  1  5  6  1  1  3  7  1  1  1  1  1  1\n[26]  1  1  3  1  8  1  3  3  1  3  1  1  1  1  1  1  1  9  7 10 11  3  3 12 13\n[51] 14 15 16 17  3 18  7 19 20 21 22  1 23 23 23 23 23 23\n```\n:::\n:::\n\n\nInterestingly, even though the Girvan-Newman approach is clearly a divisive algorithm, the results can be presented as a dendrogram, but storing top-down divisions rather than bottom-up merges. This is shown in @fig-ebdendro\n\n\n::: {.cell}\n\n```{.r .cell-code}\n   hc <- as.hclust(eb.res)\n   par(cex = 0.5) #smaller labels\n   plot(hc)\n```\n\n::: {.cell-output-display}\n![Dendrogram of Community Partition of the Law Friends Network Using the Edge-Betweenness.](edge-deletion_files/figure-html/fig-ebdendro-1.png){#fig-ebdendro width=768}\n:::\n:::\n\n\nAnother thing we can do with the `edge_betweenness` function output is highlight the edges identified as **bridges** during the divisive process, since this information is stored in the `bridges` object. We can use this vector of edge ids to create an edge color vector that will highlight the bridges in red. This is shown in @fig-eb-3. \n\n## Community Detection Using the Edge Clustering Coefficient\n\n@radicchi_etal04 propose another version of an edge-deletion approach to community detection based on an edge-level metric they call the **edge clustering coefficient** ($C(e_{ij})$). This  is essentially a measure of the extent to which an edge connects nodes who themselves share a lot of neighbors, normalized by the minimum of the degrees of the nodes minus one:\n\n$$\nC(e_{ij}) = \\frac{z_{ij} + 1}{min\\left[(k_i - 1), (k_j - 1)\\right]}\n$$ {#eq-eclust}\n\nWhere $z_{ij}$ is the number of common neighbors shared by nodes $i$ and $j$ incident to edge $e_{ij}$, and $k_i$ and $k_j$ are their respective degrees. @radicchi_etal04 add one to the numerator of @eq-eclust to account for the fact that some connected nodes may not share any neighbors.\n\nThe logic of the @radicchi_etal04 approach is that edges that go between well-clustered communities should have a *low* edge clustering coefficient (e.g., connecting nodes who themselves don't share many neighbors and therefore belong to different communities). Meanwhile, edges with a high clustering coefficient should be more likely to link nodes that belong to the same community. \n\nErgo, deleting the edges with low edge clustering coefficient (like we did with the ones that had high edge betweenness) should partition a graph into well-defined communities. \n\nTo implement this approach we need (1) a function to compute the clustering coefficient for each edge according to @eq-eclust, and (2) a modification of the `eb.comms2` function above that incorporates the idea of removing edges with minimum edge clustering scores. \n\nTo complete step 1, here's a function to compute the edge clustering coefficient as defined by @radicchi_etal04:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n    edge.clust <- function(h) {\n        d <- degree(h) #degree vector\n        e <- as_edgelist(h, names = FALSE) #graph edge list\n        w <- as.matrix(as_adjacency_matrix(h)) #graph adjacency matrix\n        m <- w %*% w #commons neighbors matrix\n        ec <- 0 #initializing edge clustering coefficient vector\n        for (r in 1:nrow(e)) {\n            i <- e[r, 1] #first node\n            j <- e[r, 2] #second node\n            z <- m[i, j] #shared neighbors\n            ec[r] <- (z + 1) / min((d[i] - 1), (d[j] - 1)) #edge clustering coefficient\n            }\n        return(ec)\n        }\n```\n:::\n\n\nThis function takes some graph `h` as input and returns a vector of length $|E|$ (number of edges in the graph) containing the estimated clustering coefficient of each edge as components. Note that we compute the number of shared neighbors by taking the second power of the adjacency matrix in lines 4 and 5. The `for` loop then goes through each edge and computes the clustering coefficient in line 11. \n\nAnd to complete step 2, here's a modification of our edge-deletion function above to incorporate the edge clustering coefficient as the criterion for edge deletion:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n   ec.comms <- function(h) {\n      k <- 1 #initializing counter\n      qv <- 0 #initializing modularity vector\n      C <- list() #initializing membership vector list\n      og <- h\n      while(ecount(h) > 0) { #do until there are no more edges to delete\n         ec <- edge.clust(h) #computing edge clustering coefficient vector\n         e <- which(ec == min(ec)) #grabbing minimum clustering edges\n         h <- delete_edges(h, e) #deleting minimum clustering edges\n         comp <- components(h) #computing number of components of edge-deleted graph\n         C[[k]] <- comp$membership #creating new community membership vector based on component membership\n         qv[k] <- modularity(og, comp$membership, directed = FALSE) #recomputing modularity of original graph\n         k <- k + 1 #increasing counter\n         }\n      maxqpos <- min(which(qv == max(qv))) #picking partition with maximum modularity\n      q <- qv[maxqpos] #picking partition with maximum modularity\n      membership <- C[[maxqpos]] #picking membership vector with maximum modularity\n      nc <- max(membership)\n      return(list(q = q, nc = nc, membership = membership))\n      }\n```\n:::\n\n\nNote that the main difference between this function and the one we used for the edge betweenness is that instead of flipping a coin and selecting a random edge in case of a tie, we now deterministically kill *all* edges that have minimum clustering (usually zero or a number close to zero) in line 9. \n\nAnd here are the results for the `law_friends` network:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n    ec <- ec.comms(ug)\n    ec\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n$q\n[1] 0.3216964\n\n$nc\n[1] 6\n\n$membership\n [1] 1 1 2 2 2 2 2 1 1 1 1 1 1 2 1 1 1 2 3 1 1 1 1 1 1 4 1 2 1 4 2 2 2 4 2 4 1 4\n[39] 1 3 3 4 3 3 4 3 2 2 3 5 3 3 3 3 2 2 3 3 3 2 3 3 6 6 6 6 6 6\n```\n:::\n:::\n\n::: {#fig-eb .cell layout-ncol=\"2\"}\n::: {.cell-output-display}\n![Community Partition According to the Edge Betweenness (C = 8).](edge-deletion_files/figure-html/fig-eb-1.png){#fig-eb-1 width=1152}\n:::\n\n::: {.cell-output-display}\n![Community Partition According to the Edge Betweenness (C = 16).](edge-deletion_files/figure-html/fig-eb-2.png){#fig-eb-2 width=1152}\n:::\n\n::: {.cell-output-display}\n![Community Partition According to the Edge Betweenness with Maximum Modularity (C = 23).](edge-deletion_files/figure-html/fig-eb-3.png){#fig-eb-3 width=1152}\n:::\n\n::: {.cell-output-display}\n![Community Partition According to the Edge Clustering with Maximum Modularity (C = 6).](edge-deletion_files/figure-html/fig-eb-4.png){#fig-eb-4 width=1152}\n:::\n\nUndirected Law Firm Friendship Network.\n:::\n\n\nWhich suggests a partition into 6 communities with a modularity score of 0.322 outperforming the best edge-betweenness partition by this metric.  \n\n@fig-eb-4 shows the resulting communities obtained from the edge-clustering coefficient approach. As shown in the Figure, the edge-clustering coefficient approach produces strongly defined, intuitive communities, grouping together densely connected groups of nodes.",
    "supporting": [
      "edge-deletion_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}