<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Random Walk Concepts in Networks – SOCIOL 208</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark-0a6b7249c26820e032cb0bd839ff02b1.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-3df00d2004a49d77fb7f0cfec873761a.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark-21e387a8c6bfe5d56933bd7053f44136.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="site_libs/bootstrap/bootstrap-3df00d2004a49d77fb7f0cfec873761a.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
<meta property="og:title" content="Random Walk Concepts in Networks – SOCIOL 208">
<meta property="og:description" content="">
<meta property="og:site_name" content="SOCIOL 208">
</head>

<body class="nav-sidebar docked quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./syllabus-208A.html">208A</a></li><li class="breadcrumb-item">Lecture Notes</li><li class="breadcrumb-item"><a href="./basic.html">Basic Concepts</a></li><li class="breadcrumb-item"><a href="./basic-random.html">Random Walk Concepts in Networks</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">SOCIOL 208</a> 
        <div class="sidebar-tools-main">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Home</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">208A</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./syllabus-208A.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">208A Syllabus</span></a>
  </div>
</li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Lecture Notes</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth2 show">  
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Basic Concepts</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth3 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./basic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Basic Network Statistics</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./basic-dir.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Basic Network Statistics for Directed Graphs</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./basic-ego.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Analyzing Ego Networks</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./basic-tm.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Analyzing Two-Mode Networks</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./basic-tm-duality.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">The Duality of Persons and Groups</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./basic-eigen.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Matrix Eigendecomposition</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./basic-random.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Random Walk Concepts in Networks</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false">
 <span class="menu-text">Centrality</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth3 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cent-deg.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Degree Centrality</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cent-clos.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Closeness Centrality</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cent-bet.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Betweenness Centrality</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cent-cube.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">The Centrality Cube</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cent-random.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Random Walk Centralities</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cent-edge.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Edge Centralities</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cent-tm.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Centrality in Two-Mode Networks</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false">
 <span class="menu-text">Status and Prestige</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth3 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prest-eigen.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Status and Prestige</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prest-pagerank.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">PageRank Prestige Scoring</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prest-hits.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Hubs and Authorities</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prest-ml.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Prestige in Multilayer Networks</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prest-tm.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Status and Prestige in Two Mode Networks</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false">
 <span class="menu-text">Equivalence and Similarity</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth3 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./sim-structequiv.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Structural Equivalence</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./sim-loc.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Local Vertex Similarities</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./sim-tm.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Similarity and Equivalence in Two-Mode Networks</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./sim-glob.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Global Vertex Similarities</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./sim-gen.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Role Similarities</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./sim-blondel.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Structural Similarity Across Graphs</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false">
 <span class="menu-text">Communities and Clustering</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth3 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./comm-mod.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Community Structure</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./comm-edge.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Finding Communities via Edge-Deletion</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./comm-spectral.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Community Detection Using Spectral Clustering</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./comm-tm-spectral.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Spectral Clustering of Two-Mode Networks</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./comm-ca.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Community Detection in Two-Mode Networks Using CA</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./comm-overlap-clique.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Using Cliques to Assign Nodes to Overlapping Communities</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./comm-overlap-edge.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Using Link Clustering to Assign Nodes to Overlapping Communities</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./comm-overlap-fitness.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Finding Overlapping Communities by Optimizing Local Fitness Functions</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="false">
 <span class="menu-text">Two Mode Networks</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth3 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./tm-ca.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Correspondence Analysis (CA) of Two-Mode Networks</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./tm-reflections.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">The Method of Reflections in Two-Mode Networks</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./tm-fitness.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Fitness and Complexity in Two Mode Networks</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="false">
 <span class="menu-text">Statistical Models</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth3 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-swap.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Graph Ensembles in Networks</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-qap.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Network Regression Using Permutation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tm.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Graph Ensembles in Two-Mode Networks</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-tm-bb.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Extracting the Backbone of Bipartite Projections Using Two-Mode Graph Ensembles</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-ergm1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exponential Random Graphs Models I</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./stat-ergm2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exponential Random Graphs Models II</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="false">
 <span class="menu-text">Data Management</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-10" class="collapse list-unstyled sidebar-section depth3 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data-loading.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Loading Network Data from a File</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data-network-lists.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Handling Graph Objects in Lists</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data-subgraph-select.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Selecting a Subgraph Based on Edge Conditions</span></a>
  </div>
</li>
      </ul>
  </li>
      </ul>
  </li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" role="navigation" aria-expanded="true">
 <span class="menu-text">208B</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-11" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./syllabus-208B.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">208B Syllabus</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./schedule-208B-S22.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">SOCIOL 208B Reading Schedule (Spring 2022)</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#the-average-first-passage-time" id="toc-the-average-first-passage-time" class="nav-link active" data-scroll-target="#the-average-first-passage-time"><span class="header-section-number">1</span> The Average First Passage Time</a>
  <ul class="collapse">
  <li><a href="#computing-the-afpt-by-iterating-until-convergence" id="toc-computing-the-afpt-by-iterating-until-convergence" class="nav-link" data-scroll-target="#computing-the-afpt-by-iterating-until-convergence"><span class="header-section-number">1.1</span> Computing the AFPT by Iterating Until Convergence</a></li>
  </ul></li>
  <li><a href="#computing-the-afpt-using-the-laplacian-matrix" id="toc-computing-the-afpt-using-the-laplacian-matrix" class="nav-link" data-scroll-target="#computing-the-afpt-using-the-laplacian-matrix"><span class="header-section-number">2</span> Computing the AFPT Using the Laplacian Matrix</a></li>
  <li><a href="#computing-the-afpt-using-a-big-matrix-formula" id="toc-computing-the-afpt-using-a-big-matrix-formula" class="nav-link" data-scroll-target="#computing-the-afpt-using-a-big-matrix-formula"><span class="header-section-number">3</span> Computing the AFPT Using a Big Matrix Formula</a></li>
  <li><a href="#the-average-commute-distance" id="toc-the-average-commute-distance" class="nav-link" data-scroll-target="#the-average-commute-distance"><span class="header-section-number">4</span> The Average Commute Distance</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/olizardo/SOCIOL208/blob/main/basic-random.qmd" class="toc-action"><i class="bi bi-github"></i>View source</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./syllabus-208A.html">208A</a></li><li class="breadcrumb-item">Lecture Notes</li><li class="breadcrumb-item"><a href="./basic.html">Basic Concepts</a></li><li class="breadcrumb-item"><a href="./basic-random.html">Random Walk Concepts in Networks</a></li></ol></nav>
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">Random Walk Concepts in Networks</h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Code</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Show All Code</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Hide All Code</a></li><li><hr class="dropdown-divider"></li><li><a id="quarto-view-source" class="dropdown-item" href="javascript:void(0)" role="button">View Source</a></li></ul></div></div>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="the-average-first-passage-time" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="the-average-first-passage-time"><span class="header-section-number">1</span> The Average First Passage Time</h2>
<p>Imagine something is diffusing through a network starting with some seed node <span class="math inline">\(i\)</span> following a series of discrete time steps. If the graph is connected, the thing will eventually reach every node in the network. However, depending on the connectivity structure of the graph, it will reach some nodes (e.g., those at a smaller graph theoretic distance from the seed node) sooner than others.</p>
<p>Here’s a function called <code>first.pass1</code> that records the minimum number of steps that it takes for something to get to each node in a graph starting from a given seed node:</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1"></a>first.pass1 <span class="ot">&lt;-</span> <span class="cf">function</span>(w, <span class="at">seed =</span> <span class="dv">1</span>) {</span>
<span id="cb1-2"><a href="#cb1-2"></a>  fp <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="dv">0</span>, <span class="fu">ncol</span>(w))</span>
<span id="cb1-3"><a href="#cb1-3"></a>  k <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb1-4"><a href="#cb1-4"></a>  i <span class="ot">&lt;-</span> seed</span>
<span id="cb1-5"><a href="#cb1-5"></a>  <span class="cf">while</span> (<span class="fu">sum</span>(fp[<span class="sc">-</span>seed] <span class="sc">==</span> <span class="dv">0</span>) <span class="sc">!=</span> <span class="dv">0</span>) {</span>
<span id="cb1-6"><a href="#cb1-6"></a>    j <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">ncol</span>(w)), <span class="dv">1</span>, <span class="at">prob =</span> w[i, ])</span>
<span id="cb1-7"><a href="#cb1-7"></a>    <span class="cf">if</span> (fp[j] <span class="sc">==</span> <span class="dv">0</span> <span class="sc">&amp;</span> j <span class="sc">!=</span> seed) {</span>
<span id="cb1-8"><a href="#cb1-8"></a>      fp[j] <span class="ot">&lt;-</span> k</span>
<span id="cb1-9"><a href="#cb1-9"></a>    }</span>
<span id="cb1-10"><a href="#cb1-10"></a>    i <span class="ot">&lt;-</span> j</span>
<span id="cb1-11"><a href="#cb1-11"></a>    k <span class="ot">&lt;-</span> k <span class="sc">+</span> <span class="dv">1</span></span>
<span id="cb1-12"><a href="#cb1-12"></a>  }</span>
<span id="cb1-13"><a href="#cb1-13"></a>  <span class="fu">names</span>(fp) <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">ncol</span>(w)</span>
<span id="cb1-14"><a href="#cb1-14"></a>  <span class="fu">return</span>(fp)</span>
<span id="cb1-15"><a href="#cb1-15"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>The function takes a transition matrix <span class="math inline">\(\mathbf{P} = \mathbf{D}^{-1}\mathbf{A}\)</span>—where <span class="math inline">\(\mathbf{D}^{-1}\)</span> is a matrix containing the inverse of the degrees of each node along the diagonals and zeros everywhere else—as the primary input (of the sort we discussed when talking about <a href="./prest-eigen.html">status and prestige</a>) and returns a vector containing the time step at which the thing that diffused through the network got to the <span class="math inline">\(j^{th}\)</span> node. It works like this:</p>
<ul>
<li><p>Line 2 initializes the “first pass” vector <code>fp</code> to all zeros. Line 3 initializes the step counter <code>k</code> and line 4 initializes the scalar <code>i</code> to the whatever node was specified as the seed note in the <code>seed</code> argument of the function.</p></li>
<li><p>Lines 5-10 implement a little <code>while</code> loop that runs until there are no more zeros in the <code>fp</code> vector. Line 6 samples a random neighbor of node <code>i</code> with probability specified by the relevant entry in the transition matrix (<span class="math inline">\(p_{ij} = \frac{1}{d_i}\)</span>), and then turns that node <code>j</code> into the new sender node <code>i</code>, marking that as the time that the thing that is diffusing through the network got to <code>j</code> using marker <code>k</code>.</p></li>
<li><p>Line 11 names the <code>fp</code> vector using the column names of the transition matrix, and line 12 returns the vector.</p></li>
</ul>
<p>Let’s test the <code>first.pass1</code> function out using the <strong>undirected</strong> version of the friendship network from the Krackhardt high-tech managers data:</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1"></a><span class="fu">library</span>(networkdata)</span>
<span id="cb2-2"><a href="#cb2-2"></a><span class="fu">library</span>(igraph)</span>
<span id="cb2-3"><a href="#cb2-3"></a>g <span class="ot">&lt;-</span> <span class="fu">as_undirected</span>(ht_friends, <span class="at">mode =</span> <span class="st">"collapse"</span>) <span class="co"># undirected graph</span></span>
<span id="cb2-4"><a href="#cb2-4"></a>A <span class="ot">&lt;-</span> <span class="fu">as.matrix</span>(<span class="fu">as_adjacency_matrix</span>(g)) <span class="co"># adjacency matrix</span></span>
<span id="cb2-5"><a href="#cb2-5"></a>D <span class="ot">&lt;-</span> <span class="fu">diag</span>(<span class="fu">rowSums</span>(A)<span class="sc">^-</span><span class="dv">1</span>) <span class="co"># inverse of degree matrix</span></span>
<span id="cb2-6"><a href="#cb2-6"></a>P <span class="ot">&lt;-</span> D <span class="sc">%*%</span> A <span class="co"># transition matrix</span></span>
<span id="cb2-7"><a href="#cb2-7"></a><span class="fu">set.seed</span>(<span class="dv">456</span>)</span>
<span id="cb2-8"><a href="#cb2-8"></a><span class="fu">first.pass1</span>(P)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18  19  20 
  0   2 137  24  14  28  43  36   8   9  16  29  15  26   7   1  25  33   6  32 
 21 
 12 </code></pre>
</div>
</div>
<p>We can see for instance that the rumor got to node 16 in just one time step, but that it took 26 time steps to get to node 14 and 137 (!) to get to node 3.</p>
<p>So it seems like this, the minimum time it takes for something that starts with me to get to you <span class="citation" data-cites="fouss_etal04b">(<a href="#ref-fouss_etal04b" role="doc-biblioref">Fouss et al. 2004</a>)</span>, is a good measure of the proximity between me and you in the graph.</p>
<p>However, we wouldn’t want to use just one run of the diffusion process to calculate this proximity measure. Instead a better approach is to use the <em>average time</em> it takes for something to get to the other nodes when it starts from a given node, across a large number of realizations of the diffusion process.</p>
<p>To do that, we can just <code>replicate</code> the <code>first.pass1</code> function some number of times (e.g., <span class="math inline">\(n = 100\)</span>) and take an average:</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1"></a><span class="fu">set.seed</span>(<span class="dv">456</span>)</span>
<span id="cb4-2"><a href="#cb4-2"></a>first.res <span class="ot">&lt;-</span> <span class="fu">replicate</span>(<span class="dv">100</span>, <span class="fu">first.pass1</span>(P))</span>
<span id="cb4-3"><a href="#cb4-3"></a><span class="fu">round</span>(<span class="fu">rowMeans</span>(first.res), <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>    1     2     3     4     5     6     7     8     9    10    11    12    13 
 0.00 16.14 32.88 21.24 17.17 24.35 59.98 27.83 25.85 17.75 10.16 15.78 86.78 
   14    15    16    17    18    19    20    21 
36.32 15.43 32.94  8.65 44.59 19.17 31.47 33.85 </code></pre>
</div>
</div>
<p>We can see that according to this measure, called <strong>the average first passage time</strong> <span class="citation" data-cites="fouss_etal16">(<a href="#ref-fouss_etal16" role="doc-biblioref">Fouss et al. 2016, 36</a>)</span>, when we start with node 1, things get relatively quickly to node 17 (<span class="math inline">\(\hat{t} = 8.7\)</span>) but they take forever to get to node 13 (<span class="math inline">\(\hat{t} = 86.8\)</span>).</p>
<p>We can of course, write a wrapper around the <code>first.pass1</code> function to compute the average first passage time from one node to another using every node in the graph as the initial seed, and put all of the results in a matrix <span class="math inline">\(\mathbf{M}\)</span> where each entry <span class="math inline">\(m_{ij}\)</span> is the average first passage time between nodes <span class="math inline">\(i\)</span> and <span class="math inline">\(j\)</span>:</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1"></a>first.pass2 <span class="ot">&lt;-</span> <span class="cf">function</span>(w, n) {</span>
<span id="cb6-2"><a href="#cb6-2"></a>  m <span class="ot">&lt;-</span> <span class="fu">rowMeans</span>(<span class="fu">replicate</span>(n, <span class="fu">first.pass1</span>(w)))</span>
<span id="cb6-3"><a href="#cb6-3"></a>  <span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">2</span><span class="sc">:</span><span class="fu">nrow</span>(w)) {</span>
<span id="cb6-4"><a href="#cb6-4"></a>    m <span class="ot">&lt;-</span> <span class="fu">rbind</span>(m, <span class="fu">rowMeans</span>(<span class="fu">replicate</span>(n, <span class="fu">first.pass1</span>(w, <span class="at">seed =</span> i))))</span>
<span id="cb6-5"><a href="#cb6-5"></a>  }</span>
<span id="cb6-6"><a href="#cb6-6"></a>  <span class="fu">rownames</span>(m) <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(w)</span>
<span id="cb6-7"><a href="#cb6-7"></a>  <span class="fu">return</span>(m)</span>
<span id="cb6-8"><a href="#cb6-8"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>And the result (showing the first ten rows and columns of <span class="math inline">\(\mathbf{M}\)</span>) is:</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1"></a><span class="fu">set.seed</span>(<span class="dv">456</span>)</span>
<span id="cb7-2"><a href="#cb7-2"></a><span class="fu">round</span>(<span class="fu">first.pass2</span>(P, <span class="dv">100</span>), <span class="dv">1</span>)[<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>, <span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>      1    2    3    4    5    6    7    8    9   10
1   0.0 16.1 32.9 21.2 17.2 24.4 60.0 27.8 25.9 17.8
2  18.1  0.0 23.4 24.0 14.6 20.5 60.6 32.6 32.6 16.6
3  20.6 22.2  0.0 19.9 17.1 29.1 63.1 29.8 26.8 19.0
4  14.1 14.1 27.4  0.0 18.1 21.7 57.8 28.9 22.7 21.8
5  16.9 16.7 30.0 25.1  0.0 25.0 52.9 36.5 19.9 24.1
6  19.5 18.1 24.4 28.2 15.2  0.0 41.5 38.6 19.5 25.2
7  20.7 15.9 26.8 24.8 16.3 14.2  0.0 33.0 26.1 23.7
8  14.1 14.9 27.2 16.6 17.2 29.2 73.3  0.0 23.8 19.1
9  18.1 16.1 27.5 23.9 16.3 20.7 52.1 32.7  0.0 20.1
10 20.0 18.7 26.2 23.3 16.2 23.8 64.7 27.0 21.2  0.0</code></pre>
</div>
</div>
<p>Note that the <span class="math inline">\(\mathbf{M}\)</span> matrix is asymmetric. That is, the average number of steps that it takes for something to get from me to you (<span class="math inline">\(m_{ij}\)</span>), is not necessarily the same as the average number of steps that it takes for something to get from you to me (<span class="math inline">\(m_{ji}\)</span>).</p>
<p>The accuracy of the average first passage time estimate we get depends on the number of replications we use to get the average. The bigger, the more accurate. However, it can take a lot of computing time if we increased <code>n</code> to a giant number.</p>
<section id="computing-the-afpt-by-iterating-until-convergence" class="level3" data-number="1.1">
<h3 data-number="1.1" class="anchored" data-anchor-id="computing-the-afpt-by-iterating-until-convergence"><span class="header-section-number">1.1</span> Computing the AFPT by Iterating Until Convergence</h3>
<p>There’s a more efficient approach to computing the entries in the average first passage time matrix <span class="math inline">\(\mathbf{M}\)</span> that involves iterating through a matrix using the information in the transition matrix <span class="math inline">\(\mathbf{P}\)</span>. The basic idea is that the average first passage time for a random walker that starts at node <span class="math inline">\(i\)</span> and ends at node <span class="math inline">\(j\)</span> is given by:</p>
<p><span id="eq-first-pass-iter"><span class="math display">\[
m_{ij} = 1 + \sum^N_{j \neq k}p_{ik}m_{k,j}
\tag{1}\]</span></span></p>
<p>With the proviso that <span class="math inline">\(m_{ii}\)</span> is always equal to zero. What this tells us is that the average first passage time between any two nodes in the graph <span class="math inline">\(i\)</span> and <span class="math inline">\(j\)</span>, is given by one plus the product of the probability that something can transition from a sender node <span class="math inline">\(i\)</span> to an intermediary node <span class="math inline">\(k\)</span>—given by <span class="math inline">\(p_{ik}\)</span>—and <span class="math inline">\(m_{kj}\)</span> which is the average first passage time from that intermediary node <span class="math inline">\(k\)</span> to the destination node <span class="math inline">\(j\)</span>.</p>
<p>Note that since we need to know <span class="math inline">\(m_{kj}\)</span> to get <span class="math inline">\(m_{ij}\)</span>, then this opens up a chicken or the egg problem that we can solve through iteration like we did for the status scores in the <a href="./prest-eigen.html">prestige</a> lesson.</p>
<p>Here’s how to proceed. We first start with a null value for all the entries of the <span class="math inline">\(\mathbf{M}\)</span> matrix (e.g., <span class="math inline">\(m_{ij} = 0\)</span> for all <span class="math inline">\(i\)</span> and <span class="math inline">\(j\)</span>), compute an initial round of <span class="math inline">\(m_{ij}\)</span> estimates for all pairs of nodes <span class="math inline">\(i\)</span> and <span class="math inline">\(j\)</span> using <a href="#eq-first-pass-iter" class="quarto-xref">Equation&nbsp;1</a>, recompute <span class="math inline">\(m_{ij}\)</span> using those new values, rinse, repeat, and stop after we don’t get any big changes between successive versions of the <span class="math inline">\(\mathbf{M}\)</span> matrix.</p>
<p>A function that implement this idea goes like this:</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1"></a>first.pass3 <span class="ot">&lt;-</span> <span class="cf">function</span>(w) {</span>
<span id="cb9-2"><a href="#cb9-2"></a>  n <span class="ot">&lt;-</span> <span class="fu">nrow</span>(w)</span>
<span id="cb9-3"><a href="#cb9-3"></a>  nodes <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">:</span>n</span>
<span id="cb9-4"><a href="#cb9-4"></a>  m <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="dv">0</span>, n, n) <span class="co"># initializing M matrix values</span></span>
<span id="cb9-5"><a href="#cb9-5"></a>  d <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="co"># initialize delta</span></span>
<span id="cb9-6"><a href="#cb9-6"></a>  <span class="cf">while</span> (d <span class="sc">&gt;</span> <span class="fl">1e-06</span>) { <span class="co"># do while delta is bigger than a tiny number</span></span>
<span id="cb9-7"><a href="#cb9-7"></a>    old.m <span class="ot">&lt;-</span> m</span>
<span id="cb9-8"><a href="#cb9-8"></a>    <span class="cf">for</span> (i <span class="cf">in</span> nodes) { <span class="co"># loop through every node</span></span>
<span id="cb9-9"><a href="#cb9-9"></a>      <span class="cf">for</span> (j <span class="cf">in</span> nodes[<span class="sc">-</span>i]) { <span class="co"># loop through every node except i</span></span>
<span id="cb9-10"><a href="#cb9-10"></a>        m[i, j] <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb9-11"><a href="#cb9-11"></a>        <span class="cf">for</span> (k <span class="cf">in</span> nodes[<span class="sc">-</span><span class="fu">c</span>(i, j)]) { <span class="co"># loop through every node except i and j</span></span>
<span id="cb9-12"><a href="#cb9-12"></a>          m[i, j] <span class="ot">&lt;-</span> m[i, j] <span class="sc">+</span> (w[i, k] <span class="sc">*</span> old.m[k, j]) <span class="co"># update M matrix values</span></span>
<span id="cb9-13"><a href="#cb9-13"></a>        }</span>
<span id="cb9-14"><a href="#cb9-14"></a>      }</span>
<span id="cb9-15"><a href="#cb9-15"></a>    }</span>
<span id="cb9-16"><a href="#cb9-16"></a>    d <span class="ot">&lt;-</span> <span class="fu">abs</span>(<span class="fu">sum</span>(<span class="fu">abs</span>(m) <span class="sc">-</span> <span class="fu">abs</span>(old.m))) <span class="co"># delta equals difference between current and previous M matrix</span></span>
<span id="cb9-17"><a href="#cb9-17"></a>  } <span class="co"># end while loop</span></span>
<span id="cb9-18"><a href="#cb9-18"></a>  <span class="fu">return</span>(m)</span>
<span id="cb9-19"><a href="#cb9-19"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>This function takes the probability transition matrix <span class="math inline">\(\mathbf{P}\)</span> as input and returns the <span class="math inline">\(\mathbf{M}\)</span> matrix of average first passage times between every pair of nodes in the network.</p>
<p>And the result is:</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1"></a><span class="fu">round</span>(<span class="fu">first.pass3</span>(P), <span class="dv">1</span>)[<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>, <span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>      [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
 [1,]  0.0 15.0 28.5 21.1 17.7 25.4 59.7 29.9 28.5  21.2
 [2,] 17.0  0.0 29.0 22.3 16.1 23.2 59.0 33.8 28.2  21.8
 [3,] 19.1 17.7  0.0 25.7 16.6 25.4 57.6 34.1 27.4  18.6
 [4,] 15.1 14.4 29.1  0.0 18.0 25.6 59.9 28.6 28.7  20.9
 [5,] 19.4 15.8 27.6 25.7  0.0 24.8 58.4 34.5 25.1  19.9
 [6,] 19.3 15.0 28.6 25.3 16.9  0.0 50.5 35.0 24.2  21.8
 [7,] 19.9 17.3 27.1 26.1 17.0 16.9  0.0 35.2 27.1  22.2
 [8,] 14.9 16.8 28.3 19.5 17.8 26.1 59.9  0.0 28.0  17.7
 [9,] 19.4 17.2 27.7 25.6 14.4 21.3 57.8 34.1  0.0  18.4
[10,] 18.7 17.3 25.4 24.3 15.7 25.4 59.4 30.2 24.9   0.0</code></pre>
</div>
</div>
<p>Which are the exact (up to rounding error) average first passage times between each pair of nodes in the network.</p>
</section>
</section>
<section id="computing-the-afpt-using-the-laplacian-matrix" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="computing-the-afpt-using-the-laplacian-matrix"><span class="header-section-number">2</span> Computing the AFPT Using the Laplacian Matrix</h2>
<p>Finally, there is a way to use matrix algebra magic to compute the average first passage time at the limit (<span class="math inline">\(n \approx \infty\)</span>) in closed form without averaging or iterations.</p>
<p>To do that, first we need to compute a matrix called the <strong>graph Laplacian</strong>, which is defined as:</p>
<p><span id="eq-lap"><span class="math display">\[
\mathbf{L} = \mathbf{D} - \mathbf{A}
\tag{2}\]</span></span></p>
<p>Where <span class="math inline">\(\mathbf{D}\)</span> is a diagonal matrix containing the degrees of each node in the graph along the diagonals and zeroes everywhere else.</p>
<p>In <code>R</code> we can compute <span class="math inline">\(\mathbf{L}\)</span> like this:</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1"></a>D <span class="ot">&lt;-</span> <span class="fu">diag</span>(<span class="fu">rowSums</span>(A))</span>
<span id="cb12-2"><a href="#cb12-2"></a>L <span class="ot">&lt;-</span> D <span class="sc">-</span> A</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>Once we have <span class="math inline">\(\mathbf{L}\)</span>, we need to compute a variation known by the less than memorable name of the <strong>Moore-Penrose Pseudo-Inverse of the Laplacian</strong>, written as <span class="math inline">\(\mathbf{L}^+\)</span>, which is given by:</p>
<p><span id="eq-ilap"><span class="math display">\[
\mathbf{L}^+ = \left(\mathbf{L} - \frac{\mathbf{E}}{N}\right) ^{-1}- \frac{\mathbf{E}}{N}
\tag{3}\]</span></span></p>
<p>Where <span class="math inline">\(\mathbf{E}\)</span> is the all ones matrix of the same dimensions as <span class="math inline">\(\mathbf{L}\)</span>.</p>
<p>So despite the terrible name, <span class="math inline">\(\mathbf{L}^+\)</span> is easy to compute in <code>R</code>:</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1"></a>E <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="dv">1</span>, <span class="fu">nrow</span>(A), <span class="fu">nrow</span>(A)) <span class="sc">/</span> <span class="fu">nrow</span>(A)</span>
<span id="cb13-2"><a href="#cb13-2"></a>L.p <span class="ot">&lt;-</span> <span class="fu">solve</span>(L <span class="sc">+</span> E) <span class="sc">-</span> E</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>As we can see, <code>E</code> is just a matrix containing the inverse of the number of nodes in the network in every cell (<span class="math inline">\(\frac{1}{N}\)</span>). We use the function <code>solve</code> to obtain the <strong>matrix inverse</strong> of the expression in parentheses in .</p>
<p>What’s in the <span class="math inline">\(\mathbf{L}^+\)</span> matrix? Let’s see the first ten rows and columns:</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1"></a><span class="fu">round</span>(L.p[<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>, <span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>], <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>        [,1]   [,2]   [,3]   [,4]   [,5]   [,6]   [,7]   [,8]   [,9]  [,10]
 [1,]  0.112  0.004 -0.011  0.015 -0.012 -0.013 -0.025  0.015 -0.013 -0.008
 [2,]  0.004  0.099 -0.015  0.007 -0.002  0.001 -0.021 -0.010 -0.012 -0.012
 [3,] -0.011 -0.015  0.167 -0.017 -0.007 -0.015 -0.014 -0.014 -0.009  0.006
 [4,]  0.015  0.007 -0.017  0.147 -0.015 -0.015 -0.028  0.022 -0.016 -0.007
 [5,] -0.012 -0.002 -0.007 -0.015  0.099 -0.010 -0.019 -0.016  0.007 -0.001
 [6,] -0.013  0.001 -0.015 -0.015 -0.010  0.145  0.030 -0.020  0.011 -0.014
 [7,] -0.025 -0.021 -0.014 -0.028 -0.019  0.030  0.341 -0.030 -0.016 -0.025
 [8,]  0.015 -0.010 -0.014  0.022 -0.016 -0.020 -0.030  0.200 -0.014  0.011
 [9,] -0.013 -0.012 -0.009 -0.016  0.007  0.011 -0.016 -0.014  0.164  0.007
[10,] -0.008 -0.012  0.006 -0.007 -0.001 -0.014 -0.025  0.011  0.007  0.125</code></pre>
</div>
</div>
<p>As we can see, some of the entries of <span class="math inline">\(\mathbf{L}^+\)</span> are positive and others are negative. More interestingly, we can see that <span class="math inline">\(\mathbf{L}^+\)</span> is a <strong>symmetric</strong> matrix: <span class="math inline">\(l^+_{ij} = l^+_{ij}\)</span>.</p>
<p>Even more interestingly, <span class="math inline">\(\mathbf{L}^+\)</span> is <strong>doubly centered</strong>—similar to the <strong>modularity matrix</strong> <a href="./comm-mod.html">considered here</a>. That means <em>both</em> the rows and column sums of the matrix are equal to the all zeros vector:</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1"></a><span class="fu">round</span>(<span class="fu">rowSums</span>(L.p), <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0</code></pre>
</div>
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1"></a><span class="fu">round</span>(<span class="fu">colSums</span>(L.p), <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0</code></pre>
</div>
</div>
<p>The average first passage time between every pair of nodes in the network <span class="math inline">\(m_{ij}\)</span> expressed in terms of the entries of <span class="math inline">\(\mathbf{L}^+\)</span> and the degree vector <span class="math inline">\(\mathbf{d}\)</span>, is then given by <span class="citation" data-cites="fouss_etal16">(<a href="#ref-fouss_etal16" role="doc-biblioref">Fouss et al. 2016, 158</a>)</span>:</p>
<p><span id="eq-firstpass"><span class="math display">\[
m_{ij} = \sum_{k=1}^n \left(l^+_{jj} - l^+_{ij} + l^+_{ik} - l^+_{kj}\right)d_k
\tag{4}\]</span></span></p>
<p>Where <span class="math inline">\(d_k\)</span> is the degree of node <span class="math inline">\(k\)</span>.</p>
<p>So let’s try it out:</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1"></a>nodes <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(A) <span class="co"># node id vector</span></span>
<span id="cb20-2"><a href="#cb20-2"></a>d <span class="ot">&lt;-</span> <span class="fu">rowSums</span>(A) <span class="co"># degree vector</span></span>
<span id="cb20-3"><a href="#cb20-3"></a>m <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="dv">0</span>, <span class="fu">nrow</span>(A), <span class="fu">nrow</span>(A)) <span class="co"># initializing M to all zeros</span></span>
<span id="cb20-4"><a href="#cb20-4"></a><span class="cf">for</span> (i <span class="cf">in</span> nodes) {</span>
<span id="cb20-5"><a href="#cb20-5"></a>  <span class="cf">for</span> (j <span class="cf">in</span> nodes) {</span>
<span id="cb20-6"><a href="#cb20-6"></a>    <span class="cf">for</span> (k <span class="cf">in</span> nodes) {</span>
<span id="cb20-7"><a href="#cb20-7"></a>      m[i, j] <span class="ot">&lt;-</span> m[i, j] <span class="sc">+</span> ((L.p[j, j] <span class="sc">-</span> L.p[i, j] <span class="sc">+</span> L.p[i, k] <span class="sc">-</span> L.p[k, j]) <span class="sc">*</span> d[k])</span>
<span id="cb20-8"><a href="#cb20-8"></a>    }</span>
<span id="cb20-9"><a href="#cb20-9"></a>  }</span>
<span id="cb20-10"><a href="#cb20-10"></a>}</span>
<span id="cb20-11"><a href="#cb20-11"></a><span class="fu">round</span>(m[<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>, <span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>], <span class="dv">1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>      [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
 [1,]  0.0 15.0 28.5 21.1 17.7 25.4 59.7 29.9 28.5  21.2
 [2,] 17.0  0.0 29.0 22.3 16.1 23.2 59.0 33.8 28.2  21.8
 [3,] 19.1 17.7  0.0 25.7 16.6 25.4 57.6 34.1 27.4  18.6
 [4,] 15.1 14.4 29.1  0.0 18.0 25.6 59.9 28.6 28.7  20.9
 [5,] 19.4 15.8 27.6 25.7  0.0 24.8 58.4 34.5 25.1  19.9
 [6,] 19.3 15.0 28.6 25.3 16.9  0.0 50.5 35.0 24.2  21.8
 [7,] 19.9 17.3 27.1 26.1 17.0 16.9  0.0 35.2 27.1  22.2
 [8,] 14.9 16.8 28.3 19.5 17.8 26.1 59.9  0.0 28.0  17.7
 [9,] 19.4 17.2 27.7 25.6 14.4 21.3 57.8 34.1  0.0  18.4
[10,] 18.7 17.3 25.4 24.3 15.7 25.4 59.4 30.2 24.9   0.0</code></pre>
</div>
</div>
<p>Which produces exactly the same results we obtained earlier via iteration.</p>
</section>
<section id="computing-the-afpt-using-a-big-matrix-formula" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="computing-the-afpt-using-a-big-matrix-formula"><span class="header-section-number">3</span> Computing the AFPT Using a Big Matrix Formula</h2>
<p>There is an even more straightforward way to compute the average first passage time that does not involve looping at all, but simple matrix operations. We can do that because we can express in matrix form like this:</p>
<p><span class="math display">\[
\mathbf{M} = \left[vol(A)\mathbf{e}(\mathbf{l}^+_{d})^T - vol(A)\mathbf{L}^+\right] + \left[(\mathbf{L}^+\mathbf{d})\mathbf{e}^T -\mathbf{e}(\mathbf{d}^T\mathbf{L}^+)\right]
\]</span></p>
<p>Now, this formula looks long and monstrous but it is composed of simple quantities we know and love. We have already been introduced to <span class="math inline">\(\mathbf{L}^+\)</span>, while <span class="math inline">\(\mathbf{e}\)</span> is a column vector of ones with as many rows as the number of nodes in the graph, <span class="math inline">\(\mathbf{d}\)</span> is a vector of the same length as the number of nodes in the graph containing the degrees of each node at each position, <span class="math inline">\(vol(A) = \sum_{i} d_{i}\)</span> is just the sum of the non-zero entries in the adjacency matrix, and <span class="math inline">\(\mathbf{l}^+_{d}\)</span> is a vector containing the diagonal entries of <span class="math inline">\(\mathbf{L}^+\)</span> at each position.</p>
<p>The following <code>R</code> code constructs <span class="math inline">\(\mathbf{M}\)</span> step by step:</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1"></a>e <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="dv">1</span>, <span class="fu">nrow</span>(A), <span class="dv">1</span>) <span class="co"># column vector of all ones</span></span>
<span id="cb22-2"><a href="#cb22-2"></a>d <span class="ot">&lt;-</span> <span class="fu">rowSums</span>(A) <span class="co"># degree vector</span></span>
<span id="cb22-3"><a href="#cb22-3"></a>l <span class="ot">&lt;-</span> <span class="fu">diag</span>(L.p) <span class="co"># diagonal vector of Laplacian inverse</span></span>
<span id="cb22-4"><a href="#cb22-4"></a>vol.A <span class="ot">&lt;-</span> <span class="fu">sum</span>(d) <span class="co"># graph volume</span></span>
<span id="cb22-5"><a href="#cb22-5"></a>M <span class="ot">&lt;-</span> vol.A <span class="sc">*</span> (e <span class="sc">%*%</span> <span class="fu">t</span>(l))</span>
<span id="cb22-6"><a href="#cb22-6"></a>M <span class="ot">&lt;-</span> M <span class="sc">-</span> (vol.A <span class="sc">*</span> L.p)</span>
<span id="cb22-7"><a href="#cb22-7"></a>M <span class="ot">&lt;-</span> M <span class="sc">+</span> (L.p <span class="sc">%*%</span> d) <span class="sc">%*%</span> <span class="fu">t</span>(e)</span>
<span id="cb22-8"><a href="#cb22-8"></a>M <span class="ot">&lt;-</span> M <span class="sc">-</span> (e <span class="sc">%*%</span> (<span class="fu">t</span>(d) <span class="sc">%*%</span> L.p))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>And now for the big reveal:</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1"></a><span class="fu">round</span>(M, <span class="dv">1</span>)[<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>, <span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>      [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
 [1,]  0.0 15.0 28.5 21.1 17.7 25.4 59.7 29.9 28.5  21.2
 [2,] 17.0  0.0 29.0 22.3 16.1 23.2 59.0 33.8 28.2  21.8
 [3,] 19.1 17.7  0.0 25.7 16.6 25.4 57.6 34.1 27.4  18.6
 [4,] 15.1 14.4 29.1  0.0 18.0 25.6 59.9 28.6 28.7  20.9
 [5,] 19.4 15.8 27.6 25.7  0.0 24.8 58.4 34.5 25.1  19.9
 [6,] 19.3 15.0 28.6 25.3 16.9  0.0 50.5 35.0 24.2  21.8
 [7,] 19.9 17.3 27.1 26.1 17.0 16.9  0.0 35.2 27.1  22.2
 [8,] 14.9 16.8 28.3 19.5 17.8 26.1 59.9  0.0 28.0  17.7
 [9,] 19.4 17.2 27.7 25.6 14.4 21.3 57.8 34.1  0.0  18.4
[10,] 18.7 17.3 25.4 24.3 15.7 25.4 59.4 30.2 24.9   0.0</code></pre>
</div>
</div>
<p>Which once again, gives us the results we seek.</p>
<p>As we saw earlier, the interpretation of the entries of the <span class="math inline">\(\mathbf{M}\)</span> matrix is also straightforward. For instance, if we start a message from node 2, we should expect it to take an average of <span class="math inline">\(m_{2, 6} =\)</span> 23.2 steps to get to node 6 by following random walks in the network.</p>
</section>
<section id="the-average-commute-distance" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="the-average-commute-distance"><span class="header-section-number">4</span> The Average Commute Distance</h2>
<p>Once we have the average first passage time, we can compute another important quantity called the <strong>average commute distance</strong> between two nodes <span class="math inline">\(i\)</span> and <span class="math inline">\(j\)</span> (<span class="math inline">\(n_{ij}\)</span>). This is the number of steps it takes for a random walker to start at node <span class="math inline">\(i\)</span>, reach another specific node <span class="math inline">\(j\)</span> and then <em>get back</em> to the original node <span class="math inline">\(i\)</span> (hence commuting, like going from home to work and then back from work to home again).</p>
<p>It turns out that <span class="math inline">\(n_{ij}\)</span> is pretty simple to compute, once we know the average first passage time between every pair of nodes <span class="math inline">\(m_{ij}\)</span>, since it is given by:</p>
<p><span class="math display">\[
n_{ij} = m_{ij} + m_{ji}
\]</span></p>
<p>So the entries of the Average Commute Distance matrix <span class="math inline">\(\mathbf{N}\)</span> are just the entries of <span class="math inline">\(\mathbf{M}\)</span> on the upper triangle added to the corresponding entries in the lower triangle. In <code>R</code> we can obtain that by just adding <span class="math inline">\(\mathbf{M}\)</span> to its transpose <span class="math inline">\(\mathbf{M}^T\)</span>:</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1"></a>N <span class="ot">&lt;-</span> M <span class="sc">+</span> <span class="fu">t</span>(M)</span>
<span id="cb25-2"><a href="#cb25-2"></a><span class="fu">round</span>(N[<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>, <span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>], <span class="dv">1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>      [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
 [1,]  0.0 32.0 47.6 36.2 37.1 44.7 79.6 44.8 47.9  39.9
 [2,] 32.0  0.0 46.7 36.7 31.9 38.2 76.3 50.6 45.5  39.0
 [3,] 47.6 46.7  0.0 54.8 44.2 54.0 84.7 62.4 55.0  44.0
 [4,] 36.2 36.7 54.8  0.0 43.7 50.9 86.0 48.1 54.4  45.2
 [5,] 37.1 31.9 44.2 43.7  0.0 41.8 75.4 52.3 39.5  35.6
 [6,] 44.7 38.2 54.0 50.9 41.8  0.0 67.4 61.1 45.5  47.2
 [7,] 79.6 76.3 84.7 86.0 75.4 67.4  0.0 95.1 84.9  81.6
 [8,] 44.8 50.6 62.4 48.1 52.3 61.1 95.1  0.0 62.1  47.9
 [9,] 47.9 45.5 55.0 54.4 39.5 45.5 84.9 62.1  0.0  43.3
[10,] 39.9 39.0 44.0 45.2 35.6 47.2 81.6 47.9 43.3   0.0</code></pre>
</div>
</div>
<p>Note that the average commute distance matrix entries are symmetric, which makes sense, for it takes as long for something to go from to you to me and back to you as from me to you and back to me. The average commute distance between pairs of nodes thus functions as a <strong>similarity metric</strong>; the lower the average commute distance, the closer or more similar two nodes are in the network.</p>
<p>Of course, we can also use math to compute <span class="math inline">\(\mathbf{N}\)</span> directly from the entries of <span class="math inline">\(\mathbf{L}^+\)</span> using a recombination of the same ingredients we used before to compute the average first passage time. It goes like this:</p>
<p><span class="math display">\[
n_{ij} = vol(A) \left(l^+_{ii} + l^+_{jj} + 2l^+_{ij}\right)
\]</span></p>
<p>Which in (more complicated) matrix form looks like:</p>
<p><span class="math display">\[
\mathbf{N} = vol(A)\left[\mathbf{l}^+_{d}\mathbf{e}^T + \mathbf{e}\mathbf{l}^+_{d} - 2\mathbf{L}^+\right]
\]</span></p>
<p>But which is actually a much less monstrous and simpler expression than before.</p>
<p>The following <code>R</code> code constructs the <span class="math inline">\(\mathbf{N}\)</span> matrix of average commute distances between each pair of nodes in the network step by step:</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1"></a>N <span class="ot">&lt;-</span> l <span class="sc">%*%</span> <span class="fu">t</span>(e)</span>
<span id="cb27-2"><a href="#cb27-2"></a>N <span class="ot">&lt;-</span> N <span class="sc">+</span> (e <span class="sc">%*%</span> l)</span>
<span id="cb27-3"><a href="#cb27-3"></a>N <span class="ot">&lt;-</span> N <span class="sc">-</span> (<span class="dv">2</span> <span class="sc">*</span> L.p)</span>
<span id="cb27-4"><a href="#cb27-4"></a>N <span class="ot">&lt;-</span> vol.A <span class="sc">*</span> N</span>
<span id="cb27-5"><a href="#cb27-5"></a><span class="fu">round</span>(N, <span class="dv">1</span>)[<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>, <span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>      [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
 [1,]  0.0 32.0 47.6 36.2 37.1 44.7 79.6 44.8 47.9  39.9
 [2,] 32.0  0.0 46.7 36.7 31.9 38.2 76.3 50.6 45.5  39.0
 [3,] 47.6 46.7  0.0 54.8 44.2 54.0 84.7 62.4 55.0  44.0
 [4,] 36.2 36.7 54.8  0.0 43.7 50.9 86.0 48.1 54.4  45.2
 [5,] 37.1 31.9 44.2 43.7  0.0 41.8 75.4 52.3 39.5  35.6
 [6,] 44.7 38.2 54.0 50.9 41.8  0.0 67.4 61.1 45.5  47.2
 [7,] 79.6 76.3 84.7 86.0 75.4 67.4  0.0 95.1 84.9  81.6
 [8,] 44.8 50.6 62.4 48.1 52.3 61.1 95.1  0.0 62.1  47.9
 [9,] 47.9 45.5 55.0 54.4 39.5 45.5 84.9 62.1  0.0  43.3
[10,] 39.9 39.0 44.0 45.2 35.6 47.2 81.6 47.9 43.3   0.0</code></pre>
</div>
</div>
<p>Which as you can see, gives us the results we seek.</p>
<p>The interpretation of the entries of the <span class="math inline">\(\mathbf{N}\)</span> matrix is also straightforward. For instance, if a message starts at node 4, it would take an average of 54.4 steps for it to get to node 9 and then back to the original node 4 by following a random walk in the network governed by the node-to-node probabilities stored in the transition matrix <span class="math inline">\(\mathbf{P}\)</span>.</p>
<p>Interestingly, we can obtain the average commute time distance between any pair nodes yet another way. For instance from the above matrix, we know the average commute time distances between nodes 3 and 8 is 62.38.</p>
<p>Let’s construct two vectors full of zeros of the same length as the number of nodes in the graph, except they have a one in the third and eighth spot respectively:</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1"></a>n <span class="ot">&lt;-</span> <span class="fu">ncol</span>(A)</span>
<span id="cb29-2"><a href="#cb29-2"></a>i <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="dv">0</span>, n)</span>
<span id="cb29-3"><a href="#cb29-3"></a>j <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="dv">0</span>, n)</span>
<span id="cb29-4"><a href="#cb29-4"></a>i[<span class="dv">3</span>] <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb29-5"><a href="#cb29-5"></a>j[<span class="dv">8</span>] <span class="ot">&lt;-</span> <span class="dv">1</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p><span class="citation" data-cites="fouss_etal04b">Fouss et al. (<a href="#ref-fouss_etal04b" role="doc-biblioref">2004</a>)</span> show that the average commute time distance between nodes 3 and 8 is also given by:</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1"></a><span class="fu">round</span>(<span class="fu">sum</span>(A) <span class="sc">*</span> (<span class="fu">t</span>((i <span class="sc">-</span> j)) <span class="sc">%*%</span> L.p <span class="sc">%*%</span> (i <span class="sc">-</span> j)), <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>      [,1]
[1,] 62.38</code></pre>
</div>
</div>
<p>Neat!</p>


<!-- -->


</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-fouss_etal04b" class="csl-entry" role="listitem">
Fouss, François, Alain Pirotte, and Marco Saerens. 2004. <span>“The Application of New Concepts of Dissimilarities Between Nodes of a Graph to Collaborative Filtering.”</span> <em>Proc. Workshop on Statistical Approaches for Web Mining</em>, 26–37.
</div>
<div id="ref-fouss_etal16" class="csl-entry" role="listitem">
Fouss, François, Marco Saerens, and Masashi Shimbo. 2016. <em>Algorithms and Models for Network Data and Link Analysis</em>. Cambridge University Press.
</div>
</div></section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb32" data-shortcodes="false"><pre class="sourceCode numberSource markdown number-lines code-with-copy"><code class="sourceCode markdown"><span id="cb32-1"><a href="#cb32-1"></a><span class="co">---</span></span>
<span id="cb32-2"><a href="#cb32-2"></a><span class="an">title:</span><span class="co"> "Random Walk Concepts in Networks"</span></span>
<span id="cb32-3"><a href="#cb32-3"></a><span class="co">---</span></span>
<span id="cb32-4"><a href="#cb32-4"></a></span>
<span id="cb32-5"><a href="#cb32-5"></a><span class="fu">## The Average First Passage Time</span></span>
<span id="cb32-6"><a href="#cb32-6"></a></span>
<span id="cb32-7"><a href="#cb32-7"></a>Imagine something is diffusing through a network starting with some seed node $i$ following a series of discrete time steps. If the graph is connected, the thing will eventually reach every node in the network. However, depending on the connectivity structure of the graph, it will reach some nodes (e.g., those at a smaller graph theoretic distance from the seed node) sooner than others. </span>
<span id="cb32-8"><a href="#cb32-8"></a></span>
<span id="cb32-9"><a href="#cb32-9"></a>Here's a function called <span class="in">`first.pass1`</span> that records the minimum number of steps that it takes for something to get to each node in a graph starting from a given seed node:</span>
<span id="cb32-10"><a href="#cb32-10"></a></span>
<span id="cb32-13"><a href="#cb32-13"></a><span class="in">```{r}</span></span>
<span id="cb32-14"><a href="#cb32-14"></a>first.pass1 <span class="ot">&lt;-</span> <span class="cf">function</span>(w, <span class="at">seed =</span> <span class="dv">1</span>) {</span>
<span id="cb32-15"><a href="#cb32-15"></a>  fp <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="dv">0</span>, <span class="fu">ncol</span>(w))</span>
<span id="cb32-16"><a href="#cb32-16"></a>  k <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb32-17"><a href="#cb32-17"></a>  i <span class="ot">&lt;-</span> seed</span>
<span id="cb32-18"><a href="#cb32-18"></a>  <span class="cf">while</span> (<span class="fu">sum</span>(fp[<span class="sc">-</span>seed] <span class="sc">==</span> <span class="dv">0</span>) <span class="sc">!=</span> <span class="dv">0</span>) {</span>
<span id="cb32-19"><a href="#cb32-19"></a>    j <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">ncol</span>(w)), <span class="dv">1</span>, <span class="at">prob =</span> w[i, ])</span>
<span id="cb32-20"><a href="#cb32-20"></a>    <span class="cf">if</span> (fp[j] <span class="sc">==</span> <span class="dv">0</span> <span class="sc">&amp;</span> j <span class="sc">!=</span> seed) {</span>
<span id="cb32-21"><a href="#cb32-21"></a>      fp[j] <span class="ot">&lt;-</span> k</span>
<span id="cb32-22"><a href="#cb32-22"></a>    }</span>
<span id="cb32-23"><a href="#cb32-23"></a>    i <span class="ot">&lt;-</span> j</span>
<span id="cb32-24"><a href="#cb32-24"></a>    k <span class="ot">&lt;-</span> k <span class="sc">+</span> <span class="dv">1</span></span>
<span id="cb32-25"><a href="#cb32-25"></a>  }</span>
<span id="cb32-26"><a href="#cb32-26"></a>  <span class="fu">names</span>(fp) <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">ncol</span>(w)</span>
<span id="cb32-27"><a href="#cb32-27"></a>  <span class="fu">return</span>(fp)</span>
<span id="cb32-28"><a href="#cb32-28"></a>}</span>
<span id="cb32-29"><a href="#cb32-29"></a><span class="in">```</span></span>
<span id="cb32-30"><a href="#cb32-30"></a></span>
<span id="cb32-31"><a href="#cb32-31"></a>The function takes a transition matrix $\mathbf{P} = \mathbf{D}^{-1}\mathbf{A}$---where $\mathbf{D}^{-1}$ is a matrix containing the inverse of the degrees of each node along the diagonals and zeros everywhere else---as the primary input (of the sort we discussed when talking about <span class="co">[</span><span class="ot">status and prestige</span><span class="co">](prest-eigen.qmd)</span>) and returns a vector containing the time step at which the thing that diffused through the network got to the $j^{th}$ node. It works like this:</span>
<span id="cb32-32"><a href="#cb32-32"></a></span>
<span id="cb32-33"><a href="#cb32-33"></a><span class="ss">- </span>Line 2 initializes the "first pass" vector <span class="in">`fp`</span> to all zeros. Line 3 initializes the step counter <span class="in">`k`</span> and line 4 initializes the scalar <span class="in">`i`</span> to the whatever node was specified as the seed note in the <span class="in">`seed`</span> argument of the function.</span>
<span id="cb32-34"><a href="#cb32-34"></a></span>
<span id="cb32-35"><a href="#cb32-35"></a><span class="ss">- </span>Lines 5-10 implement a little <span class="in">`while`</span> loop that runs until there are no more zeros in the <span class="in">`fp`</span> vector. Line 6 samples a random neighbor of node <span class="in">`i`</span> with probability specified by the relevant entry in the transition matrix ($p_{ij} = \frac{1}{d_i}$), and then turns that node <span class="in">`j`</span> into the new sender node <span class="in">`i`</span>, marking that as the time that the thing that is diffusing through the network got to <span class="in">`j`</span> using marker <span class="in">`k`</span>.</span>
<span id="cb32-36"><a href="#cb32-36"></a></span>
<span id="cb32-37"><a href="#cb32-37"></a><span class="ss">- </span>Line 11 names the <span class="in">`fp`</span> vector using the column names of the transition matrix, and line 12 returns the vector.</span>
<span id="cb32-38"><a href="#cb32-38"></a></span>
<span id="cb32-39"><a href="#cb32-39"></a>Let's test the <span class="in">`first.pass1`</span> function out using the **undirected** version of the friendship network from the Krackhardt high-tech managers data:</span>
<span id="cb32-40"><a href="#cb32-40"></a></span>
<span id="cb32-43"><a href="#cb32-43"></a><span class="in">```{r}</span></span>
<span id="cb32-44"><a href="#cb32-44"></a><span class="fu">library</span>(networkdata)</span>
<span id="cb32-45"><a href="#cb32-45"></a><span class="fu">library</span>(igraph)</span>
<span id="cb32-46"><a href="#cb32-46"></a>g <span class="ot">&lt;-</span> <span class="fu">as_undirected</span>(ht_friends, <span class="at">mode =</span> <span class="st">"collapse"</span>) <span class="co"># undirected graph</span></span>
<span id="cb32-47"><a href="#cb32-47"></a>A <span class="ot">&lt;-</span> <span class="fu">as.matrix</span>(<span class="fu">as_adjacency_matrix</span>(g)) <span class="co"># adjacency matrix</span></span>
<span id="cb32-48"><a href="#cb32-48"></a>D <span class="ot">&lt;-</span> <span class="fu">diag</span>(<span class="fu">rowSums</span>(A)<span class="sc">^-</span><span class="dv">1</span>) <span class="co"># inverse of degree matrix</span></span>
<span id="cb32-49"><a href="#cb32-49"></a>P <span class="ot">&lt;-</span> D <span class="sc">%*%</span> A <span class="co"># transition matrix</span></span>
<span id="cb32-50"><a href="#cb32-50"></a><span class="fu">set.seed</span>(<span class="dv">456</span>)</span>
<span id="cb32-51"><a href="#cb32-51"></a><span class="fu">first.pass1</span>(P)</span>
<span id="cb32-52"><a href="#cb32-52"></a><span class="in">```</span></span>
<span id="cb32-53"><a href="#cb32-53"></a></span>
<span id="cb32-54"><a href="#cb32-54"></a>We can see for instance that the rumor got to node 16 in just one time step, but that it took 26 time steps to get to node 14 and 137 (!) to get to node 3.</span>
<span id="cb32-55"><a href="#cb32-55"></a></span>
<span id="cb32-56"><a href="#cb32-56"></a>So it seems like this, the minimum time it takes for something that starts with me to get to you <span class="co">[</span><span class="ot">@fouss_etal04b</span><span class="co">]</span>, is a good measure of the proximity between me and you in the graph. </span>
<span id="cb32-57"><a href="#cb32-57"></a></span>
<span id="cb32-58"><a href="#cb32-58"></a>However, we wouldn't want to use just one run of the diffusion process to calculate this proximity measure. Instead a better approach is to use the *average time* it takes for something to get to the other nodes when it starts from a given node, across a large number of realizations of the diffusion process. </span>
<span id="cb32-59"><a href="#cb32-59"></a></span>
<span id="cb32-60"><a href="#cb32-60"></a>To do that, we can just <span class="in">`replicate`</span> the <span class="in">`first.pass1`</span> function some number of times (e.g., $n = 100$) and take an average:</span>
<span id="cb32-61"><a href="#cb32-61"></a></span>
<span id="cb32-64"><a href="#cb32-64"></a><span class="in">```{r}</span></span>
<span id="cb32-65"><a href="#cb32-65"></a><span class="fu">set.seed</span>(<span class="dv">456</span>)</span>
<span id="cb32-66"><a href="#cb32-66"></a>first.res <span class="ot">&lt;-</span> <span class="fu">replicate</span>(<span class="dv">100</span>, <span class="fu">first.pass1</span>(P))</span>
<span id="cb32-67"><a href="#cb32-67"></a><span class="fu">round</span>(<span class="fu">rowMeans</span>(first.res), <span class="dv">2</span>)</span>
<span id="cb32-68"><a href="#cb32-68"></a><span class="in">```</span></span>
<span id="cb32-69"><a href="#cb32-69"></a></span>
<span id="cb32-70"><a href="#cb32-70"></a>We can see that according to this measure, called **the average first passage time** <span class="co">[</span><span class="ot">@fouss_etal16, p. 36</span><span class="co">]</span>, when we start with node 1, things get relatively quickly to node 17 ($\hat{t} = 8.7$) but they take forever to get to node 13 ($\hat{t} = 86.8$).</span>
<span id="cb32-71"><a href="#cb32-71"></a></span>
<span id="cb32-72"><a href="#cb32-72"></a>We can of course, write a wrapper around the <span class="in">`first.pass1`</span> function to compute the average first passage time from one node to another using every node in the graph as the initial seed, and put all of the results in a matrix $\mathbf{M}$ where each entry $m_{ij}$ is the average first passage time between nodes $i$ and $j$:</span>
<span id="cb32-73"><a href="#cb32-73"></a></span>
<span id="cb32-76"><a href="#cb32-76"></a><span class="in">```{r}</span></span>
<span id="cb32-77"><a href="#cb32-77"></a>first.pass2 <span class="ot">&lt;-</span> <span class="cf">function</span>(w, n) {</span>
<span id="cb32-78"><a href="#cb32-78"></a>  m <span class="ot">&lt;-</span> <span class="fu">rowMeans</span>(<span class="fu">replicate</span>(n, <span class="fu">first.pass1</span>(w)))</span>
<span id="cb32-79"><a href="#cb32-79"></a>  <span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">2</span><span class="sc">:</span><span class="fu">nrow</span>(w)) {</span>
<span id="cb32-80"><a href="#cb32-80"></a>    m <span class="ot">&lt;-</span> <span class="fu">rbind</span>(m, <span class="fu">rowMeans</span>(<span class="fu">replicate</span>(n, <span class="fu">first.pass1</span>(w, <span class="at">seed =</span> i))))</span>
<span id="cb32-81"><a href="#cb32-81"></a>  }</span>
<span id="cb32-82"><a href="#cb32-82"></a>  <span class="fu">rownames</span>(m) <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(w)</span>
<span id="cb32-83"><a href="#cb32-83"></a>  <span class="fu">return</span>(m)</span>
<span id="cb32-84"><a href="#cb32-84"></a>}</span>
<span id="cb32-85"><a href="#cb32-85"></a><span class="in">```</span></span>
<span id="cb32-86"><a href="#cb32-86"></a></span>
<span id="cb32-87"><a href="#cb32-87"></a>And the result (showing the first ten rows and columns of $\mathbf{M}$) is:</span>
<span id="cb32-88"><a href="#cb32-88"></a></span>
<span id="cb32-91"><a href="#cb32-91"></a><span class="in">```{r}</span></span>
<span id="cb32-92"><a href="#cb32-92"></a><span class="fu">set.seed</span>(<span class="dv">456</span>)</span>
<span id="cb32-93"><a href="#cb32-93"></a><span class="fu">round</span>(<span class="fu">first.pass2</span>(P, <span class="dv">100</span>), <span class="dv">1</span>)[<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>, <span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>]</span>
<span id="cb32-94"><a href="#cb32-94"></a><span class="in">```</span></span>
<span id="cb32-95"><a href="#cb32-95"></a></span>
<span id="cb32-96"><a href="#cb32-96"></a>Note that the $\mathbf{M}$ matrix is asymmetric. That is, the average number of steps that it takes for something to get from me to you ($m_{ij}$), is not necessarily the same as the average number of steps that it takes for something to get from you to me ($m_{ji}$). </span>
<span id="cb32-97"><a href="#cb32-97"></a></span>
<span id="cb32-98"><a href="#cb32-98"></a>The accuracy of the average first passage time estimate we get depends on the number of replications we use to get the average. The bigger, the more accurate. However, it can take a lot of computing time if we increased <span class="in">`n`</span> to a giant number.</span>
<span id="cb32-99"><a href="#cb32-99"></a></span>
<span id="cb32-100"><a href="#cb32-100"></a><span class="fu">### Computing the AFPT by Iterating Until Convergence</span></span>
<span id="cb32-101"><a href="#cb32-101"></a></span>
<span id="cb32-102"><a href="#cb32-102"></a>There's a more efficient approach to computing the entries in the average first passage time matrix $\mathbf{M}$ that involves iterating through a matrix using the information in the transition matrix $\mathbf{P}$. The basic idea is that the average first passage time for a random walker that starts at node $i$ and ends at node $j$ is given by:</span>
<span id="cb32-103"><a href="#cb32-103"></a></span>
<span id="cb32-104"><a href="#cb32-104"></a>$$</span>
<span id="cb32-105"><a href="#cb32-105"></a>m_{ij} = 1 + \sum^N_{j \neq k}p_{ik}m_{k,j}</span>
<span id="cb32-106"><a href="#cb32-106"></a>$$ {#eq-first-pass-iter}</span>
<span id="cb32-107"><a href="#cb32-107"></a></span>
<span id="cb32-108"><a href="#cb32-108"></a>With the proviso that $m_{ii}$ is always equal to zero. What this tells us is that the average first passage time between any two nodes in the graph $i$ and $j$, is given by one plus the product of the probability that something can transition from a sender node $i$ to an intermediary node $k$---given by $p_{ik}$---and $m_{kj}$ which is the average first passage time from that intermediary node $k$ to the destination node $j$. </span>
<span id="cb32-109"><a href="#cb32-109"></a></span>
<span id="cb32-110"><a href="#cb32-110"></a>Note that since we need to know $m_{kj}$ to get $m_{ij}$, then this opens up a chicken or the egg problem that we can solve through iteration like we did for the status scores in the <span class="co">[</span><span class="ot">prestige</span><span class="co">](prest-eigen.qmd)</span> lesson. </span>
<span id="cb32-111"><a href="#cb32-111"></a></span>
<span id="cb32-112"><a href="#cb32-112"></a>Here's how to proceed. We first start with a null value for all the entries of the $\mathbf{M}$ matrix (e.g., $m_{ij} = 0$ for all $i$ and $j$), compute an initial round of $m_{ij}$ estimates for all pairs of nodes $i$ and $j$ using @eq-first-pass-iter, recompute $m_{ij}$ using those new values, rinse, repeat, and stop after we don't get any big changes between successive versions of the $\mathbf{M}$ matrix. </span>
<span id="cb32-113"><a href="#cb32-113"></a></span>
<span id="cb32-114"><a href="#cb32-114"></a>A function that implement this idea goes like this:</span>
<span id="cb32-115"><a href="#cb32-115"></a></span>
<span id="cb32-118"><a href="#cb32-118"></a><span class="in">```{r}</span></span>
<span id="cb32-119"><a href="#cb32-119"></a>first.pass3 <span class="ot">&lt;-</span> <span class="cf">function</span>(w) {</span>
<span id="cb32-120"><a href="#cb32-120"></a>  n <span class="ot">&lt;-</span> <span class="fu">nrow</span>(w)</span>
<span id="cb32-121"><a href="#cb32-121"></a>  nodes <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">:</span>n</span>
<span id="cb32-122"><a href="#cb32-122"></a>  m <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="dv">0</span>, n, n) <span class="co"># initializing M matrix values</span></span>
<span id="cb32-123"><a href="#cb32-123"></a>  d <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="co"># initialize delta</span></span>
<span id="cb32-124"><a href="#cb32-124"></a>  <span class="cf">while</span> (d <span class="sc">&gt;</span> <span class="fl">1e-06</span>) { <span class="co"># do while delta is bigger than a tiny number</span></span>
<span id="cb32-125"><a href="#cb32-125"></a>    old.m <span class="ot">&lt;-</span> m</span>
<span id="cb32-126"><a href="#cb32-126"></a>    <span class="cf">for</span> (i <span class="cf">in</span> nodes) { <span class="co"># loop through every node</span></span>
<span id="cb32-127"><a href="#cb32-127"></a>      <span class="cf">for</span> (j <span class="cf">in</span> nodes[<span class="sc">-</span>i]) { <span class="co"># loop through every node except i</span></span>
<span id="cb32-128"><a href="#cb32-128"></a>        m[i, j] <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb32-129"><a href="#cb32-129"></a>        <span class="cf">for</span> (k <span class="cf">in</span> nodes[<span class="sc">-</span><span class="fu">c</span>(i, j)]) { <span class="co"># loop through every node except i and j</span></span>
<span id="cb32-130"><a href="#cb32-130"></a>          m[i, j] <span class="ot">&lt;-</span> m[i, j] <span class="sc">+</span> (w[i, k] <span class="sc">*</span> old.m[k, j]) <span class="co"># update M matrix values</span></span>
<span id="cb32-131"><a href="#cb32-131"></a>        }</span>
<span id="cb32-132"><a href="#cb32-132"></a>      }</span>
<span id="cb32-133"><a href="#cb32-133"></a>    }</span>
<span id="cb32-134"><a href="#cb32-134"></a>    d <span class="ot">&lt;-</span> <span class="fu">abs</span>(<span class="fu">sum</span>(<span class="fu">abs</span>(m) <span class="sc">-</span> <span class="fu">abs</span>(old.m))) <span class="co"># delta equals difference between current and previous M matrix</span></span>
<span id="cb32-135"><a href="#cb32-135"></a>  } <span class="co"># end while loop</span></span>
<span id="cb32-136"><a href="#cb32-136"></a>  <span class="fu">return</span>(m)</span>
<span id="cb32-137"><a href="#cb32-137"></a>}</span>
<span id="cb32-138"><a href="#cb32-138"></a><span class="in">```</span></span>
<span id="cb32-139"><a href="#cb32-139"></a></span>
<span id="cb32-140"><a href="#cb32-140"></a>This function takes the probability transition matrix $\mathbf{P}$ as input and returns the $\mathbf{M}$ matrix of average first passage times between every pair of nodes in the network. </span>
<span id="cb32-141"><a href="#cb32-141"></a></span>
<span id="cb32-142"><a href="#cb32-142"></a>And the result is:</span>
<span id="cb32-143"><a href="#cb32-143"></a></span>
<span id="cb32-146"><a href="#cb32-146"></a><span class="in">```{r}</span></span>
<span id="cb32-147"><a href="#cb32-147"></a><span class="fu">round</span>(<span class="fu">first.pass3</span>(P), <span class="dv">1</span>)[<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>, <span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>]</span>
<span id="cb32-148"><a href="#cb32-148"></a><span class="in">```</span></span>
<span id="cb32-149"><a href="#cb32-149"></a></span>
<span id="cb32-150"><a href="#cb32-150"></a>Which are the exact (up to rounding error) average first passage times between each pair of nodes in the network.</span>
<span id="cb32-151"><a href="#cb32-151"></a></span>
<span id="cb32-152"><a href="#cb32-152"></a><span class="fu">## Computing the AFPT Using the Laplacian Matrix</span></span>
<span id="cb32-153"><a href="#cb32-153"></a></span>
<span id="cb32-154"><a href="#cb32-154"></a>Finally, there is a way to use matrix algebra magic to compute the average first passage time at the limit ($n \approx \infty$) in closed form without averaging or iterations.</span>
<span id="cb32-155"><a href="#cb32-155"></a></span>
<span id="cb32-156"><a href="#cb32-156"></a>To do that, first we need to compute a matrix called the **graph Laplacian**, which is defined as:</span>
<span id="cb32-157"><a href="#cb32-157"></a></span>
<span id="cb32-158"><a href="#cb32-158"></a>$$</span>
<span id="cb32-159"><a href="#cb32-159"></a>\mathbf{L} = \mathbf{D} - \mathbf{A}</span>
<span id="cb32-160"><a href="#cb32-160"></a>$$ {#eq-lap}</span>
<span id="cb32-161"><a href="#cb32-161"></a></span>
<span id="cb32-162"><a href="#cb32-162"></a>Where $\mathbf{D}$ is a diagonal matrix containing the degrees of each node in the graph along the diagonals and zeroes everywhere else. </span>
<span id="cb32-163"><a href="#cb32-163"></a></span>
<span id="cb32-164"><a href="#cb32-164"></a>In <span class="in">`R`</span> we can compute $\mathbf{L}$ like this:</span>
<span id="cb32-165"><a href="#cb32-165"></a></span>
<span id="cb32-168"><a href="#cb32-168"></a><span class="in">```{r}</span></span>
<span id="cb32-169"><a href="#cb32-169"></a>D <span class="ot">&lt;-</span> <span class="fu">diag</span>(<span class="fu">rowSums</span>(A))</span>
<span id="cb32-170"><a href="#cb32-170"></a>L <span class="ot">&lt;-</span> D <span class="sc">-</span> A</span>
<span id="cb32-171"><a href="#cb32-171"></a><span class="in">```</span></span>
<span id="cb32-172"><a href="#cb32-172"></a></span>
<span id="cb32-173"><a href="#cb32-173"></a>Once we have $\mathbf{L}$, we need to compute a variation known by the less than memorable name of the **Moore-Penrose Pseudo-Inverse of the Laplacian**, written as $\mathbf{L}^+$, which is given by:</span>
<span id="cb32-174"><a href="#cb32-174"></a></span>
<span id="cb32-175"><a href="#cb32-175"></a>$$</span>
<span id="cb32-176"><a href="#cb32-176"></a>\mathbf{L}^+ = \left(\mathbf{L} - \frac{\mathbf{E}}{N}\right) ^{-1}- \frac{\mathbf{E}}{N}</span>
<span id="cb32-177"><a href="#cb32-177"></a>$$ {#eq-ilap}</span>
<span id="cb32-178"><a href="#cb32-178"></a></span>
<span id="cb32-179"><a href="#cb32-179"></a>Where $\mathbf{E}$ is the all ones matrix of the same dimensions as $\mathbf{L}$.</span>
<span id="cb32-180"><a href="#cb32-180"></a></span>
<span id="cb32-181"><a href="#cb32-181"></a>So despite the terrible name, $\mathbf{L}^+$ is easy to compute in <span class="in">`R`</span>:</span>
<span id="cb32-182"><a href="#cb32-182"></a></span>
<span id="cb32-185"><a href="#cb32-185"></a><span class="in">```{r}</span></span>
<span id="cb32-186"><a href="#cb32-186"></a>E <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="dv">1</span>, <span class="fu">nrow</span>(A), <span class="fu">nrow</span>(A)) <span class="sc">/</span> <span class="fu">nrow</span>(A)</span>
<span id="cb32-187"><a href="#cb32-187"></a>L.p <span class="ot">&lt;-</span> <span class="fu">solve</span>(L <span class="sc">+</span> E) <span class="sc">-</span> E</span>
<span id="cb32-188"><a href="#cb32-188"></a><span class="in">```</span></span>
<span id="cb32-189"><a href="#cb32-189"></a></span>
<span id="cb32-190"><a href="#cb32-190"></a>As we can see, <span class="in">`E`</span> is just a matrix containing the inverse of the number of nodes in the network in every cell ($\frac{1}{N}$). We use the function <span class="in">`solve`</span> to obtain the **matrix inverse** of the expression in parentheses in .</span>
<span id="cb32-191"><a href="#cb32-191"></a></span>
<span id="cb32-192"><a href="#cb32-192"></a>What's in the $\mathbf{L}^+$ matrix? Let's see the first ten rows and columns:</span>
<span id="cb32-193"><a href="#cb32-193"></a></span>
<span id="cb32-196"><a href="#cb32-196"></a><span class="in">```{r}</span></span>
<span id="cb32-197"><a href="#cb32-197"></a><span class="fu">round</span>(L.p[<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>, <span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>], <span class="dv">3</span>)</span>
<span id="cb32-198"><a href="#cb32-198"></a><span class="in">```</span></span>
<span id="cb32-199"><a href="#cb32-199"></a></span>
<span id="cb32-200"><a href="#cb32-200"></a>As we can see, some of the entries of $\mathbf{L}^+$ are positive and others are negative. More interestingly, we can see that $\mathbf{L}^+$ is a **symmetric** matrix: $l^+_{ij} = l^+_{ij}$. </span>
<span id="cb32-201"><a href="#cb32-201"></a></span>
<span id="cb32-202"><a href="#cb32-202"></a>Even more interestingly, $\mathbf{L}^+$ is **doubly centered**---similar to the **modularity matrix** <span class="co">[</span><span class="ot">considered here</span><span class="co">](comm-mod.qmd)</span>. That means *both* the rows and column sums of the matrix are equal to the all zeros vector:</span>
<span id="cb32-203"><a href="#cb32-203"></a></span>
<span id="cb32-206"><a href="#cb32-206"></a><span class="in">```{r}</span></span>
<span id="cb32-207"><a href="#cb32-207"></a><span class="fu">round</span>(<span class="fu">rowSums</span>(L.p), <span class="dv">2</span>)</span>
<span id="cb32-208"><a href="#cb32-208"></a><span class="fu">round</span>(<span class="fu">colSums</span>(L.p), <span class="dv">2</span>)</span>
<span id="cb32-209"><a href="#cb32-209"></a><span class="in">```</span></span>
<span id="cb32-210"><a href="#cb32-210"></a></span>
<span id="cb32-211"><a href="#cb32-211"></a>The average first passage time between every pair of nodes in the network $m_{ij}$ expressed in terms of the entries of $\mathbf{L}^+$ and the degree vector $\mathbf{d}$, is then given by <span class="co">[</span><span class="ot">@fouss_etal16, p. 158</span><span class="co">]</span>:</span>
<span id="cb32-212"><a href="#cb32-212"></a></span>
<span id="cb32-213"><a href="#cb32-213"></a>$$</span>
<span id="cb32-214"><a href="#cb32-214"></a>m_{ij} = \sum_{k=1}^n \left(l^+_{jj} - l^+_{ij} + l^+_{ik} - l^+_{kj}\right)d_k</span>
<span id="cb32-215"><a href="#cb32-215"></a>$$ {#eq-firstpass}</span>
<span id="cb32-216"><a href="#cb32-216"></a></span>
<span id="cb32-217"><a href="#cb32-217"></a>Where $d_k$ is the degree of node $k$.</span>
<span id="cb32-218"><a href="#cb32-218"></a></span>
<span id="cb32-219"><a href="#cb32-219"></a>So let's try it out:</span>
<span id="cb32-220"><a href="#cb32-220"></a></span>
<span id="cb32-223"><a href="#cb32-223"></a><span class="in">```{r}</span></span>
<span id="cb32-224"><a href="#cb32-224"></a>nodes <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(A) <span class="co"># node id vector</span></span>
<span id="cb32-225"><a href="#cb32-225"></a>d <span class="ot">&lt;-</span> <span class="fu">rowSums</span>(A) <span class="co"># degree vector</span></span>
<span id="cb32-226"><a href="#cb32-226"></a>m <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="dv">0</span>, <span class="fu">nrow</span>(A), <span class="fu">nrow</span>(A)) <span class="co"># initializing M to all zeros</span></span>
<span id="cb32-227"><a href="#cb32-227"></a><span class="cf">for</span> (i <span class="cf">in</span> nodes) {</span>
<span id="cb32-228"><a href="#cb32-228"></a>  <span class="cf">for</span> (j <span class="cf">in</span> nodes) {</span>
<span id="cb32-229"><a href="#cb32-229"></a>    <span class="cf">for</span> (k <span class="cf">in</span> nodes) {</span>
<span id="cb32-230"><a href="#cb32-230"></a>      m[i, j] <span class="ot">&lt;-</span> m[i, j] <span class="sc">+</span> ((L.p[j, j] <span class="sc">-</span> L.p[i, j] <span class="sc">+</span> L.p[i, k] <span class="sc">-</span> L.p[k, j]) <span class="sc">*</span> d[k])</span>
<span id="cb32-231"><a href="#cb32-231"></a>    }</span>
<span id="cb32-232"><a href="#cb32-232"></a>  }</span>
<span id="cb32-233"><a href="#cb32-233"></a>}</span>
<span id="cb32-234"><a href="#cb32-234"></a><span class="fu">round</span>(m[<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>, <span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>], <span class="dv">1</span>)</span>
<span id="cb32-235"><a href="#cb32-235"></a><span class="in">```</span></span>
<span id="cb32-236"><a href="#cb32-236"></a></span>
<span id="cb32-237"><a href="#cb32-237"></a>Which produces exactly the same results we obtained earlier via iteration. </span>
<span id="cb32-238"><a href="#cb32-238"></a></span>
<span id="cb32-239"><a href="#cb32-239"></a><span class="fu">## Computing the AFPT Using a Big Matrix Formula</span></span>
<span id="cb32-240"><a href="#cb32-240"></a></span>
<span id="cb32-241"><a href="#cb32-241"></a>There is an even more straightforward way to compute the average first passage time that does not involve looping at all, but simple matrix operations. We can do that because we can express in matrix form like this:</span>
<span id="cb32-242"><a href="#cb32-242"></a></span>
<span id="cb32-243"><a href="#cb32-243"></a>$$</span>
<span id="cb32-244"><a href="#cb32-244"></a>\mathbf{M} = \left<span class="co">[</span><span class="ot">vol(A)\mathbf{e}(\mathbf{l}^+_{d})^T - vol(A)\mathbf{L}^+\right</span><span class="co">]</span> + \left<span class="co">[</span><span class="ot">(\mathbf{L}^+\mathbf{d})\mathbf{e}^T -\mathbf{e}(\mathbf{d}^T\mathbf{L}^+)\right</span><span class="co">]</span></span>
<span id="cb32-245"><a href="#cb32-245"></a>$$</span>
<span id="cb32-246"><a href="#cb32-246"></a></span>
<span id="cb32-247"><a href="#cb32-247"></a>Now, this formula looks long and monstrous but it is composed of simple quantities we know and love. We have already been introduced to $\mathbf{L}^+$, while $\mathbf{e}$ is a column vector of ones with as many rows as the number of nodes in the graph, $\mathbf{d}$ is a vector of the same length as the number of nodes in the graph containing the degrees of each node at each position, $vol(A) = \sum_{i} d_{i}$ is just the sum of the non-zero entries in the adjacency matrix, and $\mathbf{l}^+_{d}$ is a vector containing the diagonal entries of $\mathbf{L}^+$ at each position. </span>
<span id="cb32-248"><a href="#cb32-248"></a></span>
<span id="cb32-249"><a href="#cb32-249"></a>The following <span class="in">`R`</span> code constructs $\mathbf{M}$ step by step:</span>
<span id="cb32-250"><a href="#cb32-250"></a></span>
<span id="cb32-253"><a href="#cb32-253"></a><span class="in">```{r}</span></span>
<span id="cb32-254"><a href="#cb32-254"></a>e <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="dv">1</span>, <span class="fu">nrow</span>(A), <span class="dv">1</span>) <span class="co"># column vector of all ones</span></span>
<span id="cb32-255"><a href="#cb32-255"></a>d <span class="ot">&lt;-</span> <span class="fu">rowSums</span>(A) <span class="co"># degree vector</span></span>
<span id="cb32-256"><a href="#cb32-256"></a>l <span class="ot">&lt;-</span> <span class="fu">diag</span>(L.p) <span class="co"># diagonal vector of Laplacian inverse</span></span>
<span id="cb32-257"><a href="#cb32-257"></a>vol.A <span class="ot">&lt;-</span> <span class="fu">sum</span>(d) <span class="co"># graph volume</span></span>
<span id="cb32-258"><a href="#cb32-258"></a>M <span class="ot">&lt;-</span> vol.A <span class="sc">*</span> (e <span class="sc">%*%</span> <span class="fu">t</span>(l))</span>
<span id="cb32-259"><a href="#cb32-259"></a>M <span class="ot">&lt;-</span> M <span class="sc">-</span> (vol.A <span class="sc">*</span> L.p)</span>
<span id="cb32-260"><a href="#cb32-260"></a>M <span class="ot">&lt;-</span> M <span class="sc">+</span> (L.p <span class="sc">%*%</span> d) <span class="sc">%*%</span> <span class="fu">t</span>(e)</span>
<span id="cb32-261"><a href="#cb32-261"></a>M <span class="ot">&lt;-</span> M <span class="sc">-</span> (e <span class="sc">%*%</span> (<span class="fu">t</span>(d) <span class="sc">%*%</span> L.p))</span>
<span id="cb32-262"><a href="#cb32-262"></a><span class="in">```</span></span>
<span id="cb32-263"><a href="#cb32-263"></a></span>
<span id="cb32-264"><a href="#cb32-264"></a>And now for the big reveal:</span>
<span id="cb32-265"><a href="#cb32-265"></a></span>
<span id="cb32-268"><a href="#cb32-268"></a><span class="in">```{r}</span></span>
<span id="cb32-269"><a href="#cb32-269"></a><span class="fu">round</span>(M, <span class="dv">1</span>)[<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>, <span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>]</span>
<span id="cb32-270"><a href="#cb32-270"></a><span class="in">```</span></span>
<span id="cb32-271"><a href="#cb32-271"></a></span>
<span id="cb32-272"><a href="#cb32-272"></a>Which once again, gives us the results we seek.</span>
<span id="cb32-273"><a href="#cb32-273"></a></span>
<span id="cb32-274"><a href="#cb32-274"></a>As we saw earlier, the interpretation of the entries of the $\mathbf{M}$ matrix is also straightforward. For instance, if we start a message from node 2, we should expect it to take an average of $m_{2, 6} =$ <span class="in">`r round(M[2,6], 1)`</span> steps to get to node 6 by following random walks in the network.</span>
<span id="cb32-275"><a href="#cb32-275"></a></span>
<span id="cb32-276"><a href="#cb32-276"></a><span class="fu">## The Average Commute Distance</span></span>
<span id="cb32-277"><a href="#cb32-277"></a></span>
<span id="cb32-278"><a href="#cb32-278"></a>Once we have the average first passage time, we can compute another important quantity called the **average commute distance** between two nodes $i$ and $j$ ($n_{ij}$). This is the number of steps it takes for a random walker to start at node $i$, reach another specific node $j$ and then *get back* to the original node $i$ (hence commuting, like going from home to work and then back from work to home again). </span>
<span id="cb32-279"><a href="#cb32-279"></a></span>
<span id="cb32-280"><a href="#cb32-280"></a>It turns out that $n_{ij}$ is pretty simple to compute, once we know the average first passage time between every pair of nodes $m_{ij}$, since it is given by:</span>
<span id="cb32-281"><a href="#cb32-281"></a></span>
<span id="cb32-282"><a href="#cb32-282"></a>$$</span>
<span id="cb32-283"><a href="#cb32-283"></a> n_{ij} = m_{ij} + m_{ji}</span>
<span id="cb32-284"><a href="#cb32-284"></a>$$</span>
<span id="cb32-285"><a href="#cb32-285"></a></span>
<span id="cb32-286"><a href="#cb32-286"></a>So the entries of the Average Commute Distance matrix $\mathbf{N}$ are just the entries of $\mathbf{M}$ on the upper triangle added to the corresponding entries in the lower triangle. In <span class="in">`R`</span> we can obtain that by just adding $\mathbf{M}$ to its transpose $\mathbf{M}^T$:</span>
<span id="cb32-287"><a href="#cb32-287"></a></span>
<span id="cb32-290"><a href="#cb32-290"></a><span class="in">```{r}</span></span>
<span id="cb32-291"><a href="#cb32-291"></a>N <span class="ot">&lt;-</span> M <span class="sc">+</span> <span class="fu">t</span>(M)</span>
<span id="cb32-292"><a href="#cb32-292"></a><span class="fu">round</span>(N[<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>, <span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>], <span class="dv">1</span>)</span>
<span id="cb32-293"><a href="#cb32-293"></a><span class="in">```</span></span>
<span id="cb32-294"><a href="#cb32-294"></a></span>
<span id="cb32-295"><a href="#cb32-295"></a>Note that the average commute distance matrix entries are symmetric, which makes sense, for it takes as long for something to go from to you to me and back to you as from me to you and back to me. The average commute distance between pairs of nodes thus functions as a **similarity metric**; the lower the average commute distance, the closer or more similar two nodes are in the network. </span>
<span id="cb32-296"><a href="#cb32-296"></a></span>
<span id="cb32-297"><a href="#cb32-297"></a>Of course, we can also use math to compute $\mathbf{N}$ directly from the entries of $\mathbf{L}^+$ using a recombination of the same ingredients we used before to compute the average first passage time. It goes like this:</span>
<span id="cb32-298"><a href="#cb32-298"></a></span>
<span id="cb32-299"><a href="#cb32-299"></a>$$</span>
<span id="cb32-300"><a href="#cb32-300"></a>n_{ij} = vol(A) \left(l^+_{ii} + l^+_{jj} + 2l^+_{ij}\right)</span>
<span id="cb32-301"><a href="#cb32-301"></a>$$</span>
<span id="cb32-302"><a href="#cb32-302"></a></span>
<span id="cb32-303"><a href="#cb32-303"></a>Which in (more complicated) matrix form looks like:</span>
<span id="cb32-304"><a href="#cb32-304"></a></span>
<span id="cb32-305"><a href="#cb32-305"></a>$$</span>
<span id="cb32-306"><a href="#cb32-306"></a>\mathbf{N} = vol(A)\left<span class="co">[</span><span class="ot">\mathbf{l}^+_{d}\mathbf{e}^T + \mathbf{e}\mathbf{l}^+_{d} - 2\mathbf{L}^+\right</span><span class="co">]</span></span>
<span id="cb32-307"><a href="#cb32-307"></a>$$</span>
<span id="cb32-308"><a href="#cb32-308"></a></span>
<span id="cb32-309"><a href="#cb32-309"></a>But which is actually a much less monstrous and simpler expression than before. </span>
<span id="cb32-310"><a href="#cb32-310"></a></span>
<span id="cb32-311"><a href="#cb32-311"></a>The following <span class="in">`R`</span> code constructs the $\mathbf{N}$ matrix of average commute distances between each pair of nodes in the network step by step:</span>
<span id="cb32-312"><a href="#cb32-312"></a></span>
<span id="cb32-315"><a href="#cb32-315"></a><span class="in">```{r}</span></span>
<span id="cb32-316"><a href="#cb32-316"></a>N <span class="ot">&lt;-</span> l <span class="sc">%*%</span> <span class="fu">t</span>(e)</span>
<span id="cb32-317"><a href="#cb32-317"></a>N <span class="ot">&lt;-</span> N <span class="sc">+</span> (e <span class="sc">%*%</span> l)</span>
<span id="cb32-318"><a href="#cb32-318"></a>N <span class="ot">&lt;-</span> N <span class="sc">-</span> (<span class="dv">2</span> <span class="sc">*</span> L.p)</span>
<span id="cb32-319"><a href="#cb32-319"></a>N <span class="ot">&lt;-</span> vol.A <span class="sc">*</span> N</span>
<span id="cb32-320"><a href="#cb32-320"></a><span class="fu">round</span>(N, <span class="dv">1</span>)[<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>, <span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>]</span>
<span id="cb32-321"><a href="#cb32-321"></a><span class="in">```</span></span>
<span id="cb32-322"><a href="#cb32-322"></a></span>
<span id="cb32-323"><a href="#cb32-323"></a>Which as you can see, gives us the results we seek. </span>
<span id="cb32-324"><a href="#cb32-324"></a></span>
<span id="cb32-325"><a href="#cb32-325"></a>The interpretation of the entries of the $\mathbf{N}$ matrix is also straightforward. For instance, if a message starts at node 4, it would take an average of <span class="in">`r round(N[4, 9], 1)`</span> steps for it to get to node 9 and then back to the original node 4 by following a random walk in the network governed by the node-to-node probabilities stored in the transition matrix $\mathbf{P}$. </span>
<span id="cb32-326"><a href="#cb32-326"></a></span>
<span id="cb32-327"><a href="#cb32-327"></a>Interestingly, we can obtain the average commute time distance between any pair nodes yet another way. For instance from the above matrix, we know the average commute time distances between nodes 3 and 8 is <span class="in">`r round(N[3, 8], 2)`</span>. </span>
<span id="cb32-328"><a href="#cb32-328"></a></span>
<span id="cb32-329"><a href="#cb32-329"></a>Let's construct two vectors full of zeros of the same length as the number of nodes in the graph, except they have a one in the third and eighth spot respectively:</span>
<span id="cb32-330"><a href="#cb32-330"></a></span>
<span id="cb32-333"><a href="#cb32-333"></a><span class="in">```{r}</span></span>
<span id="cb32-334"><a href="#cb32-334"></a>n <span class="ot">&lt;-</span> <span class="fu">ncol</span>(A)</span>
<span id="cb32-335"><a href="#cb32-335"></a>i <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="dv">0</span>, n)</span>
<span id="cb32-336"><a href="#cb32-336"></a>j <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="dv">0</span>, n)</span>
<span id="cb32-337"><a href="#cb32-337"></a>i[<span class="dv">3</span>] <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb32-338"><a href="#cb32-338"></a>j[<span class="dv">8</span>] <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb32-339"><a href="#cb32-339"></a><span class="in">```</span></span>
<span id="cb32-340"><a href="#cb32-340"></a></span>
<span id="cb32-341"><a href="#cb32-341"></a>@fouss_etal04b show that the average commute time distance between nodes 3 and 8 is also given by:</span>
<span id="cb32-342"><a href="#cb32-342"></a></span>
<span id="cb32-345"><a href="#cb32-345"></a><span class="in">```{r}</span></span>
<span id="cb32-346"><a href="#cb32-346"></a><span class="fu">round</span>(<span class="fu">sum</span>(A) <span class="sc">*</span> (<span class="fu">t</span>((i <span class="sc">-</span> j)) <span class="sc">%*%</span> L.p <span class="sc">%*%</span> (i <span class="sc">-</span> j)), <span class="dv">2</span>)</span>
<span id="cb32-347"><a href="#cb32-347"></a><span class="in">```</span></span>
<span id="cb32-348"><a href="#cb32-348"></a></span>
<span id="cb32-349"><a href="#cb32-349"></a>Neat!</span>
</code></pre></div><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/olizardo/SOCIOL208/blob/main/basic-random.qmd" class="toc-action"><i class="bi bi-github"></i>View source</a></li></ul></div></div></div></footer></body></html>