<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.313">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>SOCIOL 208 - Statistical Models of Networks IV</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="styles.css">
<meta property="og:title" content="SOCIOL 208 - Statistical Models of Networks IV">
<meta property="og:description" content="In the two-mode case, ERGMs allow us to test multivariate hypothesis regarding patterns of affiliations between persons and groups, net of other network characteristics.">
<meta property="og:site-name" content="SOCIOL 208">
</head>

<body class="nav-sidebar docked">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
    <div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title">Statistical Models of Networks IV</h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">SOCIOL 208</a> 
        <div class="sidebar-tools-main">
  <a href="" class="quarto-color-scheme-toggle sidebar-tool" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
    </div>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">Home</a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">208A</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./syllabus-208A.html" class="sidebar-item-text sidebar-link">208A Syllabus</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./schedule-208A-F24.html" class="sidebar-item-text sidebar-link">SOCIOL 208A Reading Schedule (Fall 2024)</a>
  </div>
</li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">Handouts</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth2 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./handout1.html" class="sidebar-item-text sidebar-link">Basic Network Statistics</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./inoutdegdist.html" class="sidebar-item-text sidebar-link">Graph Degree Metrics in Directed Networks</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./handout2.html" class="sidebar-item-text sidebar-link">Centrality</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cube.html" class="sidebar-item-text sidebar-link">The Cube</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./handout3.html" class="sidebar-item-text sidebar-link">Status and Prestige</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./handout4.html" class="sidebar-item-text sidebar-link">Role Equivalence and Structural Similarity</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./handout5.html" class="sidebar-item-text sidebar-link">Vertex Similarity</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./blondel.html" class="sidebar-item-text sidebar-link">Role Similarity Across Graphs</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./handout6.html" class="sidebar-item-text sidebar-link">Community Structure</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ahn.html" class="sidebar-item-text sidebar-link">Assigning Nodes to Multiple Communities</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./handout7.html" class="sidebar-item-text sidebar-link">Analyzing Two-Mode Networks</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ca.html" class="sidebar-item-text sidebar-link">Correspondence Analysis (CA) of Two-Mode Networks</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./spectral.html" class="sidebar-item-text sidebar-link">Community Detection Using Spectral Clustering</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./handout8.html" class="sidebar-item-text sidebar-link">Analyzing Ego Networks</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./handout9.html" class="sidebar-item-text sidebar-link">Statistical Models of Networks I</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./handout10.html" class="sidebar-item-text sidebar-link">Statistical Models of Networks II</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./handout11.html" class="sidebar-item-text sidebar-link">Statistical Models of Networks III</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./handout12.html" class="sidebar-item-text sidebar-link active">Statistical Models of Networks IV</a>
  </div>
</li>
      </ul>
  </li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">208B</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./syllabus-208B.html" class="sidebar-item-text sidebar-link">208B Syllabus</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./schedule-208B-S24.html" class="sidebar-item-text sidebar-link">SOCIOL 208B Reading Schedule (Spring 2024)</a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#two-mode-ergms" id="toc-two-mode-ergms" class="nav-link active" data-scroll-target="#two-mode-ergms">Two-Mode ERGMs</a></li>
  <li><a href="#affiliation-heterogeneity-based-on-node-attributes" id="toc-affiliation-heterogeneity-based-on-node-attributes" class="nav-link" data-scroll-target="#affiliation-heterogeneity-based-on-node-attributes">Affiliation Heterogeneity Based on Node Attributes</a></li>
  <li><a href="#homophily-in-the-two-mode-case" id="toc-homophily-in-the-two-mode-case" class="nav-link" data-scroll-target="#homophily-in-the-two-mode-case">Homophily in the Two Mode Case</a></li>
  <li><a href="#conditining-on-degree" id="toc-conditining-on-degree" class="nav-link" data-scroll-target="#conditining-on-degree">Conditining on Degree</a></li>
  </ul>
<div class="toc-actions"><div><i class="bi bi-github"></i></div><div class="action-links"><p><a href="https://github.com/olizardo/SOCIOL208/blob/main/handout12.qmd" class="toc-action">View source</a></p></div></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title d-none d-lg-block">Statistical Models of Networks IV</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="two-mode-ergms" class="level2">
<h2 class="anchored" data-anchor-id="two-mode-ergms">Two-Mode ERGMs</h2>
<p>In the two-mode case, ERGMs allow us to test multivariate hypothesis regarding patterns of affiliations between persons and groups, net of other network characteristics.</p>
<p>Let’s load some data, this time we will use Daniel McFarland’s data of high school student affiliations with specific activity clubs collected in 1997:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1"></a>   url1 <span class="ot">&lt;-</span> <span class="st">"https://github.com/JeffreyAlanSmith/Integrated_Network_Science/raw/master/data/affiliations_1997.txt"</span></span>
<span id="cb1-2"><a href="#cb1-2"></a></span>
<span id="cb1-3"><a href="#cb1-3"></a>   A <span class="ot">&lt;-</span> <span class="fu">read.delim</span>(<span class="at">file =</span> url1, <span class="at">check.names =</span> <span class="cn">FALSE</span>)</span>
<span id="cb1-4"><a href="#cb1-4"></a>   <span class="fu">dim</span>(A)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1295   91</code></pre>
</div>
</div>
<p>The bi-adjacency matrix is of dimensions <span class="math inline">\(1295 \times 91\)</span>. The clubs are:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1"></a>   <span class="fu">colnames</span>(A)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "Academic decathalon"                  
 [2] "Art Club"                             
 [3] "Asian Club"                           
 [4] "Band, 8th"                            
 [5] "Band, Jazz"                           
 [6] "Band, Marching (Symphonic)"           
 [7] "Baseball, JV (10th)"                  
 [8] "Baseball, V"                          
 [9] "Basketball, boys 8th"                 
[10] "Basketball, boys 9th"                 
[11] "Basketball, boys JV"                  
[12] "Basketball, boys V"                   
[13] "Basketball, girls 8th"                
[14] "Basketball, girls 9th"                
[15] "Basketball, girls JV"                 
[16] "Basketball, girls V"                  
[17] "Cheerleaders, 8th"                    
[18] "Cheerleaders, 9th"                    
[19] "Cheerleaders, JV"                     
[20] "Cheerleaders, Spirit Squad"           
[21] "Cheerleaders, V"                      
[22] "Chess Club"                           
[23] "Choir, a capella"                     
[24] "Choir, barbershop quartet (4 men)"    
[25] "Choir, chamber singers"               
[26] "Choir, concert"                       
[27] "Choir, treble"                        
[28] "Choir, vocal ensemble (4 women)"      
[29] "Choir, women's ensemble"              
[30] "Close-up"                             
[31] "Cross Country, boys 8th"              
[32] "Cross Country, boys V"                
[33] "Cross Country, girls 8th"             
[34] "Cross Country, girls V"               
[35] "Debate"                               
[36] "Drill Team"                           
[37] "Drunk Driving"                        
[38] "Drunk Driving Officers"               
[39] "Football, 8th"                        
[40] "Football, 9th"                        
[41] "Football, V"                          
[42] "Forensics"                            
[43] "Forensics (National Forensics League)"
[44] "French Club (high)"                   
[45] "French Club (low)"                    
[46] "French NHS"                           
[47] "Full IB Diploma Students (12th)"      
[48] "German Club"                          
[49] "German NHS"                           
[50] "Golf, boys V"                         
[51] "Hispanic Club"                        
[52] "Internships"                          
[53] "Junior Class Board"                   
[54] "Key Club"                             
[55] "Latin Club"                           
[56] "Newspaper Staff"                      
[57] "NHS"                                  
[58] "Orchestra, 8th"                       
[59] "Orchestra, Full Concert"              
[60] "Orchestra, Symphonic"                 
[61] "PEER"                                 
[62] "Pep Club"                             
[63] "Pep Club Officers"                    
[64] "Quiz-Bowl (all)"                      
[65] "Science Olympiad"                     
[66] "Soccer, V"                            
[67] "Softball, JV (10th)"                  
[68] "Softball, V"                          
[69] "Spanish Club"                         
[70] "Spanish Club (high)"                  
[71] "Spanish NHS"                          
[72] "STUCO"                                
[73] "Swim &amp; Dive Team, boys"               
[74] "Swim &amp; Dive Team, girls"              
[75] "Teachers of Tomorrow"                 
[76] "Tennis girls V"                       
[77] "Tennis, boys V"                       
[78] "Theatre Productions"                  
[79] "Thespian Society (ITS)"               
[80] "Track, boys 8th"                      
[81] "Track, boys V"                        
[82] "Track, girls 8th"                     
[83] "Track, girls V"                       
[84] "Volleyball, 8th"                      
[85] "Volleyball, 9th"                      
[86] "Volleyball, JV"                       
[87] "Volleyball, V"                        
[88] "Wrestling, 8th"                       
[89] "Wrestling, V"                         
[90] "Yearbook Contributors"                
[91] "Yearbook Editors"                     </code></pre>
</div>
</div>
<p>We also have attributes for students and clubs:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1"></a>   url2 <span class="ot">&lt;-</span> <span class="st">"https://github.com/JeffreyAlanSmith/Integrated_Network_Science/raw/master/data/attributes_students.txt"</span></span>
<span id="cb5-2"><a href="#cb5-2"></a>   </span>
<span id="cb5-3"><a href="#cb5-3"></a>   sa <span class="ot">&lt;-</span> <span class="fu">read.delim</span>(<span class="at">file =</span> url2, <span class="at">stringsAsFactors =</span> <span class="cn">FALSE</span>)</span>
<span id="cb5-4"><a href="#cb5-4"></a>   </span>
<span id="cb5-5"><a href="#cb5-5"></a>   url3 <span class="ot">&lt;-</span> <span class="st">"https://github.com/JeffreyAlanSmith/Integrated_Network_Science/raw/master/data/attributes_clubs.txt"</span></span>
<span id="cb5-6"><a href="#cb5-6"></a>   </span>
<span id="cb5-7"><a href="#cb5-7"></a>   ca <span class="ot">&lt;-</span> <span class="fu">read.delim</span>(<span class="at">file =</span> url3, <span class="at">stringsAsFactors =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We then use the approach outlined <a href="https://inarwhal.github.io/NetworkAnalysisR-book/ch11-Two-mode-Networks.html#example-affiliation-data">here</a> to construct a vertex attribute data frame that <code>igraph</code> can use.</p>
<div class="cell">

</div>
<p>The resulting two mode network has the following characteristics:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1"></a>   <span class="fu">library</span>(network)</span>
<span id="cb6-2"><a href="#cb6-2"></a>   <span class="fu">table</span>(<span class="fu">V</span>(g)<span class="sc">$</span>type)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
FALSE  TRUE 
  922    91 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1"></a>   attribute_list <span class="ot">&lt;-</span> <span class="fu">do.call</span>(list, sca)</span>
<span id="cb8-2"><a href="#cb8-2"></a>   n <span class="ot">&lt;-</span> <span class="fu">network</span>(<span class="fu">as.matrix</span>(A), <span class="at">bipartite =</span> <span class="cn">TRUE</span>, <span class="at">vertex.attr =</span> attribute_list)</span>
<span id="cb8-3"><a href="#cb8-3"></a>   n</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> Network attributes:
  vertices = 1013 
  directed = FALSE 
  hyper = FALSE 
  loops = FALSE 
  multiple = FALSE 
  bipartite = 922 
  total edges= 2423 
    missing edges= 0 
    non-missing edges= 2423 

 Vertex attribute names: 
    club_feeder club_profile club_type_detailed club_type_gender club_type_grade gender grade96 grade97 ids missing96 missing97 race type vertex.names 

 Edge attribute names not shown </code></pre>
</div>
</div>
<p>We have a network with 2423 edges, 922 people nodes and 91 club nodes. Both the people and the clubs have vertex attributes.</p>
<p>And now let’s fit bipartite ergms!</p>
<p>As always, we begin with the baseline Erdos-Renyi random graph model that fits just the density:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1"></a>   <span class="fu">library</span>(ergm)</span>
<span id="cb10-2"><a href="#cb10-2"></a>   m1 <span class="ot">&lt;-</span> <span class="fu">ergm</span>(n <span class="sc">~</span> edges)</span>
<span id="cb10-3"><a href="#cb10-3"></a>   <span class="fu">summary</span>(m1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
ergm(formula = n ~ edges)

Maximum Likelihood Results:

      Estimate Std. Error MCMC % z value Pr(&gt;|z|)    
edges -3.51534    0.02061      0  -170.5   &lt;1e-04 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

     Null Deviance: 116313  on 83902  degrees of freedom
 Residual Deviance:  21953  on 83901  degrees of freedom
 
AIC: 21955  BIC: 21964  (Smaller is better. MC Std. Err. = 0)</code></pre>
</div>
</div>
<p>Which we can check is indeed the density:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1"></a>   <span class="fu">exp</span>(m1<span class="sc">$</span>coefficients[<span class="dv">1</span>])<span class="sc">/</span>(<span class="dv">1</span> <span class="sc">+</span> <span class="fu">exp</span>(m1<span class="sc">$</span>coefficients))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     edges 
0.02887893 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1"></a>   <span class="dv">2423</span><span class="sc">/</span>(<span class="dv">922</span> <span class="sc">*</span> <span class="dv">91</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.02887893</code></pre>
</div>
</div>
<p>Great. Now for more interesting stuff. Let’s look at affiliation heterogeneity based on gender and race.</p>
</section>
<section id="affiliation-heterogeneity-based-on-node-attributes" class="level2">
<h2 class="anchored" data-anchor-id="affiliation-heterogeneity-based-on-node-attributes">Affiliation Heterogeneity Based on Node Attributes</h2>
<p>For two-mode ergms, this works just a before, except that now we have to specify which node set the attribute belongs to. So instead of <code>nodefactor</code>, we use the <code>b1factor</code> and <code>b2factor</code> ergm terms.</p>
<p>In this case, <code>b1factor</code> refers to the people node set, so that’s what we will use:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1"></a>   <span class="fu">library</span>(ergm)</span>
<span id="cb16-2"><a href="#cb16-2"></a>   m2 <span class="ot">&lt;-</span> <span class="fu">ergm</span>(n <span class="sc">~</span> edges </span>
<span id="cb16-3"><a href="#cb16-3"></a>              <span class="sc">+</span> <span class="fu">b1factor</span>(<span class="st">"gender"</span>, <span class="at">base =</span> <span class="dv">2</span>)</span>
<span id="cb16-4"><a href="#cb16-4"></a>              <span class="sc">+</span> <span class="fu">b1factor</span>(<span class="st">"race"</span>, <span class="at">base =</span> <span class="dv">5</span>)</span>
<span id="cb16-5"><a href="#cb16-5"></a>              )</span>
<span id="cb16-6"><a href="#cb16-6"></a>   <span class="fu">summary</span>(m2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
ergm(formula = n ~ edges + b1factor("gender", base = 2) + b1factor("race", 
    base = 5))

Maximum Likelihood Results:

                              Estimate Std. Error MCMC % z value Pr(&gt;|z|)    
edges                         -3.71411    0.03870      0 -95.960   &lt;1e-04 ***
b1factor.gender.female         0.33093    0.04349      0   7.609   &lt;1e-04 ***
b1factor.race.Asian            0.06197    0.08848      0   0.700   0.4837    
b1factor.race.black           -0.04807    0.04497      0  -1.069   0.2850    
b1factor.race.Hispanic         0.26870    0.13035      0   2.061   0.0393 *  
b1factor.race.Native American  0.18215    0.21879      0   0.833   0.4051    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

     Null Deviance: 116313  on 83902  degrees of freedom
 Residual Deviance:  21888  on 83896  degrees of freedom
 
AIC: 21900  BIC: 21956  (Smaller is better. MC Std. Err. = 0)</code></pre>
</div>
</div>
<p>We find that women are more active than men. In the same way, compared to white people, Hispanic people tend to have more memberships.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1"></a>   <span class="fu">library</span>(ergm)</span>
<span id="cb18-2"><a href="#cb18-2"></a>   m2 <span class="ot">&lt;-</span> <span class="fu">ergm</span>(n <span class="sc">~</span> edges </span>
<span id="cb18-3"><a href="#cb18-3"></a>              <span class="sc">+</span> <span class="fu">b1factor</span>(<span class="st">"gender"</span>, <span class="at">base =</span> <span class="dv">2</span>) </span>
<span id="cb18-4"><a href="#cb18-4"></a>              <span class="sc">+</span> <span class="fu">b1factor</span>(<span class="st">"race"</span>, <span class="at">base =</span> <span class="dv">5</span>)</span>
<span id="cb18-5"><a href="#cb18-5"></a>              <span class="sc">+</span> <span class="fu">b1cov</span>(<span class="st">"grade97"</span>) </span>
<span id="cb18-6"><a href="#cb18-6"></a>              )</span>
<span id="cb18-7"><a href="#cb18-7"></a>   <span class="fu">summary</span>(m2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
ergm(formula = n ~ edges + b1factor("gender", base = 2) + b1factor("race", 
    base = 5) + b1cov("grade97"))

Maximum Likelihood Results:

                              Estimate Std. Error MCMC % z value Pr(&gt;|z|)    
edges                         -5.11734    0.16218      0 -31.554   &lt;1e-04 ***
b1factor.gender.female         0.33608    0.04349      0   7.728   &lt;1e-04 ***
b1factor.race.Asian            0.03073    0.08859      0   0.347   0.7287    
b1factor.race.black           -0.03454    0.04499      0  -0.768   0.4427    
b1factor.race.Hispanic         0.26985    0.13040      0   2.069   0.0385 *  
b1factor.race.Native American  0.12759    0.21892      0   0.583   0.5600    
b1cov.grade97                  0.13864    0.01537      0   9.020   &lt;1e-04 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

     Null Deviance: 116313  on 83902  degrees of freedom
 Residual Deviance:  21806  on 83895  degrees of freedom
 
AIC: 21820  BIC: 21885  (Smaller is better. MC Std. Err. = 0)</code></pre>
</div>
</div>
<p>Of course, it could be that some <em>types</em> of clubs are more (or less) attractive foci for affiliation than others. In the two-mode ergm we can explore activity (popularity) differences across both modes, based on attributes, using the <code>b2factor</code> term:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1"></a>   <span class="fu">library</span>(ergm)</span>
<span id="cb20-2"><a href="#cb20-2"></a>   m3 <span class="ot">&lt;-</span> <span class="fu">ergm</span>(n <span class="sc">~</span> edges <span class="sc">+</span> <span class="fu">b1factor</span>(<span class="st">"gender"</span>, <span class="at">base =</span> <span class="dv">2</span>) </span>
<span id="cb20-3"><a href="#cb20-3"></a>              <span class="sc">+</span> <span class="fu">b1factor</span>(<span class="st">"race"</span>, <span class="at">base =</span> <span class="dv">5</span>)</span>
<span id="cb20-4"><a href="#cb20-4"></a>              <span class="sc">+</span> <span class="fu">b2factor</span>(<span class="st">"club_type_detailed"</span>, <span class="at">base =</span> <span class="dv">7</span>)</span>
<span id="cb20-5"><a href="#cb20-5"></a>              )</span>
<span id="cb20-6"><a href="#cb20-6"></a>   <span class="fu">summary</span>(m3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
ergm(formula = n ~ edges + b1factor("gender", base = 2) + b1factor("race", 
    base = 5) + b2factor("club_type_detailed", base = 7))

Maximum Likelihood Results:

                                                 Estimate Std. Error MCMC %
edges                                            -3.59928    0.05590      0
b1factor.gender.female                            0.33443    0.04372      0
b1factor.race.Asian                               0.06266    0.08899      0
b1factor.race.black                              -0.04860    0.04522      0
b1factor.race.Hispanic                            0.27204    0.13126      0
b1factor.race.Native American                     0.18435    0.22022      0
b2factor.club_type_detailed.Academic Competition  0.10037    0.08095      0
b2factor.club_type_detailed.Academic Interest     0.39981    0.06235      0
b2factor.club_type_detailed.Ethnic Interest      -0.73864    0.19258      0
b2factor.club_type_detailed.Individual Sports    -0.87056    0.08573      0
b2factor.club_type_detailed.Leadership           -0.51845    0.17432      0
b2factor.club_type_detailed.Media                -0.46324    0.14129      0
b2factor.club_type_detailed.Service               0.84615    0.06601      0
b2factor.club_type_detailed.Team Sports          -0.80973    0.07102      0
                                                 z value Pr(&gt;|z|)    
edges                                            -64.386  &lt; 1e-04 ***
b1factor.gender.female                             7.649  &lt; 1e-04 ***
b1factor.race.Asian                                0.704 0.481349    
b1factor.race.black                               -1.075 0.282422    
b1factor.race.Hispanic                             2.073 0.038212 *  
b1factor.race.Native American                      0.837 0.402524    
b2factor.club_type_detailed.Academic Competition   1.240 0.215012    
b2factor.club_type_detailed.Academic Interest      6.412  &lt; 1e-04 ***
b2factor.club_type_detailed.Ethnic Interest       -3.835 0.000125 ***
b2factor.club_type_detailed.Individual Sports    -10.155  &lt; 1e-04 ***
b2factor.club_type_detailed.Leadership            -2.974 0.002938 ** 
b2factor.club_type_detailed.Media                 -3.279 0.001043 ** 
b2factor.club_type_detailed.Service               12.818  &lt; 1e-04 ***
b2factor.club_type_detailed.Team Sports          -11.402  &lt; 1e-04 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

     Null Deviance: 116313  on 83902  degrees of freedom
 Residual Deviance:  21072  on 83888  degrees of freedom
 
AIC: 21100  BIC: 21231  (Smaller is better. MC Std. Err. = 0)</code></pre>
</div>
</div>
<p>Here we can see that there is statistically significant heterogeneity in the attractiveness of clubs as sources of affiliation. In comparison to the base category of art kid clubs (“Performance Arts”) we can see that all clubs are less popular except those based on service and academic pursuits.</p>
</section>
<section id="homophily-in-the-two-mode-case" class="level2">
<h2 class="anchored" data-anchor-id="homophily-in-the-two-mode-case">Homophily in the Two Mode Case</h2>
<p>Obviously, in the two-mode case, we can’t have “homophily” in the standard sense, since people can only connect to groups and groups and people different kind of things, so they can’t technically share attributes.</p>
<p>However, we can look at a different type of homophily and that is whether people tend to make affiliations with the <em>same kind</em> of groups, based on a group attribute.</p>
<p>That’s what the <code>b1nodematch</code> and <code>b2nodematch</code> ergm terms do. The first looks at whether people of the same kind tend to join the same group (number of two stars featuring a group as the focal node connected to two people of the same kind) and the second as to whether people tend to pick groups of the same kind (counts the number of two-stars with a person as the focal node and two groups that share the same attribute).</p>
<p>Let’s look at <code>b2nodematch</code> first:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1"></a>   <span class="fu">library</span>(ergm)</span>
<span id="cb22-2"><a href="#cb22-2"></a>   m4 <span class="ot">&lt;-</span> <span class="fu">ergm</span>(n <span class="sc">~</span> edges <span class="sc">+</span> <span class="fu">b1factor</span>(<span class="st">"gender"</span>, <span class="at">base =</span> <span class="dv">2</span>) </span>
<span id="cb22-3"><a href="#cb22-3"></a>              <span class="sc">+</span> <span class="fu">b1factor</span>(<span class="st">"race"</span>, <span class="at">base =</span> <span class="dv">5</span>)</span>
<span id="cb22-4"><a href="#cb22-4"></a>              <span class="sc">+</span> <span class="fu">b2factor</span>(<span class="st">"club_type_detailed"</span>, <span class="at">base =</span> <span class="dv">7</span>)</span>
<span id="cb22-5"><a href="#cb22-5"></a>              <span class="sc">+</span> <span class="fu">b2nodematch</span>(<span class="st">"club_type_detailed"</span>), </span>
<span id="cb22-6"><a href="#cb22-6"></a>              <span class="at">estimate =</span><span class="st">"MPLE"</span></span>
<span id="cb22-7"><a href="#cb22-7"></a>              )</span>
<span id="cb22-8"><a href="#cb22-8"></a>   <span class="fu">summary</span>(m4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
ergm(formula = n ~ edges + b1factor("gender", base = 2) + b1factor("race", 
    base = 5) + b2factor("club_type_detailed", base = 7) + b2nodematch("club_type_detailed"), 
    estimate = "MPLE")

Maximum Pseudolikelihood Results:

                                                 Estimate Std. Error MCMC %
edges                                            -3.82279    0.05862      0
b1factor.gender.female                            0.26310    0.04404      0
b1factor.race.Asian                               0.07010    0.08929      0
b1factor.race.black                              -0.03046    0.04534      0
b1factor.race.Hispanic                            0.26585    0.13179      0
b1factor.race.Native American                     0.15316    0.22157      0
b2factor.club_type_detailed.Academic Competition  0.22802    0.08150      0
b2factor.club_type_detailed.Academic Interest     0.37327    0.06256      0
b2factor.club_type_detailed.Ethnic Interest      -0.48387    0.19343      0
b2factor.club_type_detailed.Individual Sports    -0.70224    0.08660      0
b2factor.club_type_detailed.Leadership           -0.26526    0.17527      0
b2factor.club_type_detailed.Media                -0.22181    0.14238      0
b2factor.club_type_detailed.Service               0.87144    0.06631      0
b2factor.club_type_detailed.Team Sports          -0.72231    0.07135      0
b2nodematch.club_type_detailed                    0.41356    0.02513      0
                                                 z value Pr(&gt;|z|)    
edges                                            -65.217  &lt; 1e-04 ***
b1factor.gender.female                             5.974  &lt; 1e-04 ***
b1factor.race.Asian                                0.785  0.43238    
b1factor.race.black                               -0.672  0.50169    
b1factor.race.Hispanic                             2.017  0.04368 *  
b1factor.race.Native American                      0.691  0.48943    
b2factor.club_type_detailed.Academic Competition   2.798  0.00514 ** 
b2factor.club_type_detailed.Academic Interest      5.967  &lt; 1e-04 ***
b2factor.club_type_detailed.Ethnic Interest       -2.501  0.01237 *  
b2factor.club_type_detailed.Individual Sports     -8.109  &lt; 1e-04 ***
b2factor.club_type_detailed.Leadership            -1.513  0.13017    
b2factor.club_type_detailed.Media                 -1.558  0.11926    
b2factor.club_type_detailed.Service               13.141  &lt; 1e-04 ***
b2factor.club_type_detailed.Team Sports          -10.124  &lt; 1e-04 ***
b2nodematch.club_type_detailed                    16.457  &lt; 1e-04 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Warning:  The standard errors are based on naive pseudolikelihood and are suspect. Set control.ergm$MPLE.covariance.method='Godambe' for a simulation-based approximation of the standard errors.

     Null Pseudo-deviance: 116313  on 83902  degrees of freedom
 Residual Pseudo-deviance:  20832  on 83887  degrees of freedom
 
AIC: 20862  BIC: 21002  (Smaller is better. MC Std. Err. = 0)</code></pre>
</div>
</div>
<p>Which tells us, that indeed, when people select groups, they tend to select from within group buckets defined by club type.</p>
<p>Like before, we can check whether this tendency is the same across groups by specifying the argument <code>diff = TRUE</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1"></a>   <span class="fu">library</span>(ergm)</span>
<span id="cb24-2"><a href="#cb24-2"></a>   m5 <span class="ot">&lt;-</span> <span class="fu">ergm</span>(n <span class="sc">~</span> edges <span class="sc">+</span> <span class="fu">b1factor</span>(<span class="st">"gender"</span>, <span class="at">base =</span> <span class="dv">2</span>) </span>
<span id="cb24-3"><a href="#cb24-3"></a>              <span class="sc">+</span> <span class="fu">b1factor</span>(<span class="st">"race"</span>, <span class="at">base =</span> <span class="dv">5</span>)</span>
<span id="cb24-4"><a href="#cb24-4"></a>              <span class="sc">+</span> <span class="fu">b2factor</span>(<span class="st">"club_type_detailed"</span>, <span class="at">base =</span> <span class="dv">7</span>)</span>
<span id="cb24-5"><a href="#cb24-5"></a>              <span class="sc">+</span> <span class="fu">b2nodematch</span>(<span class="st">"club_type_detailed"</span>, <span class="at">diff =</span> <span class="cn">TRUE</span>, </span>
<span id="cb24-6"><a href="#cb24-6"></a>                            <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>, <span class="dv">8</span><span class="sc">:</span><span class="dv">9</span>)), </span>
<span id="cb24-7"><a href="#cb24-7"></a>              <span class="at">estimate =</span><span class="st">"MPLE"</span></span>
<span id="cb24-8"><a href="#cb24-8"></a>              )</span>
<span id="cb24-9"><a href="#cb24-9"></a>   <span class="fu">summary</span>(m5)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
ergm(formula = n ~ edges + b1factor("gender", base = 2) + b1factor("race", 
    base = 5) + b2factor("club_type_detailed", base = 7) + b2nodematch("club_type_detailed", 
    diff = TRUE, levels = c(1:6, 8:9)), estimate = "MPLE")

Maximum Pseudolikelihood Results:

                                                    Estimate Std. Error MCMC %
edges                                               -3.56597    0.05607      0
b1factor.gender.female                               0.27014    0.04474      0
b1factor.race.Asian                                  0.07597    0.09009      0
b1factor.race.black                                 -0.02116    0.04575      0
b1factor.race.Hispanic                               0.20642    0.13395      0
b1factor.race.Native American                        0.14636    0.22256      0
b2factor.club_type_detailed.Academic Competition    -0.66730    0.10792      0
b2factor.club_type_detailed.Academic Interest        0.38531    0.07094      0
b2factor.club_type_detailed.Ethnic Interest         -0.79386    0.19912      0
b2factor.club_type_detailed.Individual Sports       -0.98294    0.09399      0
b2factor.club_type_detailed.Leadership              -0.49734    0.17433      0
b2factor.club_type_detailed.Media                   -0.49065    0.14568      0
b2factor.club_type_detailed.Service                  0.44840    0.07811      0
b2factor.club_type_detailed.Team Sports             -0.90151    0.07930      0
b2nodematch.club_type_detailed.Academic Competition  1.20303    0.05720      0
b2nodematch.club_type_detailed.Academic Interest     0.02433    0.05680      0
b2nodematch.club_type_detailed.Ethnic Interest       1.52377    0.76157      0
b2nodematch.club_type_detailed.Individual Sports     0.47399    0.12795      0
b2nodematch.club_type_detailed.Leadership           -9.64287   86.14685      0
b2nodematch.club_type_detailed.Media                 0.49713    0.51260      0
b2nodematch.club_type_detailed.Service               0.62030    0.04885      0
b2nodematch.club_type_detailed.Team Sports           0.23752    0.08092      0
                                                    z value Pr(&gt;|z|)    
edges                                               -63.596  &lt; 1e-04 ***
b1factor.gender.female                                6.038  &lt; 1e-04 ***
b1factor.race.Asian                                   0.843 0.399046    
b1factor.race.black                                  -0.463 0.643663    
b1factor.race.Hispanic                                1.541 0.123317    
b1factor.race.Native American                         0.658 0.510771    
b2factor.club_type_detailed.Academic Competition     -6.183  &lt; 1e-04 ***
b2factor.club_type_detailed.Academic Interest         5.431  &lt; 1e-04 ***
b2factor.club_type_detailed.Ethnic Interest          -3.987  &lt; 1e-04 ***
b2factor.club_type_detailed.Individual Sports       -10.458  &lt; 1e-04 ***
b2factor.club_type_detailed.Leadership               -2.853 0.004333 ** 
b2factor.club_type_detailed.Media                    -3.368 0.000757 ***
b2factor.club_type_detailed.Service                   5.741  &lt; 1e-04 ***
b2factor.club_type_detailed.Team Sports             -11.368  &lt; 1e-04 ***
b2nodematch.club_type_detailed.Academic Competition  21.032  &lt; 1e-04 ***
b2nodematch.club_type_detailed.Academic Interest      0.428 0.668427    
b2nodematch.club_type_detailed.Ethnic Interest        2.001 0.045410 *  
b2nodematch.club_type_detailed.Individual Sports      3.704 0.000212 ***
b2nodematch.club_type_detailed.Leadership            -0.112 0.910875    
b2nodematch.club_type_detailed.Media                  0.970 0.332143    
b2nodematch.club_type_detailed.Service               12.698  &lt; 1e-04 ***
b2nodematch.club_type_detailed.Team Sports            2.935 0.003334 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Warning:  The standard errors are based on naive pseudolikelihood and are suspect. Set control.ergm$MPLE.covariance.method='Godambe' for a simulation-based approximation of the standard errors.

     Null Pseudo-deviance: 116313  on 83902  degrees of freedom
 Residual Pseudo-deviance:  20500  on 83880  degrees of freedom
 
AIC: 20544  BIC: 20750  (Smaller is better. MC Std. Err. = 0)</code></pre>
</div>
</div>
<p>The results show that compared to art kid clubs, “homophily” in club selection is stronger for Academic competiton, Service, and Individual sport clubs.</p>
<p>We can do the same to check out whether there is homophily on the people side. This tests hypotheses of the type: Do people with the same attributes tend to join the same clubs?</p>
<p>Here’s an example using racial identification:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1"></a>   <span class="fu">library</span>(ergm)</span>
<span id="cb26-2"><a href="#cb26-2"></a>   m6 <span class="ot">&lt;-</span> <span class="fu">ergm</span>(n <span class="sc">~</span> edges <span class="sc">+</span> <span class="fu">b1factor</span>(<span class="st">"gender"</span>, <span class="at">base =</span> <span class="dv">2</span>) </span>
<span id="cb26-3"><a href="#cb26-3"></a>              <span class="sc">+</span> <span class="fu">b1factor</span>(<span class="st">"race"</span>, <span class="at">base =</span> <span class="dv">5</span>)</span>
<span id="cb26-4"><a href="#cb26-4"></a>              <span class="sc">+</span> <span class="fu">b2factor</span>(<span class="st">"club_type_detailed"</span>, <span class="at">base =</span> <span class="dv">7</span>)</span>
<span id="cb26-5"><a href="#cb26-5"></a>              <span class="sc">+</span> <span class="fu">b1nodematch</span>(<span class="st">"race"</span>, <span class="at">diff =</span> <span class="cn">TRUE</span>, <span class="at">levels =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>),</span>
<span id="cb26-6"><a href="#cb26-6"></a>              <span class="at">estimate =</span><span class="st">"MPLE"</span></span>
<span id="cb26-7"><a href="#cb26-7"></a>              )</span>
<span id="cb26-8"><a href="#cb26-8"></a>   <span class="fu">summary</span>(m6)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
ergm(formula = n ~ edges + b1factor("gender", base = 2) + b1factor("race", 
    base = 5) + b2factor("club_type_detailed", base = 7) + b1nodematch("race", 
    diff = TRUE, levels = 1:4), estimate = "MPLE")

Maximum Pseudolikelihood Results:

                                                  Estimate Std. Error MCMC %
edges                                            -3.544174   0.055893      0
b1factor.gender.female                            0.341908   0.044110      0
b1factor.race.Asian                              -0.679353   0.124135      0
b1factor.race.black                              -0.553479   0.056490      0
b1factor.race.Hispanic                           -0.373579   0.175540      0
b1factor.race.Native American                    -0.185026   0.270507      0
b2factor.club_type_detailed.Academic Competition  0.123044   0.081117      0
b2factor.club_type_detailed.Academic Interest     0.292581   0.063349      0
b2factor.club_type_detailed.Ethnic Interest      -1.288069   0.225703      0
b2factor.club_type_detailed.Individual Sports    -0.788961   0.085917      0
b2factor.club_type_detailed.Leadership           -0.474640   0.174383      0
b2factor.club_type_detailed.Media                -0.397085   0.141393      0
b2factor.club_type_detailed.Service               0.513993   0.070547      0
b2factor.club_type_detailed.Team Sports          -0.724093   0.071205      0
b1nodematch.race.Asian                            0.212673   0.015707      0
b1nodematch.race.black                            0.033657   0.001801      0
b1nodematch.race.Hispanic                         0.520407   0.061182      0
b1nodematch.race.Native American                  0.726083   0.200975      0
                                                 z value Pr(&gt;|z|)    
edges                                            -63.410  &lt; 1e-04 ***
b1factor.gender.female                             7.751  &lt; 1e-04 ***
b1factor.race.Asian                               -5.473  &lt; 1e-04 ***
b1factor.race.black                               -9.798  &lt; 1e-04 ***
b1factor.race.Hispanic                            -2.128 0.033323 *  
b1factor.race.Native American                     -0.684 0.493978    
b2factor.club_type_detailed.Academic Competition   1.517 0.129297    
b2factor.club_type_detailed.Academic Interest      4.619  &lt; 1e-04 ***
b2factor.club_type_detailed.Ethnic Interest       -5.707  &lt; 1e-04 ***
b2factor.club_type_detailed.Individual Sports     -9.183  &lt; 1e-04 ***
b2factor.club_type_detailed.Leadership            -2.722 0.006492 ** 
b2factor.club_type_detailed.Media                 -2.808 0.004979 ** 
b2factor.club_type_detailed.Service                7.286  &lt; 1e-04 ***
b2factor.club_type_detailed.Team Sports          -10.169  &lt; 1e-04 ***
b1nodematch.race.Asian                            13.540  &lt; 1e-04 ***
b1nodematch.race.black                            18.687  &lt; 1e-04 ***
b1nodematch.race.Hispanic                          8.506  &lt; 1e-04 ***
b1nodematch.race.Native American                   3.613 0.000303 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Warning:  The standard errors are based on naive pseudolikelihood and are suspect. Set control.ergm$MPLE.covariance.method='Godambe' for a simulation-based approximation of the standard errors.

     Null Pseudo-deviance: 116313  on 83902  degrees of freedom
 Residual Pseudo-deviance:  20565  on 83884  degrees of freedom
 
AIC: 20601  BIC: 20769  (Smaller is better. MC Std. Err. = 0)</code></pre>
</div>
</div>
<p>Which shows that compared to white students, members of the same racialized minority category tend to be more likely to join the same group.</p>
</section>
<section id="conditining-on-degree" class="level2">
<h2 class="anchored" data-anchor-id="conditining-on-degree">Conditining on Degree</h2>
<p>Note that the models above only condition on the number of edges in the network (a two-mode version of the Erdos-Renyi model). So we may want to check whether any results regarding activity and homophily hold up against a more sophisticated null model, perhaps one that conditions on degree.</p>
<p>Note that in the two mode case we have two sets of degrees to worry about, the people and the groups, corresponding to the <code>gwb1degree</code> and <code>gwb2degree</code> geometrically weighted decay terms:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1"></a>   <span class="fu">library</span>(ergm)</span>
<span id="cb28-2"><a href="#cb28-2"></a>   m7 <span class="ot">&lt;-</span> <span class="fu">ergm</span>(n <span class="sc">~</span> edges </span>
<span id="cb28-3"><a href="#cb28-3"></a>              <span class="sc">+</span> <span class="fu">gwb1degree</span>(<span class="at">decay =</span> <span class="fl">0.25</span>, <span class="at">fixed =</span> <span class="cn">TRUE</span>)</span>
<span id="cb28-4"><a href="#cb28-4"></a>              <span class="sc">+</span> <span class="fu">gwb2degree</span>(<span class="at">decay =</span> <span class="fl">0.25</span>, <span class="at">fixed =</span> <span class="cn">TRUE</span>)</span>
<span id="cb28-5"><a href="#cb28-5"></a>              <span class="sc">+</span> <span class="fu">b1factor</span>(<span class="st">"gender"</span>, <span class="at">base =</span> <span class="dv">2</span>) </span>
<span id="cb28-6"><a href="#cb28-6"></a>              <span class="sc">+</span> <span class="fu">b1factor</span>(<span class="st">"race"</span>, <span class="at">base =</span> <span class="dv">5</span>)</span>
<span id="cb28-7"><a href="#cb28-7"></a>              <span class="sc">+</span> <span class="fu">b2factor</span>(<span class="st">"club_type_detailed"</span>, <span class="at">base =</span> <span class="dv">7</span>)</span>
<span id="cb28-8"><a href="#cb28-8"></a>              <span class="sc">+</span> <span class="fu">b1nodematch</span>(<span class="st">"race"</span>, <span class="at">diff =</span> <span class="cn">TRUE</span>, <span class="at">levels =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>),</span>
<span id="cb28-9"><a href="#cb28-9"></a>              <span class="at">estimate =</span><span class="st">"MPLE"</span></span>
<span id="cb28-10"><a href="#cb28-10"></a>              )</span>
<span id="cb28-11"><a href="#cb28-11"></a>   <span class="fu">summary</span>(m7)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
ergm(formula = n ~ edges + gwb1degree(decay = 0.25, fixed = TRUE) + 
    gwb2degree(decay = 0.25, fixed = TRUE) + b1factor("gender", 
    base = 2) + b1factor("race", base = 5) + b2factor("club_type_detailed", 
    base = 7) + b1nodematch("race", diff = TRUE, levels = 1:4), 
    estimate = "MPLE")

Maximum Pseudolikelihood Results:

                                                   Estimate Std. Error MCMC %
edges                                             -3.241289   0.058868      0
gwb1deg.fixed.0.25                                -1.419093   0.087824      0
gwb2deg.fixed.0.25                               -53.587909  55.867644      0
b1factor.gender.female                             0.240393   0.044445      0
b1factor.race.Asian                               -0.688534   0.124691      0
b1factor.race.black                               -0.541557   0.056688      0
b1factor.race.Hispanic                            -0.488329   0.176411      0
b1factor.race.Native American                     -0.168338   0.272995      0
b2factor.club_type_detailed.Academic Competition   0.108630   0.082188      0
b2factor.club_type_detailed.Academic Interest      0.282413   0.064644      0
b2factor.club_type_detailed.Ethnic Interest       -1.318605   0.227371      0
b2factor.club_type_detailed.Individual Sports     -0.795388   0.086082      0
b2factor.club_type_detailed.Leadership            -0.492344   0.175090      0
b2factor.club_type_detailed.Media                 -0.413327   0.142185      0
b2factor.club_type_detailed.Service                0.501474   0.071752      0
b2factor.club_type_detailed.Team Sports           -0.738812   0.072287      0
b1nodematch.race.Asian                             0.218717   0.015995      0
b1nodematch.race.black                             0.034394   0.001829      0
b1nodematch.race.Hispanic                          0.531126   0.061868      0
b1nodematch.race.Native American                   0.801330   0.206123      0
                                                 z value Pr(&gt;|z|)    
edges                                            -55.060  &lt; 1e-04 ***
gwb1deg.fixed.0.25                               -16.158  &lt; 1e-04 ***
gwb2deg.fixed.0.25                                -0.959 0.337461    
b1factor.gender.female                             5.409  &lt; 1e-04 ***
b1factor.race.Asian                               -5.522  &lt; 1e-04 ***
b1factor.race.black                               -9.553  &lt; 1e-04 ***
b1factor.race.Hispanic                            -2.768 0.005638 ** 
b1factor.race.Native American                     -0.617 0.537477    
b2factor.club_type_detailed.Academic Competition   1.322 0.186264    
b2factor.club_type_detailed.Academic Interest      4.369  &lt; 1e-04 ***
b2factor.club_type_detailed.Ethnic Interest       -5.799  &lt; 1e-04 ***
b2factor.club_type_detailed.Individual Sports     -9.240  &lt; 1e-04 ***
b2factor.club_type_detailed.Leadership            -2.812 0.004924 ** 
b2factor.club_type_detailed.Media                 -2.907 0.003650 ** 
b2factor.club_type_detailed.Service                6.989  &lt; 1e-04 ***
b2factor.club_type_detailed.Team Sports          -10.221  &lt; 1e-04 ***
b1nodematch.race.Asian                            13.674  &lt; 1e-04 ***
b1nodematch.race.black                            18.806  &lt; 1e-04 ***
b1nodematch.race.Hispanic                          8.585  &lt; 1e-04 ***
b1nodematch.race.Native American                   3.888 0.000101 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Warning:  The standard errors are based on naive pseudolikelihood and are suspect. Set control.ergm$MPLE.covariance.method='Godambe' for a simulation-based approximation of the standard errors.

     Null Pseudo-deviance: 116313  on 83902  degrees of freedom
 Residual Pseudo-deviance:  20198  on 83882  degrees of freedom
 
AIC: 20238  BIC: 20425  (Smaller is better. MC Std. Err. = 0)</code></pre>
</div>
</div>
<p>Which shows that our results hold up even after accounting for degree-heterogeneity at the graph level.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>