{
  "hash": "ee6366a4c0c12f2eefe3d6169f26609a",
  "result": {
    "markdown": "---\ntitle: \"Graph Ensembles in Two-Mode Networks\"\nexecute: \n  eval: true\n  echo: true\n  output: true\n  warning: false\n  message: false\nformat: \n   html:\n      code-line-numbers: true\n---\n\n\nAs we saw in the [graph ensemble lesson](swap.qmd), there are many approaches to randomizing the structure of one-mode networks when the aim is to create **graph ensembles** preserving selected properties. These ensembles, in turn, can be used to do **null hypothesis testing** in networks. \n\nNot surprisingly, a similar suite of techniques exist for the two-mode case, but until recently various approaches were scattered (and reduplicated) across a bunch of literatures in social network analysis, ecology, network physics, and  computer science [@neal_etal24]. \n\n## Two-Mode Erdos-Renyi Model\n\nLike with one-mode networks, the simplest null model for two-mode networks is one that preserves the number of nodes and the number of edges. This model, like we saw in the one-mode network case, also preserves anything that is a function of these two-quantities. In the two-mode case, this is the bipartite graph's **density** and the average degrees of the nodes in each mode (recall that two-mode networks [have two average degrees](two-mode.qmd)). This is thus a two-mode version of the **Erdos-Renyi** null model. \n\nLet's load up the *Southern Women* (SW) data and see how it works:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n   library(igraph)\n   library(networkdata)\n   A <- as_biadjacency_matrix(southern_women)\n```\n:::\n\n\nLet's compute some basic network statistics:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n   d <- sum(A)/(nrow(A)*ncol(A)) #density\n   ad.p <- mean(rowSums(A)) #average degree of people\n   ad.g <- mean(colSums(A)) #average degree of groups\n   d\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.3531746\n```\n:::\n\n```{.r .cell-code}\n   ad.p\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 4.944444\n```\n:::\n\n```{.r .cell-code}\n   ad.g\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 6.357143\n```\n:::\n:::\n\n\nWe can see that the density of the SW network is $d=$ 0.35, the average degree of people $\\bar{k_p}=$ 4.94 and the average degree of groups $\\bar{k_g}=$ 6.36.  \n\nNow, let's compute something on this network, like the **degree correlation** between people and groups, answering  the question: Do people with lots of memberships tend to join larger groups?\n\nFirst let's create an edge list data frame with the incident nodes' degrees as the two main columns and compute the correlation between the respective degrees:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n   v.a <- as.vector(A) #adjacency relations\n   rd <- rep(rowSums(A), ncol(A)) #row degrees\n   cd <- rep(colSums(A), each = nrow(A)) #column degrees\n   d <- data.frame(e = v.a, rd =  rd, cd = cd)\n   cor(d[d$e == 1, ]$rd, d[d$e == 1, ]$cd) #degree correlation among adjacent nodes\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] -0.2783186\n```\n:::\n:::\n\n\nWhich is negative, suggesting **degree anti-correlation** in this network (people with lots of memberships tend to belong to smaller groups). \n\nIs this value statistically significant net of the network density? To find out, we need to create a two-mode **graph ensemble** of networks with the same density, number of persons, and number of groups as SW. \n\nBefore we get to that, let's package the steps above into a two-mode degree correlation function:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n   tm.deg.corr <- function(x) {\n      d <- data.frame(e = as.vector(x), \n                      rd = rep(rowSums(x), ncol(x)), \n                      cd = rep(colSums(x), each = nrow(x)))\n      return(cor(d[d$e == 1, ]$rd, d[d$e == 1, ]$cd))\n   }\n```\n:::\n\n\nThis function takes the biadjacency matrix as input, and returns the correlations between the degrees of nodes in each mode. \n\nOK, now back to generating an Erdos-Renyi two-mode network. A simple approach goes like this: \n\nFirst, let's create a vectorized version of the adjacency matrix:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n   v.a <- as.vector(A)\n   v.a\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  [1] 1 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1\n [38] 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1\n [75] 1 1 1 1 1 0 1 0 0 0 0 0 0 0 0 0 1 1 1 1 0 1 1 1 0 0 0 0 0 1 0 0 0 0 0 1 1\n[112] 1 1 0 1 0 1 1 0 0 1 1 1 0 0 0 1 1 1 1 0 1 1 1 1 1 1 1 1 0 1 1 0 0 1 0 1 0\n[149] 0 0 0 1 1 1 1 1 1 1 0 1 1 1 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0\n[186] 0 0 0 0 0 0 0 0 1 1 0 1 1 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0\n[223] 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0\n```\n:::\n:::\n\n\nThese are just the biadjacency matrix entries stretched out into a long vector of length equal to the number of rows multiplied by the number of columns of the matrix (18 $\\times$ 14 $=$ 252). \n\nThen we just reshuffle the values of this vector by reassigning vector positions across the entire length of the vector at random:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n   v.shuff <- v.a[sample(1:length(v.a))]\n```\n:::\n\n\nNow we can just generate a new biadjacency matrix `A.perm` from the reshuffled vector `v.shuff`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n   A.perm <- matrix(v.shuff, nrow = nrow(A)) #creating permuted biadjacency matrix\n   rownames(A.perm) <- rownames(A)\n   colnames(A.perm) <- colnames(A)\n   A.perm\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n          6/27 3/2 4/12 9/26 2/25 5/19 3/15 9/16 4/8 6/10 2/23 4/7 11/21 8/3\nEVELYN       0   1    0    1    0    0    1    0   1    1    1   0     0   0\nLAURA        0   1    0    0    0    1    1    1   0    0    0   1     0   0\nTHERESA      0   1    0    0    0    1    0    1   0    1    1   1     0   0\nBRENDA       0   1    1    0    1    0    0    0   1    1    0   0     0   1\nCHARLOTTE    0   0    0    0    1    1    1    0   0    1    1   0     1   1\nFRANCES      0   0    0    0    0    1    0    0   1    0    0   1     0   1\nELEANOR      1   0    1    1    1    1    1    0   1    0    0   0     0   1\nPEARL        1   0    1    1    0    0    0    0   1    1    0   0     0   0\nRUTH         0   0    1    1    1    0    1    0   1    0    1   0     1   0\nVERNE        0   0    0    1    0    0    0    0   0    0    0   0     0   0\nMYRNA        1   0    1    0    1    0    0    1   1    0    1   0     0   1\nKATHERINE    0   1    0    0    0    0    0    0   0    0    1   0     1   1\nSYLVIA       1   0    0    0    0    1    1    1   0    1    0   0     0   0\nNORA         0   1    0    1    0    1    1    0   0    0    0   0     0   0\nHELEN        0   0    0    0    0    0    0    1   0    0    1   0     0   0\nDOROTHY      1   0    0    0    0    0    0    0   0    0    1   0     1   0\nOLIVIA       0   0    1    0    0    0    0    0   1    1    0   1     0   1\nFLORA        0   0    0    0    0    1    0    0   1    1    0   1     0   0\n```\n:::\n:::\n\n\nWe can verify that `A.perm` has the same basic network statistics as `A`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n   d <- sum(A.perm)/(nrow(A.perm)*ncol(A.perm)) #density\n   ad.p <- mean(rowSums(A.perm)) #average degree of people\n   ad.g <- mean(colSums(A.perm)) #average degree of groups\n   d\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.3531746\n```\n:::\n\n```{.r .cell-code}\n   ad.p\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 4.944444\n```\n:::\n\n```{.r .cell-code}\n   ad.g\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 6.357143\n```\n:::\n:::\n\n\nBut *not* the same degree distributions:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n   rowSums(A)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   EVELYN     LAURA   THERESA    BRENDA CHARLOTTE   FRANCES   ELEANOR     PEARL \n        8         7         8         7         4         4         4         3 \n     RUTH     VERNE     MYRNA KATHERINE    SYLVIA      NORA     HELEN   DOROTHY \n        4         4         4         6         7         8         5         2 \n   OLIVIA     FLORA \n        2         2 \n```\n:::\n\n```{.r .cell-code}\n   rowSums(A.perm)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   EVELYN     LAURA   THERESA    BRENDA CHARLOTTE   FRANCES   ELEANOR     PEARL \n        6         5         6         6         7         4         8         5 \n     RUTH     VERNE     MYRNA KATHERINE    SYLVIA      NORA     HELEN   DOROTHY \n        7         1         7         4         5         4         2         3 \n   OLIVIA     FLORA \n        5         4 \n```\n:::\n\n```{.r .cell-code}\n   colSums(A)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n 6/27   3/2  4/12  9/26  2/25  5/19  3/15  9/16   4/8  6/10  2/23   4/7 11/21 \n    3     3     6     4     8     8    10    14    12     5     4     6     3 \n  8/3 \n    3 \n```\n:::\n\n```{.r .cell-code}\n   colSums(A.perm)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n 6/27   3/2  4/12  9/26  2/25  5/19  3/15  9/16   4/8  6/10  2/23   4/7 11/21 \n    5     6     6     6     5     8     7     5     9     8     8     5     4 \n  8/3 \n    7 \n```\n:::\n:::\n\n\nWe can now package the two-mode permutation steps into a function called `tm.perm`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n   tm.perm <- function(x) {\n      v.a <- as.vector(x)\n      v.s <- v.a[sample(1:length(v.a))]\n      w <- matrix(v.s, nrow = nrow(x))\n      rownames(w) <- rownames(x)\n      colnames(w) <- colnames(x)\n      return(w)\n   }\n```\n:::\n\n\nAnd generate a 500 strong Erdos-Renyi graph ensemble for the SW data:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n   set.seed(4567)\n   G <- replicate(500, tm.perm(A), simplify = FALSE)\n```\n:::\n\n\nWe can now `sapply` the `tm.deg.corr` function from before across our ensemble to get 500 degree correlations:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n   corrs <- sapply(G, tm.deg.corr)\n   corrs[1:100] #first hundred entries\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  [1] -0.181068203 -0.028314100  0.188798665 -0.164612262 -0.046365539\n  [6] -0.117754101 -0.111534437  0.031349320 -0.166265165 -0.109026429\n [11] -0.063007761  0.035804196 -0.093016920 -0.008386071 -0.116197236\n [16] -0.120114305 -0.127791616 -0.051316368 -0.179359174 -0.169231258\n [21] -0.072542931 -0.109965295 -0.077388567 -0.086158870 -0.070277167\n [26] -0.040457937 -0.191663455 -0.051744760  0.017962735 -0.062511337\n [31] -0.140546077 -0.180194592 -0.074843653 -0.015082985 -0.130821828\n [36] -0.040472998  0.059572901 -0.085852479  0.025473457 -0.023345432\n [41] -0.075236000 -0.085682500 -0.043660481  0.057020861 -0.079154999\n [46]  0.113252420 -0.133612519 -0.108477373 -0.081678899  0.084910633\n [51]  0.098588342 -0.112577719 -0.040747607  0.095056504  0.051027047\n [56]  0.002563878 -0.038096975 -0.080671796 -0.062014599 -0.064015988\n [61]  0.061467130  0.015000308 -0.063111868 -0.139627092  0.023332867\n [66] -0.027933756 -0.036593341 -0.049240244 -0.130301946  0.040592725\n [71] -0.136314003 -0.051252491  0.038112132  0.001781197  0.049331912\n [76] -0.082950723 -0.120608238 -0.085908704  0.073822120 -0.058662697\n [81] -0.088400011 -0.127457896  0.042472937 -0.094378753 -0.025708298\n [86]  0.040868238 -0.108797377 -0.089105995 -0.127387349  0.007556992\n [91] -0.029442970  0.120221999 -0.157639066 -0.107269116 -0.061072459\n [96] -0.130828870 -0.157198707 -0.093604225 -0.187877666  0.097223042\n```\n:::\n:::\n\n\nSo let's see how our observed value stacks up in the grand scheme:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n   library(ggplot2)\n   p <- ggplot(data = data.frame(round(corrs, 2)), aes(x = corrs))\n   p <- p + geom_histogram(binwidth = 0.015, stat = \"bin\", fill = \"darkblue\")\n   p <- p + geom_vline(xintercept = tm.deg.corr(A), \n                       color = \"red\", linetype = 1, linewidth = 1.5)\n   p <- p + geom_vline(xintercept = 0, linetype = 1, \n                       color = \"purple\", linewidth = 1.5)\n   p <- p + theme_minimal() + labs(x = \"Q by Level\", y = \"Freq.\")\n   p <- p + theme(axis.text = element_text(size = 12))\n   p <- p + annotate(\"text\", x=-0.04, y=45, label= \"Zero Point\", color = \"purple\")\n   p <- p + annotate(\"text\", x=-0.23, y=45, label= \"Obs. Value\", color = \"red\")\n   p\n```\n\n::: {.cell-output-display}\n![](tm-null_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n\nIt looks like our observed value is close to the tail end of the negative spectrum, suggesting it is statistically improbable to have been obvserved by chance. We can compute the value that corresponds to the 1st percentile of the assortativity distribution from the ensemble and then see if what observe is below that value ($p < 0.01$). \n\n\n::: {.cell}\n\n```{.r .cell-code}\n   quantile(corrs, probs = 0.01)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n        1% \n-0.2602561 \n```\n:::\n\n```{.r .cell-code}\n   tm.deg.corr(A) < quantile(corrs, probs = 0.01)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  1% \nTRUE \n```\n:::\n:::\n\n\nWhich is definitely true in this null graph ensemble, suggesting that degree anti-correlation is present in the SW data, at statistically significant levels, net of density. \n\nAs before, if we wanted a more stringent two-tailed we would need to create a vector with the *absolute value* of the two-mode degree correlation: \n\n\n::: {.cell}\n\n```{.r .cell-code}\n   1 - ecdf(abs(corrs))(abs(tm.deg.corr(A)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.004\n```\n:::\n:::\n\n\nWhich is still statistically significant at conventional levels. \n\n## Fixed Degree Models\nAs we already noted, the two-mode Erdos-Renyi model fixes the number of edges (and thus the density and average degrees) in the network, but does not preserve the original degree distributions. We might want to test our hypotheses by using a two-mode graph ensemble that \"controls for\" the node degrees. \n\nHow do we do that? One complication is that we have two sets of degrees so we have more options than in the one mode case. We can fix the row (person) degree, or the column (group) degree or *both* degrees. \n\nLet's begin with the simplest case, in which we fix *either* the row or column degree but not both. \n\n### Fixing Row Degrees\n\nTo fix the row degrees, we need to randomize the entries in each row of the biadjacency matrix, while preserving the number of ones in that row. One way to do this is to write a function that takes an observed row of the matrix, randomizes it and then substitutes it for the observed row:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n   rand.row <- function(r) {\n      return(r[sample(1:length(r))])\n      }\n```\n:::\n\n\nNow we can just `apply` the `rand.row` function to each row of the biadjacency matrix `A` to generate a new matrix `A.r`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n   A.r <- apply(A, 1, rand.row)\n   A.r <- t(A.r)\n   rownames(A.r) <- rownames(A)\n   colnames(A.r) <- colnames(A)\n```\n:::\n\n\nHere's the original matrix `A`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n   A\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n          6/27 3/2 4/12 9/26 2/25 5/19 3/15 9/16 4/8 6/10 2/23 4/7 11/21 8/3\nEVELYN       1   1    1    1    1    1    0    1   1    0    0   0     0   0\nLAURA        1   1    1    0    1    1    1    1   0    0    0   0     0   0\nTHERESA      0   1    1    1    1    1    1    1   1    0    0   0     0   0\nBRENDA       1   0    1    1    1    1    1    1   0    0    0   0     0   0\nCHARLOTTE    0   0    1    1    1    0    1    0   0    0    0   0     0   0\nFRANCES      0   0    1    0    1    1    0    1   0    0    0   0     0   0\nELEANOR      0   0    0    0    1    1    1    1   0    0    0   0     0   0\nPEARL        0   0    0    0    0    1    0    1   1    0    0   0     0   0\nRUTH         0   0    0    0    1    0    1    1   1    0    0   0     0   0\nVERNE        0   0    0    0    0    0    1    1   1    0    0   1     0   0\nMYRNA        0   0    0    0    0    0    0    1   1    1    0   1     0   0\nKATHERINE    0   0    0    0    0    0    0    1   1    1    0   1     1   1\nSYLVIA       0   0    0    0    0    0    1    1   1    1    0   1     1   1\nNORA         0   0    0    0    0    1    1    0   1    1    1   1     1   1\nHELEN        0   0    0    0    0    0    1    1   0    1    1   1     0   0\nDOROTHY      0   0    0    0    0    0    0    1   1    0    0   0     0   0\nOLIVIA       0   0    0    0    0    0    0    0   1    0    1   0     0   0\nFLORA        0   0    0    0    0    0    0    0   1    0    1   0     0   0\n```\n:::\n:::\n\n\nAnd the reshuffled matrix `A.r`\n\n\n::: {.cell}\n\n```{.r .cell-code}\n   A.r\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n          6/27 3/2 4/12 9/26 2/25 5/19 3/15 9/16 4/8 6/10 2/23 4/7 11/21 8/3\nEVELYN       1   0    0    1    0    1    1    1   1    0    1   0     0   1\nLAURA        0   0    1    1    1    0    0    0   1    0    1   1     0   1\nTHERESA      1   0    1    0    0    1    0    1   1    0    1   1     0   1\nBRENDA       0   1    1    0    1    0    1    0   0    1    0   0     1   1\nCHARLOTTE    0   0    1    0    0    0    0    0   1    1    1   0     0   0\nFRANCES      0   1    0    1    0    0    1    1   0    0    0   0     0   0\nELEANOR      0   0    0    0    0    0    1    0   0    1    1   0     0   1\nPEARL        0   0    0    0    1    0    0    0   1    1    0   0     0   0\nRUTH         0   0    0    0    0    1    0    1   0    1    0   0     0   1\nVERNE        0   0    0    0    1    1    0    1   0    0    0   0     1   0\nMYRNA        1   1    0    0    0    0    1    1   0    0    0   0     0   0\nKATHERINE    0   1    1    0    0    1    0    0   0    0    1   0     1   1\nSYLVIA       1   0    0    0    1    0    0    1   1    1    1   0     0   1\nNORA         1   1    0    1    1    1    0    1   0    1    0   0     1   0\nHELEN        0   0    1    0    1    1    0    0   0    1    0   0     0   1\nDOROTHY      1   0    0    0    0    0    0    0   0    1    0   0     0   0\nOLIVIA       0   1    0    0    0    0    0    0   0    1    0   0     0   0\nFLORA        0   0    0    0    0    0    0    0   0    0    0   1     0   1\n```\n:::\n:::\n\n\nNote that the new matrix `A.r` preserves the person degrees of the original:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n   rowSums(A)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   EVELYN     LAURA   THERESA    BRENDA CHARLOTTE   FRANCES   ELEANOR     PEARL \n        8         7         8         7         4         4         4         3 \n     RUTH     VERNE     MYRNA KATHERINE    SYLVIA      NORA     HELEN   DOROTHY \n        4         4         4         6         7         8         5         2 \n   OLIVIA     FLORA \n        2         2 \n```\n:::\n\n```{.r .cell-code}\n   rowSums(A.r)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   EVELYN     LAURA   THERESA    BRENDA CHARLOTTE   FRANCES   ELEANOR     PEARL \n        8         7         8         7         4         4         4         3 \n     RUTH     VERNE     MYRNA KATHERINE    SYLVIA      NORA     HELEN   DOROTHY \n        4         4         4         6         7         8         5         2 \n   OLIVIA     FLORA \n        2         2 \n```\n:::\n:::\n\n\nBut not the group degrees, because each person's memberships are randomly distributed across groups:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n   colSums(A)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n 6/27   3/2  4/12  9/26  2/25  5/19  3/15  9/16   4/8  6/10  2/23   4/7 11/21 \n    3     3     6     4     8     8    10    14    12     5     4     6     3 \n  8/3 \n    3 \n```\n:::\n\n```{.r .cell-code}\n   colSums(A.r)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n 6/27   3/2  4/12  9/26  2/25  5/19  3/15  9/16   4/8  6/10  2/23   4/7 11/21 \n    6     6     6     4     7     7     5     8     6    10     7     3     4 \n  8/3 \n   10 \n```\n:::\n:::\n\n\nAll the other lower order statistics like density are preserved:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n   sum(A.r)/(nrow(A.r)*ncol(A.r))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.3531746\n```\n:::\n:::\n\n\nNow we package everything into a function:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n   fix.deg <- function(x, mode = 1) {\n      w <- apply(x, mode, function(r) {r[sample(1:length(r))]})\n      if (mode == 1) {\n         w <- t(w)\n         }\n      rownames(w) <- rownames(x)\n      colnames(w) <- colnames(x)\n      return(w)\n      }\n```\n:::\n\n\nWe then generate a graph ensemble of reshuffled matrices that preserve the person degrees, and compute our degree correlations in that set of networks:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n   set.seed(4567)\n   G <- replicate(500, fix.deg(A), simplify = FALSE)\n   corrs <- sapply(G, tm.deg.corr)\n```\n:::\n\n\nLet's compute the degree correlations across this ensemble and see how our observed value stacks up in the grand scheme:\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](tm-null_files/figure-html/unnamed-chunk-25-1.png){width=672}\n:::\n:::\n\n\nLooking pretty good! Let's check the p-value:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n   quantile(corrs, probs = 0.01)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n        1% \n-0.2869344 \n```\n:::\n\n```{.r .cell-code}\n   tm.deg.corr(A) < quantile(corrs, probs = 0.01)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   1% \nFALSE \n```\n:::\n\n```{.r .cell-code}\n   1 - ecdf(abs(corrs))(abs(tm.deg.corr(A)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.012\n```\n:::\n:::\n\n\nNote that our result is no longer statistically significant at the $p <0.01$ level, but it can be defended at the $p < 0.05$ level. Still a chance of getting published.\n\n### Fixing Column Degrees\nWe can fix the column degrees using the same `fix.deg` function as earlier, but this time, we just change the `mode` argument to equal `2`, to `apply` the function to the columns and not the rows of the matrix `A`. \n\nFor instance:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n   A.c <- fix.deg(A, mode = 2)\n   A.c\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n          6/27 3/2 4/12 9/26 2/25 5/19 3/15 9/16 4/8 6/10 2/23 4/7 11/21 8/3\nEVELYN       0   1    0    1    1    1    1    0   1    0    1   1     0   0\nLAURA        0   0    1    0    0    0    1    1   1    0    0   0     0   0\nTHERESA      0   1    0    1    1    0    0    1   1    1    0   0     0   0\nBRENDA       0   0    1    0    0    1    0    1   0    0    1   1     1   0\nCHARLOTTE    0   0    0    0    0    1    0    1   1    0    0   0     0   0\nFRANCES      0   1    0    0    1    0    1    1   1    1    0   0     1   0\nELEANOR      0   0    0    0    0    0    1    0   0    1    1   0     0   0\nPEARL        0   0    0    0    0    0    0    0   1    1    0   0     0   0\nRUTH         0   0    0    0    1    0    0    1   1    0    0   0     0   0\nVERNE        1   0    1    0    1    1    1    1   1    0    0   1     0   1\nMYRNA        0   0    1    0    1    1    1    1   0    0    0   0     0   0\nKATHERINE    1   0    0    1    0    0    1    1   1    0    0   1     1   0\nSYLVIA       0   0    0    0    1    0    1    1   1    1    0   0     0   0\nNORA         1   0    1    0    1    0    1    1   0    0    0   0     0   0\nHELEN        0   0    0    0    0    1    0    1   1    0    0   1     0   1\nDOROTHY      0   0    0    0    0    1    0    0   0    0    1   0     0   0\nOLIVIA       0   0    0    0    0    1    1    1   1    0    0   0     0   0\nFLORA        0   0    1    1    0    0    0    1   0    0    0   1     0   1\n```\n:::\n:::\n\n\nWhich generates a reshuffled adjacency matrix that preserves the group degrees:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n   colSums(A)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n 6/27   3/2  4/12  9/26  2/25  5/19  3/15  9/16   4/8  6/10  2/23   4/7 11/21 \n    3     3     6     4     8     8    10    14    12     5     4     6     3 \n  8/3 \n    3 \n```\n:::\n\n```{.r .cell-code}\n   colSums(A.c)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n 6/27   3/2  4/12  9/26  2/25  5/19  3/15  9/16   4/8  6/10  2/23   4/7 11/21 \n    3     3     6     4     8     8    10    14    12     5     4     6     3 \n  8/3 \n    3 \n```\n:::\n:::\n\n\nBut *not* the person degrees:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n   rowSums(A)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   EVELYN     LAURA   THERESA    BRENDA CHARLOTTE   FRANCES   ELEANOR     PEARL \n        8         7         8         7         4         4         4         3 \n     RUTH     VERNE     MYRNA KATHERINE    SYLVIA      NORA     HELEN   DOROTHY \n        4         4         4         6         7         8         5         2 \n   OLIVIA     FLORA \n        2         2 \n```\n:::\n\n```{.r .cell-code}\n   rowSums(A.c)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   EVELYN     LAURA   THERESA    BRENDA CHARLOTTE   FRANCES   ELEANOR     PEARL \n        8         4         6         6         3         7         3         2 \n     RUTH     VERNE     MYRNA KATHERINE    SYLVIA      NORA     HELEN   DOROTHY \n        3         9         5         7         5         5         5         2 \n   OLIVIA     FLORA \n        4         5 \n```\n:::\n:::\n\n\nAnd now we test our hypothesis that there is degree anti-correlation in the SW data on an ensemble of graphs with fixed group degrees:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n   set.seed(4567)\n   G <- replicate(500, fix.deg(A, mode = 2), simplify = FALSE)\n   corrs <- sapply(G, tm.deg.corr)\n```\n:::\n\n\nLet's see how things look:\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](tm-null_files/figure-html/unnamed-chunk-31-1.png){width=672}\n:::\n:::\n\n\nUh oh, adjusting for group degrees seems to have made our conclusions a bit more shaky. Let' see:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n   quantile(corrs, probs = 0.01)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n        1% \n-0.3039788 \n```\n:::\n\n```{.r .cell-code}\n   tm.deg.corr(A) < quantile(corrs, probs = 0.01)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   1% \nFALSE \n```\n:::\n\n```{.r .cell-code}\n   1 - ecdf(abs(corrs))(abs(tm.deg.corr(A)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.028\n```\n:::\n:::\n\n\nStill significant at $p < 0.05$! \n\nRegardless, it is clear that our earlier conclusions from the Erdos-Renyi model were a bit too optimistic. What happens when we try to fix *both* the row and column degrees?\n\n### Fixing Row and Column Degrees\nTo fix row and column degrees, we play a swapping game. At each round, we select two random persons $a$ and $b$. Each person collects their memberships and calculates the memberships they have that the other person does not have (and vice versa). Thus, $a$ has a set of memberships that $b$ does not have, and $b$ has a set of memberships that $a$ does not have. Then they trade memberships $n$ times where $n$ is a number between zero and the minimum of the size of the two sets of memberships that the other person does not have. We repeat this trading game for $k$ number of times. \n\nBelow is a function called `make.swap` that implements this algorithm, called \"curveball\" [@neal_etal24]. The function takes the biadjacency matrix as input and repeats the process described above 500 times:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n   make.swap <- function(x, k = 100) {\n      z <- 1 #initializing counter\n      while(z <= k) {\n         n <- sample(rownames(x), 2) #sampling two people at random\n         a <- n[1] #person a\n         b <- n[2] #person b\n         a.m <- names(which(x[a, ] == 1)) #person a's memberships\n         b.m <- names(which(x[b, ] == 1)) #person b's memberships\n         ab <- setdiff(a.m, b.m) #memberships that a has that b does not\n         ba <- setdiff(b.m, a.m) #memberships that b has that a does not\n         w <- sample(0:min(length(ab), length(ba)), size = 1) #number of rounds of trade\n         if (w > 0) {\n            for (i in 1:w) {\n               ab.m <- sample(ab, 1) #membership that a will transfer to b\n               ba.m <- sample(ba, 1) #membership that b will transfer to a\n               x[a, ab.m] <- 0 #a loses membership\n               x[b, ab.m] <- 1 #b gains membership\n               x[b, ba.m] <- 0 #b loses membership\n               x[a, ba.m] <- 1 #a gains membership\n               a.m <- names(which(x[a, ] == 1)) #updating a's memberships\n               b.m <- names(which(x[b, ] == 1)) #updating b's memberships\n               ab <- setdiff(a.m, b.m) #updating differences between a and b's memberships\n               ba <- setdiff(b.m, a.m) #updating differences between b and a's memberships\n               }\n            }\n         z <- z + 1 #incrementing counter\n         }\n      return(x)\n   }\n```\n:::\n\n\nHere's an example:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n   A.s <- make.swap(A)\n   A.s\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n          6/27 3/2 4/12 9/26 2/25 5/19 3/15 9/16 4/8 6/10 2/23 4/7 11/21 8/3\nEVELYN       0   0    1    0    0    0    1    1   1    0    1   1     1   1\nLAURA        0   1    1    0    1    1    0    1   1    0    0   1     0   0\nTHERESA      1   0    0    1    0    1    1    1   1    1    0   0     1   0\nBRENDA       0   0    1    0    0    1    1    1   1    1    1   0     0   0\nCHARLOTTE    0   1    0    0    0    0    1    1   0    0    0   0     0   1\nFRANCES      0   0    1    0    1    1    0    0   1    0    0   0     0   0\nELEANOR      0   0    0    0    1    0    1    1   1    0    0   0     0   0\nPEARL        0   0    0    0    0    0    1    0   1    0    0   1     0   0\nRUTH         0   0    0    1    1    0    1    1   0    0    0   0     0   0\nVERNE        1   0    0    0    0    0    0    1   0    0    0   1     0   1\nMYRNA        0   0    0    0    0    1    1    1   0    1    0   0     0   0\nKATHERINE    0   0    1    1    0    1    1    1   1    0    0   0     0   0\nSYLVIA       0   1    1    0    1    1    0    0   1    0    1   0     1   0\nNORA         1   0    0    1    1    0    1    1   1    1    0   1     0   0\nHELEN        0   0    0    0    1    0    0    1   1    1    0   1     0   0\nDOROTHY      0   0    0    0    1    0    0    0   1    0    0   0     0   0\nOLIVIA       0   0    0    0    0    0    0    1   0    0    1   0     0   0\nFLORA        0   0    0    0    0    1    0    1   0    0    0   0     0   0\n```\n:::\n:::\n\n\nWe can see that while the specifc entries of the swapped biadjacency matrix `A.s` are different from those of the original matrix `A` both the row and column degrees are preserved:\n \n\n::: {.cell}\n\n```{.r .cell-code}\n   rowSums(A.s)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   EVELYN     LAURA   THERESA    BRENDA CHARLOTTE   FRANCES   ELEANOR     PEARL \n        8         7         8         7         4         4         4         3 \n     RUTH     VERNE     MYRNA KATHERINE    SYLVIA      NORA     HELEN   DOROTHY \n        4         4         4         6         7         8         5         2 \n   OLIVIA     FLORA \n        2         2 \n```\n:::\n\n```{.r .cell-code}\n   rowSums(A)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   EVELYN     LAURA   THERESA    BRENDA CHARLOTTE   FRANCES   ELEANOR     PEARL \n        8         7         8         7         4         4         4         3 \n     RUTH     VERNE     MYRNA KATHERINE    SYLVIA      NORA     HELEN   DOROTHY \n        4         4         4         6         7         8         5         2 \n   OLIVIA     FLORA \n        2         2 \n```\n:::\n\n```{.r .cell-code}\n   colSums(A.s)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n 6/27   3/2  4/12  9/26  2/25  5/19  3/15  9/16   4/8  6/10  2/23   4/7 11/21 \n    3     3     6     4     8     8    10    14    12     5     4     6     3 \n  8/3 \n    3 \n```\n:::\n\n```{.r .cell-code}\n   colSums(A)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n 6/27   3/2  4/12  9/26  2/25  5/19  3/15  9/16   4/8  6/10  2/23   4/7 11/21 \n    3     3     6     4     8     8    10    14    12     5     4     6     3 \n  8/3 \n    3 \n```\n:::\n:::\n\n\nAnd now we create our graph ensemble with fixed row *and* column degrees, and test our degree anti-correlation hypothesis:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n   set.seed(4567)\n   G <- replicate(500, make.swap(A), simplify = FALSE)\n   corrs <- sapply(G, tm.deg.corr)\n```\n:::\n\n\nPlotting the results gives us:\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](tm-null_files/figure-html/unnamed-chunk-37-1.png){width=672}\n:::\n:::\n\n\nNote that once we fix the person and group degrees, most of the degree correlations observed in the ensemble are negative (below zero). The observed value also does not look as extreme as with the Erdos-Renyi or fixed degree model for either rows or columns separately. \n\nLet's check the p-value at $p < 0.01$:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n   quantile(corrs, probs = 0.01)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n        1% \n-0.3137641 \n```\n:::\n\n```{.r .cell-code}\n   tm.deg.corr(A) < quantile(corrs, probs = 0.01)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   1% \nFALSE \n```\n:::\n:::\n\n\nNot close to significant it seems. How about $p < 0.05$?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n   quantile(corrs, probs = 0.05)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n        5% \n-0.2861612 \n```\n:::\n\n```{.r .cell-code}\n   tm.deg.corr(A) < quantile(corrs, probs = 0.05)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   5% \nFALSE \n```\n:::\n:::\n\n\nThat does not seem to work either! What's the actual p-value?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n   1 - ecdf(abs(corrs))(abs(tm.deg.corr(A)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.062\n```\n:::\n:::\n\n\nAs suspected, the two-tailed test indicates that the hypothesis of degree anti-correlation is no longer justified in these data even using a criterion of $p < 0.05$. Looks like our paper won't be published after all :(\n",
    "supporting": [
      "tm-null_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}